### ISSUE TITLE
[Bug]:  Artifacts:Night_vision_goggles

### ISSUE THREAD

**Issue by Dryst4** [AllTheMods/All-the-mods-9-Sky#100]
### Possible Fixes

Yes

### Modpack Version

1.0

### What happened?

I got a reward from a bounty quest. The item is called Artifacts:Night_vision_goggles. It appears as a square with a question mark in the inventory and is not equippable in any slot.
![Screenshot (57)](https://github.com/AllTheMods/ATM-9/assets/98194386/56fde3d5-6061-4654-b78c-5c3ac05240c4)

**Comment by TheBedrockMaster** [comment]
Fixed in 1.0.1?

**Comment by Dryst4** [comment]
> Fixed in 1.0.1?

Just updated to 1.0.3 and still not fixed

**Comment by billbertking1** [comment]
> > Fixed in 1.0.1?
> 
> 
> 
> Just updated to 1.0.3 and still not fixed

As in not fixed in 1.0.3 you mean it's still the ? item?
If so, that's never gonna change. That's due to the artifacts mod not being installed upon receiving the reward and won't change regardless if Artifacts is added.

**Comment by TheBedrockMaster** [comment]
I was talking about the loot table, not the item

**Comment by billbertking1** [comment]
Ahh! My apologies. I believe it's on the todo list

**Comment by TheBedrockMaster** [comment]
No, YOU'RE right, I'm not the person who made this report, sorry

**Comment by Dryst4** [comment]
Yeah, sorry, I meant the item, but the quest that gave the item no longer gives a random reward so I think that fixes the issue
