### ISSUE TITLE
[Bug]: ATM9TTS: two bugged quests

### ISSUE THREAD

**Issue by LuciusV** [AllTheMods/All-the-mods-9-Sky#101]
### Possible Fixes

Yes

### Modpack Version

1.0.0

### What happened?

1. Powah chapter: starting quest reqires uraninite, unobtainable in skyblock. Suggest change to dielectric paste.
2. Apotheosis Resources chapter Youthful quest reward is "aquaculture" missing item. (Was reported in ATM9nf and not fixed yet)

**Comment by TheBedrockMaster** [comment]
The first one was fixed in 1.0.1

**Comment by ToshibaEC0Microwave** [comment]
Second ones being fixed for next update
