### ISSUE TITLE
[Bug]: Breaking claimed blocks with build gadget

### ISSUE THREAD

**Issue by Satherov** [AllTheMods/All-the-mods-9-Sky#102]
### Possible Fixes

Yes

### Modpack Version

1.0

### What happened?

If you're using the build gadget items, you can manipulate claimed chunks, breaking blocks and grieving items. I don't know if that is something you can fix or the FTB has to fix but I wanted to mention it

**Comment by billbertking1** [comment]
https://github.com/Direwolf20-MC/BuildingGadgets2/issues/66
