### ISSUE TITLE
[Bug]: Igneous Extruder not showing in JEI

### ISSUE THREAD

**Issue by DJDrWright** [AllTheMods/All-the-mods-9-Sky#103]
### Possible Fixes

Yes

### Modpack Version

1.0.0

### What happened?

The recipe is available but the machine does not show up in search. Not sure if there are others missing but I only have 89 pages in JEI.

**Comment by billbertking1** [comment]
Bug with thermal. Implemented a hot fix that's coming in the next update (soon™️)
