### ISSUE TITLE
Unable to obtain kivi block

### ISSUE THREAD

**Issue by Stormdemon29** [AllTheMods/All-the-mods-9-Sky#108]
I have been trying to use the igneous extruder with a block of obsidian underneath it to make kivi but all it's doing is making cobblestone and I can't use it to make a netherack infinitely either as it is not working right. I have supplied pictures of exactly what I'm seeing and doing.
![17175676001745271694888045948719](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/157261094/c7679f65-3cb6-4f6d-9e44-c18d2ef20328)
![17175676685507747753981218875643](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/157261094/e2905a82-f621-423a-ba95-c2ca2d957501)
![1717567695131324789292183831492](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/157261094/689eafc3-2d24-405f-92c4-e26291672a11)
![17175677132972587156455713394870](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/157261094/680a11fb-7bf5-4121-9f37-8c2dfc703042)

**Comment by billbertking1** [comment]
Place water on one side of it and lava on the other side.

For future reference, F2 is screenshot button in game.

**Comment by Stormdemon29** [comment]
> Place water on one side of it and lava on the other side.
> 
> For future reference, F2 is screenshot button in game.

I have both but the recipe is not even showing for kivi. Which I referenced and also I'm using a steam deck so I'm not able to screenshot.

**Comment by billbertking1** [comment]
Are you able to access in the modpack install directory?

**Comment by Stormdemon29** [comment]
If you're trying to ask if I'm on the latest update version of the modpack then yes. If it's about the actual mods I'm able to access those too.

**Comment by billbertking1** [comment]
Ok, if you could navigate to `atm9sky\logs\kubejs` and post the `server.log` and `startup.log` that'd be much appreciated. Those will be able to tell me what broke between 1.0 and 1.1

**Comment by cstalker** [comment]
Funny, i am getting kiva just fine. i am on 1.01

**Comment by cstalker** [comment]
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/8680854/aa5d488f-f7bc-44af-9562-390a092abdf3)

**Comment by oly2o6** [comment]
Visual jei bug, should be fixed in a future version of thermal
