### ISSUE TITLE
Importer and Exporter Quest have the same Subtitle

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#111]
### Modpack Version

1.0.1

### Describe the issue

The subtitle for the quest "Exporter" says "Importing Items" just like the "Importer" Quest.
![2024-06-05_17 44 33](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/fdd8ccb6-1062-45cf-a51f-aaac520fca3a)
![2024-06-05_17 44 34](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/f007f2b1-652c-4cd2-b83d-593b6a7e0690)

**Comment by ToshibaEC0Microwave** [comment]
Being fixed
