### ISSUE TITLE
Mycelial Generator Quests (Optional)

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#112]
### Modpack Version

1.0.1

### Describe the issue

The quests for the mycelial generators, in the "Industrial Foregoing" Chapter are optional even though the quest for doing all the quests isn't.
![2024-06-05_17 36 19](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/725ef4c0-640c-4eb5-ac9e-4fbbba83db64)
![2024-06-05_17 36 31](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/04461092-e68e-4396-bf4a-8b0aab6ea236)

**Comment by ToshibaEC0Microwave** [comment]
Now will be optional!

**Comment by TheBedrockMaster** [comment]
I blame Jonh for this one
