### ISSUE TITLE
Lots of Broken Quests in "Industrial Foregoing" Chapter

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#113]
### Modpack Version

1.0.1, 1.0.2, 1.0.3, 1.0.4

### Describe the issue

A bunch of quest's writing are messed up.
![2024-06-05_17 36 07](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/e8783354-d39a-4bb3-a22f-223f9a59bb6f)
![2024-06-05_18 09 11](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/886faebe-1a23-450c-9f10-f7c25836aaee)
![2024-06-05_18 09 24](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/0a23e610-397a-494b-b777-bc0b870b963c)
![2024-06-05_18 09 34](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/fc2e8bc4-12c9-46da-9042-0fb64744c986)
![2024-06-05_18 09 46](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/28f1648b-a536-46f3-a07d-d1f9307dc730)
![2024-06-05_18 10 08](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/0d1f25ca-a23a-4b65-bb18-404f81de985b)
![2024-06-05_18 10 05](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/911dae80-f0ed-431d-abac-69146d8607e7)
![2024-06-05_18 10 10](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/ae571dd9-80e0-4d97-90aa-694d7f43ed6a)
![2024-06-05_18 10 11](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/63130a08-6df3-4756-a5a8-a442c2432ea1)
![2024-06-05_18 10 12](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/8ef4d48c-e6ac-4d5f-8e43-d0af91e8efca)
![2024-06-05_18 10 14](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/a29564b1-6666-42f1-b0b2-f45dd22abca8)
![2024-06-05_18 10 15](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/4a312b3a-b1f1-401c-bae8-ce14f1dce267)
![2024-06-06_09 00 13](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/4545a9e6-4989-4e39-9806-7d2c29d21397)
![2024-06-06_09 04 28](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/0d01733a-cb2b-42fa-b50a-11dc4b004cb8)
![2024-06-06_09 04 42](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/0a689835-5c11-4943-a489-c33b8b4cb54a)
![2024-06-06_11 08 13](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/69aaa11e-da81-43ba-818a-80167b66d56c)
![2024-06-06_11 38 24](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/a182087c-6422-4dee-a18f-6c2d4502c12e)

**Comment by TheBedrockMaster** [comment]
Still broken in 1.0.3 :(

**Comment by TheBedrockMaster** [comment]
https://github.com/AllTheMods/All-the-mods-9-Sky/pull/269 Fixes this?

**Comment by ToshibaEC0Microwave** [comment]
Will be fixed in next update. Someone (me) forgot to add the IF part of the lang.

**Comment by Jadedfey** [comment]
Will the loot rewards be fixed too for IF? Looks like something got mixed up with that.

**Comment by Ugnasijus1** [comment]
also the same thing is with the productive bees questline 
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/102345753/398ef66f-d4c5-4d39-bb9f-1ac11ab8d33e)
