### ISSUE TITLE
[Quests issues]: Meteorite hunting quest mistake

### ISSUE THREAD

**Issue by Ugnasijus1** [AllTheMods/All-the-mods-9-Sky#117]
### Modpack Version

1.0.1

### Describe the issue

The quest says you get skystone dust from sieving sand, even though you actually get it from dust
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/102345753/82762a7a-9c44-43c5-8513-045bc1f7e0dd)

**Comment by ToshibaEC0Microwave** [comment]
Will be fixed for next update
