### ISSUE TITLE
Thermal Ingots & ATO Ingots

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#123]
### Possible Fixes

Yes

### Modpack Version

1.0.1

### What happened?

The Ingots from Thermal Series are still in JEI and usable for recipes requiring their counterparts from ATO. 
![2024-06-06_08 06 38](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/140266b5-d7b8-4db2-9f84-301892c5a14d)
![2024-06-06_08 06 39](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/9c2ea73c-86dd-4f57-84cb-cdcc873637b1)
![2024-06-06_08 06 40](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/b30b9c3c-6b27-4f93-a197-9a67430cc4f6)
![2024-06-06_08 06 41](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/0cdf0905-479a-4632-b500-1a8106610804)
![2024-06-06_08 06 42](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/6b265fe7-d0b9-4c73-b20b-1f854c074831)
![2024-06-06_08 06 43](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/08f0218f-08c1-43d6-8924-41e2c045ad9c)
![2024-06-06_08 06 43_2](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/0e4cb760-fa64-401f-8917-0e234adf692b)
![2024-06-06_08 06 44](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/4788ee13-5d39-4e36-a87f-141be41559d1)
![2024-06-06_08 06 50](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/d53d1be4-f3e5-4773-afed-845fa861a4c4)
![2024-06-06_08 06 51](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/7f08f750-230c-43e1-a7dc-308b850ccd29)
![2024-06-06_08 07 09](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/6cb2ceae-d6bd-4c5a-a8af-b171d07b2b69)

**Comment by oly2o6** [comment]
Its a temp fix we had to put in place, as thermal wasnt showing in JEI at all before this, going to mark as wont fix for now until we have a way to actually fix this properly

**Comment by TheBedrockMaster** [comment]
No worries :)
