### ISSUE TITLE
[Crash]: i cant fix it

### ISSUE THREAD

**Issue by snipe935** [AllTheMods/All-the-mods-9-Sky#127]
### Possible Fixes

Yes

### Modpack Version

newest

### What happened?

so i have the right ram and it keeps crashing i gave curseforge over 10 gigs of ram and it still keeps on crashing so i need help to fix it

### Crash Log

The game crashed whilst exception in server tick loop Error: java.util.ConcurrentModificationException: null-1

**Comment by Mitchell5200** [comment]
Can't properly help without the actual crash reports, or the latest.log file. As that error message is meaningless to us.
Below instructions copied from Discord

> How do I submit my log? (Client)
> 1. Go to your modpack's folder (You should be able to find an Open Folder button in your launcher)
> 2. Go to crash-reports (If there isn't a crash report, upload hs_err_pid.log or logs/latest.log)
> 3. Upload your latest crash report to https://mclo.gs/ (This will help us understand it, and remove personal info.)
> 4. Copy the link to the report and paste it here.
