### ISSUE TITLE
[Bug]: Flux Dust recipe

### ISSUE THREAD

**Issue by Bodadis** [AllTheMods/All-the-mods-9-Sky#130]
### Possible Fixes

Yes

### Modpack Version

1.0.1

### What happened?

Flux Recipe showing Air instead of Compressed Obsidian.

![2024-06-06_04 14 48](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/171534737/d809b683-2ce5-40e3-8109-acea93f94b24)

**Comment by billbertking1** [comment]
Fixed in dev
