### ISSUE TITLE
[Bug]: No way of getting CropTopia seeds

### ISSUE THREAD

**Issue by King-Tempy** [AllTheMods/All-the-mods-9-Sky#132]
### Possible Fixes

Yes

### Modpack Version

1.01

### What happened?

No way of getting CropTopia seeds

**Comment by TheBedrockMaster** [comment]
Bags of seeds work.

**Comment by DiggityMan420** [comment]
no way for trees either

**Comment by Hamredahl** [comment]
This is gonna be fixed when the Farming for Blockheads Market gets fixed, see #192.
