### ISSUE TITLE
"Youthful" Quest Broken Reward

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#142]
### Modpack Version

1.0.1 & 1.0.2 & 1.0.3

### Describe the issue

The quest "Youthful" in the "Apotheosis" Chapter gives a broken reward (Missing Item), being from Aquaculture.
![2024-06-06_16 30 35](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/e668bd37-a896-4c0c-8b37-c45db9a969c6)

**Comment by ToshibaEC0Microwave** [comment]
Will be fixed next update
