### ISSUE TITLE
"Soulium Seed Base" Quest Weird "i"

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#143]
### Modpack Version

1.0.1

### Describe the issue

In the description for the quest "Soulium Seed Base" in the "Mystical Agriculture" Chapter the word "is" has a weird looking "i".
![2024-06-06_16 01 05](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/67c6476b-f9a5-4a27-b9e3-45d12d94c35b)

**Comment by ToshibaEC0Microwave** [comment]
Looks fine on my end, not sure if there's really a problem with it
