### ISSUE TITLE
[Bug]: Player Simulator can not click sieve with material in it

### ISSUE THREAD

**Issue by SeaOfScrolls** [AllTheMods/All-the-mods-9-Sky#148]
### Possible Fixes

Yes

### Modpack Version

1.0.1

### What happened?

I set up a player simulator to use a list of materials on my sieves. It will place an item into the sieve initially, but will not continue clicking even when set up to do so. It will also not do so when set up to click empty or just click.

**Comment by billbertking1** [comment]
Is your area claimed? Did you enable fake players in your claim?

**Comment by SeaOfScrolls** [comment]
I have tried both claimed and unclaimed, as well as with fake players enabled in a claim.

**Comment by SeaOfScrolls** [comment]
That resolved the issue, thank you very much.
