### ISSUE TITLE
[Bug]: Flux Compactor missing Recipes

### ISSUE THREAD

**Issue by ItsChugg** [AllTheMods/All-the-mods-9-Sky#151]
### Possible Fixes

Yes

### Modpack Version

1.0.1

### What happened?

Flux Compactor does not compact any ore chunks except for vanilla ores.

![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/150368381/cd953b5a-d8fe-413b-892a-1553427316bb)
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/150368381/64cf5917-bd35-4d96-b7c6-35a91a55725a)

**Comment by oly2o6** [comment]
#43
