### ISSUE TITLE
[Quests issues]: Industrial Foregoing quest loot reward bag broken

### ISSUE THREAD

**Issue by bashlee09** [AllTheMods/All-the-mods-9-Sky#153]
### Modpack Version

1.0.1

### Describe the issue

The Loot Reward bag that you get as a reward for some industrial foregoing quests doesn't actually give you anything, it opens a blank screen.

**Comment by AryaElendril** [comment]
I opened the Industrial Foregoing questline in Editing Mode and confirmed that it appears the issue is from the Loot Bag rewards being set to a blank reward pool. 

ATM team will need to update the loot bags to whatever their choice of reward pool would be for those bags!
