### ISSUE TITLE
[Bug]: New Compressed Obsidian Recipe for Flux Dust not functioning

### ISSUE THREAD

**Issue by AryaElendril** [AllTheMods/All-the-mods-9-Sky#154]
### Possible Fixes

Yes

### Modpack Version

1.0.1

### What happened?

When placing AllTheCompress Compressed Obsidian as the bottom block for the flux dust recipe from Flux Networks, the Compressed Obsidian is not treated as the correct block for the recipe. I found the fix to this issue as it appears it was just due to a typo within the KubeJS script located at ```\All the Mods 9 - To the Sky\kubejs\server_scripts\mods\flux.js```.

The current line 18 of the code is:
```if (base.id != 'allthecompressed:obsidian_block_1x') return```

and just needs to be updated to instead say:
```if (base.id != 'allthecompressed:obsidian_1x') return```

The blockID for the compressed obsidian is ```allthecompressed:obsidian_1x``` instead of ```allthecompressed:obsidian_block_1x```.

I believe the same change will need to be made to the KubeJS script at ```\All the Mods 9 - To the Sky\kubejs\client_scripts\jei_add.js``` at line 6:

```let customFlux = new $CreatingFluxRecipe('allthecompressed:obsidan_block_1x', 'minecraft:obsidian', 'minecraft:redstone', 'fluxnetworks:flux_dust')```

would now be:

```let customFlux = new $CreatingFluxRecipe('allthecompressed:obsidan_1x', 'minecraft:obsidian', 'minecraft:redstone', 'fluxnetworks:flux_dust')```

My name is Arya the Elf on Discord and I am within the AllTheMods Discord if you have any questions! ^_^

**Comment by billbertking1** [comment]
I've learned to test things other people wrote prior after this lol

https://github.com/AllTheMods/All-the-mods-9-Sky/commit/1930bad02e4c393e8bc9192c3b11234f1e670ed I fixed it earlier this morning, will be in next update! Thank you
