### ISSUE TITLE
[Crash]: atm9sky not launching The game crashed whilst rendering overlay Error 

### ISSUE THREAD

**Issue by octtoprime** [AllTheMods/All-the-mods-9-Sky#155]
### Possible Fixes

Yes

### Modpack Version

1.0

### What happened?

it worked one day and then the next day the game crashed win i launch the game with a rendering overlay error and i dont now how to fix it 

![Screenshot 2024-06-06 182815](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/145510396/81888633-62d9-4d1d-8569-bcfb876e6b9b)

### Crash Log

https://gist.github.com/octtoprime/78d628fbfb91306ebe1020ff44a389fd

**Comment by oly2o6** [comment]
Can you try redownloading the modpack? If you are on curseforge/singleplayer make sure to open folder and grab your saves folder before downloading a new profile so you can move it over later, reopen if the issue persists

**Comment by octtoprime** [comment]
it take me a little bet to do it but that has fixed the issue
