### ISSUE TITLE
[Bug]: Crafting station Diamond chest UI Lag

### ISSUE THREAD

**Issue by Ticskter** [AllTheMods/All-the-mods-9-Sky#156]
### Possible Fixes

Yes

### Modpack Version

1.0.1

### What happened?

Did a quick search and saw that this bug has been reported about 5 days ago with no response or information on how to create the issue. So i created this bug again with more information. I hope that is OK.

While having a Double Diamond chest from Sophisticated Storage connected to a Crafting station and looking up a recipe with multiple usable items the UI gets extremely laggy.

My setup to create this issue:
Double Diamond Chest roughly filled half way with items.
Crafting Station Connected to the chest.
Searched for "stack upgrade" and clicked on the "stack upgrade Starter Tier" recipe, (at this point no UI lag)  then clicked on "Stack upgrade Tier 1 plus" item in the 3x3 crafting grid, (minimal lag while moving mouse around UI to see names of items) then click on "Stack upgrade Tier 1" items in center of 3x3 grid {the one with the copper recipe}  and now on this screen with the "blank upgrade Base" and the logs rotating through the different usable items there is an EXTREME amount of lag when moving the mouse around the UI.

If i remove the Crafting station and place it down all by its self there is NO UI Lag.
If i open the chest and go through the recipe chain there is NO UI lag.

Also while at the end of writing this bug report, this also happens with a single diamond chest that is filled about half way. 
Also tested with a Vanilla Double chest and the lag is present although very minimal compared to what i stated above.

I would assume that the issue is in fact the crafting station mod as only when in it that this issue occurs.

**Comment by oly2o6** [comment]
Thanks for all of the additional information! We are actually investigating why this is happening at the moment so the additional info will be helpful for a future report to the author
