### ISSUE TITLE
[Bug]: Dying on slab does not spawn a grave

### ISSUE THREAD

**Issue by Kami-no-Shi** [AllTheMods/All-the-mods-9-Sky#158]
### Possible Fixes

Yes

### Modpack Version

1.0.1

### What happened?

Dying on a slab does not spawn a grave and causes player(in this case: Me) to lose all items with no way of getting them back.

**Comment by billbertking1** [comment]
Bug with Corail. There's a command to restore your grave, I believe it's `/tbrestore` or similar

**Comment by Kami-no-Shi** [comment]
I tried that command and it doesnt seem to be enabled.

**Comment by billbertking1** [comment]
Open to LAN -> enable cheats

**Comment by Kami-no-Shi** [comment]
> Open to LAN -> enable cheats

I also forgot to mention this is in a multiplayer world with me and my friends
