### ISSUE TITLE
[Crash]: I can't launch the modpack error (0xc0000005)

### ISSUE THREAD

**Issue by Bapt-727** [AllTheMods/All-the-mods-9-Sky#162]
### Possible Fixes

Yes

### Modpack Version

1.0

### What happened?

I tried to launch this modpacl but every time it crash at the start error (0xc0000005).
I tried to update my graphic card, uninstall and install back java but nothing is working
So if you have any suggestions
Thanks

### Crash Log

https://gist.github.com/Bapt-727/a8588582075bad3abdb9439dd0b8e89d

**Comment by Mitchell5200** [comment]
`C  [atio6axx.dll+0x192b60]` that's an AMD video driver there, but it looks like you also have a NVIDA GPU, so given the error, it's likely your system is not adequately using the GPU, follow the instructions in the link below.
https://www.xda-developers.com/how-force-app-use-discrete-gpu-windows-11/


Below copied from discord
> The `atio6axx` "Problematic frame" in a `hs_err_pid` file, is part of the **AMD** driver for the GPU, there's a bad version of the AMD drivers that instantly crashes on an OpenGL task, 
Reinstall/Fresh install your drivers from https://www.amd.com/en/support
> **IF** you do not have an **AMD GPU**, then you need to set your system to be using that GPU instead of the AMD integrated GPU on the CPU, steps below.
https://www.xda-developers.com/how-force-app-use-discrete-gpu-windows-11/
