### ISSUE TITLE
[Bug]: lan multiplayer not working after first time joining

### ISSUE THREAD

**Issue by sliver-s-pain** [AllTheMods/All-the-mods-9-Sky#164]
### Possible Fixes

Yes

### Modpack Version

atm9sky-1.0.1.zip 

### What happened?

after my friends joined a world we started up a new world and when we try joining eachother in a lan word we get an (index 0 out of bounds for length 0) we have tried deleting the pack and reinstalling and stuff but we cant get it to work

### latest.log

https://gist.github.com/sliver-s-pain/a5ff79ba09f0c7ad59e19c49d8d37614

### Developer reports

i dont think so

**Comment by OvercastWarmth** [comment]
Can confirm that this is still an issue with worlds hosted off of the client. We got the same problem trying to play with our friend using [World Host](https://modrinth.com/mod/world-host), but I don't doubt that the same would hold true in a LAN connection.
