### ISSUE TITLE
[Bug]: Industrial Foregoing laser lens

### ISSUE THREAD

**Issue by rreilly-edr** [AllTheMods/All-the-mods-9-Sky#165]
### Possible Fixes

Yes

### Modpack Version

1.0.1

### What happened?

the only way to get fluorite ore is to use the ore laser drill ( or bees which i am not doing), there is no recipe to craft the lens for the ore laser drill. unless i am missing something.
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/31705381/1d9b9b8d-d9fe-46a0-bc7b-cf9795102f69)

**Comment by billbertking1** [comment]
That's an old recipe. Use dissolution chamber, per JEI.
