### ISSUE TITLE
[Quests issues]: Doesn't have the craft to obtain the rune from Forbidden and Arcanus.

### ISSUE THREAD

**Issue by hollowcraft** [AllTheMods/All-the-mods-9-Sky#167]
### Modpack Version

1.0.1

### Describe the issue

The modpack only has the Dimensional Mineshaft from Occultism to obtain the rune, but the quest doesn't mention that and just appears as a simple quest.

**Comment by asoshinsky** [comment]
The bug is still in version 1.0.8a
