### ISSUE TITLE
[Bug]: AlChemistry recepies not working in compactor and combiner

### ISSUE THREAD

**Issue by Wally00123** [AllTheMods/All-the-mods-9-Sky#169]
### Possible Fixes

Yes

### Modpack Version

1.01

### What happened?

When trying to craft recipes using AlChemistry in the appropriate machines, it always overrides the selected recipe if it shares common ingredients with another based on the first recipe alphabetically (ex - when trying to craft a sapling like Jungle or Oak, always turns to Acacia, when trying to craft water (H2O) always overrides with Hydroxide (HO), etc.

**Comment by TheBedrockMaster** [comment]
This is a part of the Alchemistry mod, you need to pin the recipe for these recipes, not a bug in the modpack.
