### ISSUE TITLE
[Quests issues]: Moss Block/Dirt Seed

### ISSUE THREAD

**Issue by Si3ge-Tech** [AllTheMods/All-the-mods-9-Sky#170]
### Modpack Version

1.0.1

### Describe the issue

In the moss block quest (Getting Started 2, near the end), the text says "4 Dirt Seed", when it should be 4 Grass Seeds. Most likely players don't have Dirt Seeds at that point and should be able to infer Grass is meant, but it confused me for a while.

**Comment by ToshibaEC0Microwave** [comment]
The dirt will now be grass
