### ISSUE TITLE
[Bug]: IronJetpack Undefined and uncraftable

### ISSUE THREAD

**Issue by Bodadis** [AllTheMods/All-the-mods-9-Sky#171]
### Possible Fixes

Yes

### Modpack Version

1.0.2

### What happened?

Modpack version: 1.0.2

When I logged in to my world I got this message when I hovered over the Jetpack I had and also couldn't find them in JEI

![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/171534737/fe3c04a7-692a-44ef-9be5-ad38b498e63b)

**Comment by MindOfNasser** [comment]
same issue here, plus iron jetpacks not showing in JEI
![Screenshot_1](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/45881640/0c6844ee-f927-4805-a175-f3c203963ab3)

**Comment by TheBedrockMaster** [comment]
Can also confirm this happened on my end.

**Comment by calebb13** [comment]
this happened to me too

**Comment by karonte84** [comment]
same here
![Screenshot_2](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/470528/3f27b82c-41a7-4b12-9e34-b85ebe899472)

**Comment by T-D3V** [comment]
Can confirm this one too.

**Comment by billbertking1** [comment]
Fixed in .3
