### ISSUE TITLE
[Bug]: Level Emitters changing values when right clicked

### ISSUE THREAD

**Issue by Bodadis** [AllTheMods/All-the-mods-9-Sky#172]
### Possible Fixes

Yes

### Modpack Version

1.0.1

### What happened?

Modpack Version: 1.0.1

Issue: I'm trying to set up a level emitter to only emit a signal when over a designated number, in this case Buckets worth of Latex. But first of all it sets it to 0.001 B worth of Latex instead of 1B. And when I put in a value it auto changes it to 3000000 B instead.

![2024-06-08_03 42 56](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/171534737/23a2fe92-cfd5-423a-b7e3-7db018aa3dd4)

**Comment by Bodadis** [comment]
It seems to increase each time I right click it.

**Comment by Nyxane** [comment]
Its not possible to increase it past the int limit 2,147,483,647 mB

**Comment by Bodadis** [comment]
> Its not possible to increase it past the int limit 2,147,483,647 mB

I'm not trying to increase it to the int limit, I want like 10k mB or something

**Comment by Nyxane** [comment]
10 000 mili-buckets is 10 buckets worth, not 3 million buckets
3 million buckets works out to 3 billion mili-buckets

**Comment by Nyxane** [comment]
Ok Sorry, i finally understand this bug report, it seems to multiply it by inverse of the 0.001 to auto calculate the amount of mB, but the units seem to be in Buckets,
Try entering, 0.01 into the field, and don't open the menu again otherwise it'll multiply the 10 buckets by 1000

**Comment by Bodadis** [comment]
> Ok Sorry, i finally understand this bug report, it seems to multiply it by inverse of the 0.001 to auto calculate the amount of mB, but the units seem to be in Buckets, Try entering, 0.01 into the field, and don't open the menu again otherwise it'll multiply the 10 buckets by 1000

Yeah I set an amount I was happy with and haven't touched it since lol, but it is an annoying bug that should be solved. Don't know if it's the ATM-team or the AE2-team though
