### ISSUE TITLE
[Bug/Question]: Dirt uncraftable super early game?

### ISSUE THREAD

**Issue by LuckySkye13** [AllTheMods/All-the-mods-9-Sky#173]
### Possible Fixes

Yes

### Modpack Version

1.0.2

### What happened?

Is dirt supposed to be non-craftable in the super early game? The earliest/easiest method I can find is through Mekanism's metallurgic infuser using sand and biofuel... unless I'm missing something? I've clicked through every page of jei for getting dirt, and I tried the classic saplings/compostables into a barrel, and couldn't. Thanks!

**Comment by Bodadis** [comment]
Using plantmaterial in barrels from Ex Deorum can make dirt. There's also this quite early dirt generator.

Xycraft Extractor, Dirt, Xycraft Water Block and a Drying Basin from Integrated Dynamics.
![Dirt generator](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/171534737/3c2ac44c-a137-4b42-a1bf-9a071d1c2494)

**Comment by LuckySkye13** [comment]
Odd... I relaunched my game, didn't change anything in between, and looked at the barrel i tried making dirt in and it's now full of dirt... and now it's actually taking saplings out of my inventory when I right click, and making dirt... the recipe still doesn't show in JEI, but it is working now at least. Not sure what happened, might have just been a glitch during loading?

**Comment by Bodadis** [comment]
> Odd... I relaunched my game, didn't change anything in between, and looked at the barrel i tried making dirt in and it's now full of dirt... and now it's actually taking saplings out of my inventory when I right click, and making dirt... the recipe still doesn't show in JEI, but it is working now at least. Not sure what happened, might have just been a glitch during loading?

I don't know, but the Minecraft barrel makes bone meal whilst the Ex Deorum barrel makes dirt. :)

**Comment by adroslice** [comment]
There's definitely some weird stuff going on with the barrel implementation. There's the issue with its hitbox that makes placing things on top difficult, and manually putting in compostables has a tendency to
- Not show up or
- Show some kind of weird rainbow effect

So it seems like there is both a client-server as well as a rendering issue at play here.

**Comment by LuckySkye13** [comment]
Well, to add another recipe bug... Today I loaded it up and could no longer make steel dust in the infuser... the recipe was just gone, like it had been disabled. Couldn't even just put the enriched iron back in, it just wouldn't accept it. Reloading made it work again

**Comment by TheBedrockMaster** [comment]
Can this be closed?
