### ISSUE TITLE
[Bug]: Slab to Plank recipe gives Log instead

### ISSUE THREAD

**Issue by Hamredahl** [AllTheMods/All-the-mods-9-Sky#175]
### Possible Fixes

Yes

### Modpack Version

1.0.2

### What happened?

Some of the logs are currently craftable with 2 slabs instead of the usual slabs to plank, making them an infinite resource. On a quick check this seems to affect Oak, Acacia, Mangrove and Cherry, but I might have missed some.

<img width="190" alt="SlabToLog" src="https://github.com/AllTheMods/All-the-mods-9-Sky/assets/26722336/a89831a7-cbe1-42fb-8094-b08e1e4ce23a">

**Comment by Hamredahl** [comment]
On further testing, it seems that it's not those specific wood types, but instead random ones each restart of the pack. 

Further testing with only Quark and it's dependencies + JEI installed on a separate pack (Quark version 4.0-455 and Zeta 1.0-16, JEI 15.3.0.4, Forge 47.2.20) does not yield the same error, so I'm holding off on reporting this on the Quark git.

**Comment by billbertking1** [comment]
Enable advanced tooltips by pressing F3+H and post the recipe ID's, it'll tell you which mod adds that recipe

**Comment by Hamredahl** [comment]
A sorry, I edited my last comment around 40 times in the midst of testing and removed that info by mistake. The recipe ID is by Quark (the reason I tested Quark separately), specifically quark:tweaks/crafting/slab_to_block.

<img width="545" alt="SlabsToBlock" src="https://github.com/AllTheMods/All-the-mods-9-Sky/assets/26722336/89d5e6f1-c241-45a4-bedf-1735534f09a0">
