### ISSUE TITLE
[Bug]: Some mod config's resetting between updates

### ISSUE THREAD

**Issue by Nefar1on** [AllTheMods/All-the-mods-9-Sky#178]
### Possible Fixes

Yes

### Modpack Version

1.0.2

### What happened?

When updating from 1.0.0 to 1.0.1 my config for TheOneProbe and my Weather graphics settings reset themselves to default.
I applied my settings again and continued as normal but when I updated to 1.0.2 it reset both of them again.

### latest.log

https://gist.github.com/Nefar1on/3787f6c8e0b414e983ccc170f5c68b0c

**Comment by billbertking1** [comment]
That's because there's configs in the update that override. It's annoying but how it is and we can't do anything about it.
