### ISSUE TITLE
"Engineer's Goggles" Quest Typo

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#181]
### Modpack Version

1.0.2 & 1.0.3

### Describe the issue

The quest "Engineer's Goggles" in the "Create" Chapter spells the word 'contraptions' as "contrations".
![2024-06-08_20 52 26](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/ad97b8cf-e3db-488e-b83c-9072a77c16fe)

**Comment by ToshibaEC0Microwave** [comment]
The P has been added
