### ISSUE TITLE
[Bug]: [1.02-] Industrial Foregoing plastic is incompatible with Pneumaticraft plastic

### ISSUE THREAD

**Issue by shade1822226911** [AllTheMods/All-the-mods-9-Sky#183]
### Possible Fixes

Yes

### Modpack Version

1.02

### What happened?

Industrial Foregoing plastic is incompatible with Pneumaticraft plastic, even though the opposite works
i suggest unifying all plastic unless this is intentional

**Comment by TheBedrockMaster** [comment]
Makes PneumaticCraft a bit harder.
