### ISSUE TITLE
[Minor Bug]: Autofill option from Inventory Tweaks Reforxed not working

### ISSUE THREAD

**Issue by OneComputerGuy** [AllTheMods/All-the-mods-9-Sky#186]
### Possible Fixes

Yes

### Modpack Version

1.0.2

### What happened?

When doing actions that require lots of the same material (building or sieving) the autofill option/behavior is not working which leads to circling to through the hot bar items, IIRC this was working in previous packs but in this one it hasn't worked since 1.0.0

**Comment by billbertking1** [comment]
As for sieves, it's an issue with how ex deorum handles sieves input or similar so the call never triggers for refoxed to replace the stack

**Comment by thedarkcolour** [comment]
I'm away from the computer so I don't know what is wrong. How do you suggest I fix this in Ex Deorum?

**Comment by billbertking1** [comment]
Unsure, I'll dig it up in dev chat and forward it to you in discord though
