### ISSUE TITLE
[Bug]: Ender fluid conduit does not have channels

### ISSUE THREAD

**Issue by DHN4** [AllTheMods/All-the-mods-9-Sky#187]
### Possible Fixes

Yes

### Modpack Version

1.0.2

### What happened?

Ender IO ender fluid pipes should have channels to pipe different fluid on. They do not and act like base fluid pipes. Ender IO ender fluid pipes are not configurable.
Ender IO redstone pipes are not configurable with or without the wrench.
Two pipes in one block (ender fluid and redstone) show missing skin purple and black checkered pattern on intersecting blocks
Since using ender fluid pipe and redstone pipes my game is unable to close normally. Game hangs at saving game. Need to force terminate game to quit. (fixed in 1.0.2)

![iocond](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/108018397/67d9e7b6-ddb0-462d-81d3-6dfb893922f5)

### latest.log

https://gist.github.com/DHN4/620782a973c16838ddc398e0f5d0b60d

**Comment by oly2o6** [comment]
Not a bug, just not implemented in 1.20.1 by eio

**Comment by DHN4** [comment]
Thank you for checking.
