### ISSUE TITLE
[Bug]: Infinite wood through Crafting

### ISSUE THREAD

**Issue by JedDakBunny** [AllTheMods/All-the-mods-9-Sky#188]
### Possible Fixes

Yes

### Modpack Version

1.0.2

### What happened?

I wanted to make a barrel and had 1 less wood than I needed to make it so I wanted to see if I can use 2 slabs to make one plank but alas you make a oak log out of 2 planks giving you infinite wood.
https://youtu.be/lbKbGSBYD_k

**Comment by Hamredahl** [comment]
#175
