### ISSUE TITLE
[Bug]: Flux Sieve not working properly with Diamond Mesh on Crushed Blackstone (Version 1.0.2)

### ISSUE THREAD

**Issue by Netcromancer** [AllTheMods/All-the-mods-9-Sky#189]
### Possible Fixes

Yes

### Modpack Version

1.0.2

### What happened?

When using the Flux Sieve on Crushed Blackstone, if a diamond mesh is used, only Blackstone Pebbles are created. I have tested with a Gold Mesh and was able to get Gunpowder and Basalt Pebbles. I did not test any other meshes. Neither the diamond, nor the gold, produced Ancient Debris or Magma Cream. When using a manual sieve, all components shown in JEI are produced, so it does not appear to be the process of sieving, but the Flux Sieve itself and only on Crushed Blackstone, so far that I have tested.

**Comment by Netcromancer** [comment]
Tested with Dirt and no grass seeds or mycelium seed are produced with any mesh.

**Comment by Netcromancer** [comment]
As of 1.0.3, this is still not working.

**Comment by bryangrossman** [comment]
I still see this as an issue with the 1.1.2 version of the pack. When using the Flux Sieve on Crushed Blackstone, if a diamond mesh is used, only Blackstone Pebbles and gunpowder are dropped when Magma Cream and Ancient Debris are supposed to drop also.   Seems to be the same issue with the gold mesh ...
