### ISSUE TITLE
[Bug]: Mekanism Infused alloy does not appear to be craftable

### ISSUE THREAD

**Issue by Diamondmaster486** [AllTheMods/All-the-mods-9-Sky#191]
### Possible Fixes

Yes

### Modpack Version

1.0.2

### What happened?

The infused alloy from mekanism does not appear to be craftable.  As shown in the images below, there is no listed way to craft it in JEI, nor is it craftable using the normal recipe of iron and redstone in a Metallurgic Infuser. It seems like things can still be crafted with infused alloy without issue.
![2024-06-08_16 32 17](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/172149554/8fefa16f-aae8-414e-af36-5a412eb8c0e4)
![2024-06-08_16 37 50](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/172149554/aee1c512-43e4-4ad2-83cd-456eb0fd06ee)
![2024-06-08_16 32 27](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/172149554/2dbd834f-1070-4421-aa07-aec55e1412d9)

**Comment by billbertking1** [comment]
Does restarting your client fix it?

**Comment by Diamondmaster486** [comment]
Yes it did, I will close the issue
