### ISSUE TITLE
[Bug]: Croptopia seeds and saplings not showing up on farming for blockheads market

### ISSUE THREAD

**Issue by Plaguesoul84** [AllTheMods/All-the-mods-9-Sky#192]
### Possible Fixes

Yes

### Modpack Version

1.0.2

### What happened?

crops and saplings should be on the farming for blockheads market like in atm9 but they arent i think it a config issue cause i dont see a config in the folder for farming with blockheads and theres one in atm9

**Comment by Hamredahl** [comment]
The config in Farming for Blockheads is empty (in both ATM9 and ATM9TtS), as it usually handles many other mods compatibility in other ways. Croptopia is NOT handled by Farming for Blockheads, but supposedly by a datapack usually shipped with Croptopia according to the Farming for Blockheads git (See issue [209](https://github.com/TwelveIterationMods/FarmingForBlockheads/issues/209)). Not that I've seen that work ever, so I'm a bit skeptical. 

Instead, I'm 99% sure that it's a forgotten file in KubeJS startup scripts. The [farmingForBlockheads.js](https://github.com/AllTheMods/ATM-9/blob/main/kubejs/startup_scripts/farmingForBlockheads.js) file from ATM9 startup_scripts folder takes the generated registry of custom market entries found in KubeJS server scripts and inserts them into the market. This file is missing in ATM9TtS even though the custom market entries (and its generator) exist, and a simple copy paste of the file solves the issue. 

So if you wanna fix this for yourself temporarily, copy ATM9\kubejs\startup_scripts\farmingForBlockheads.js and paste it in the ATM9TtS\kubejs\startup_scripts folder. 

Cheers!

**Comment by Plaguesoul84** [comment]
THANK YOU

**Comment by billbertking1** [comment]
Fixed in dev. Thank you, @Hamredahl for reminding us of that!

**Comment by Hamredahl** [comment]
Happy to help!
