### ISSUE TITLE
[Bug]: Diamond Furnace UI with JEI Search

### ISSUE THREAD

**Issue by iChasm03** [AllTheMods/All-the-mods-9-Sky#194]
### Possible Fixes

Yes

### Modpack Version

1.0.3

### What happened?

![image_2024-06-08_193448016](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/27167431/4808e7a6-4f73-49ae-8e65-578cf3edd944)
When using the search feature in JEI and filtering the search (double-clicking the search bar) it shows multiple other UI slots inside a Diamond Furnace.

### latest.log

https://gist.github.com/iChasm03/05d837033dc6a482015f7e160caeb708

**Comment by billbertking1** [comment]
Probably because if you put a factory upgrade in it, those slots are visible. Should go to the iron furnaces GitHub though
