### ISSUE TITLE
[Bug]: Twerk-it-Meal

### ISSUE THREAD

**Issue by Im-Death** [AllTheMods/All-the-mods-9-Sky#195]
### Possible Fixes

Yes

### Modpack Version

1.0.1

### What happened?

The mod TwerkItMeal bypasses the need for a Crux for Mystical Agriculture Crops. So with it, you don't need the necessary crux's for the allthemodium/vibranium/unobtainium, Dragon, and Nether Star seeds.

**Comment by oly2o6** [comment]
We do not have twerkitmeal, we have squatgrow.
