### ISSUE TITLE
Allthemodium and Vibranium missing Info

### ISSUE THREAD

**Issue by DiggityMan420** [AllTheMods/All-the-mods-9-Sky#197]
### Modpack Version

1.0.3

### Describe the issue

![Screenshot_5](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/45196448/595018bf-5adb-40db-adaa-d6e986b4a7cf)
![Screenshot_4](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/45196448/12fce5e3-b1ea-4e89-aa26-593fdf72632a)

**Comment by max0n4ik** [comment]
its old questline
