### ISSUE TITLE
[Bug]: No recipe for the Gaia Spirit Crux

### ISSUE THREAD

**Issue by Bas950** [AllTheMods/All-the-mods-9-Sky#199]
### Possible Fixes

Yes

### Modpack Version

1.0.3

### What happened?

![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/34792838/7b304a75-532b-4d85-833e-fbf110752061)
The crux is implemented but there is no way to make it.

![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/34792838/43483991-bcde-46f7-8df9-adda795009a8)

**Comment by AdimoUK** [comment]
I've had a look in the code and it looks like this was removed deliberately:

![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/667616/b3efb0c9-a5e1-4fef-a3b7-39b853025377)

Would be great if we could get a confirmation from pack owners whether this is a bug or intentional.

**Comment by ReikoAldrakar** [comment]
Any updates on this?
The why would be interseting.
Because they did not make it impossible to farm the seed, you can still farm it in the Phytogenic Insolator.
Only the Garden Cloche and "In Nature" farming was disabled by this
