### ISSUE TITLE
[Bug]: Crimson Iron not obtainable

### ISSUE THREAD

**Issue by Remyrios** [AllTheMods/All-the-mods-9-Sky#200]
### Possible Fixes

Yes

### Modpack Version

1.0.3

### What happened?

Crimson Iron in any shape or form is unobtainable. This locks the player out from attaining all the Silent Gear tool materials alongside the Silent Gear questline not being completable.

**Comment by dalthox** [comment]
you can get it from nether fortresses or the nether fortress gate which gives you tons of fortress loot rolls
