### ISSUE TITLE
[Bug]: Uranium Oxide: Observe Uranium Oxide in a machine

### ISSUE THREAD

**Issue by Nidaelie** [AllTheMods/All-the-mods-9-Sky#201]
### Possible Fixes

Yes

### Modpack Version

1.0.3

### What happened?

quest asking to observe fluid inside a machine not trigering

**Comment by Nidaelie** [comment]
Observe a completed induction matrix not trigerring either

**Comment by Patrick15a** [comment]
Same for Fusion Reactor

**Comment by TheBedrockMaster** [comment]
This has been fixed as of the current release.

**Comment by Ataqan** [comment]
its not fixed for me
