### ISSUE TITLE
[Crash]: Game wont launch upon updating

### ISSUE THREAD

**Issue by HoolaHoops** [AllTheMods/All-the-mods-9-Sky#203]
### Possible Fixes

Yes

### Modpack Version

1.0.3

### What happened?

When I updated the pack, I launched the game, Crash. Exit Code: 1

Things ive tried:
Relaunching
Redownloading
Rebooting PC
Downgrading and playing previous version, which wouldn't launch either
Updating Java
Updating Video Driver
Reallocating RAM

I'm unsure on anything else this could be related too. ATM9 doesnt have the issue, nor does any other pack I try.

Any solutions are welcomed.

Thanks

### Crash Log

No Crash Log

### Latest.Log

https://gist.github.com/HoolaHoops/f9323ae796242611ad50e95675bb9905

**Comment by oly2o6** [comment]
reopen if this is still happening
