### ISSUE TITLE
[Bug]: Please Update Exdeorum to version: 1.36 to fix a Sound ISSUE

### ISSUE THREAD

**Issue by Hakuati** [AllTheMods/All-the-mods-9-Sky#204]
### Possible Fixes

No

### Modpack Version

1.0.3

### What happened?

Issue: https://github.com/thedarkcolour/ExDeorum/issues/87

**Comment by Ozzymud** [comment]
Thank you for this, can confirm, was going nuts trying to muffle the sound :P

**Comment by Pyario** [comment]
@Ozzymud What sound is that? So what's it called? Can't find it.
