### ISSUE TITLE
[Bug]: Cobble Gen Tier 1-5 Not actually auto-outputting on Multiplayer

### ISSUE THREAD

**Issue by mikevmark** [AllTheMods/All-the-mods-9-Sky#207]
### Possible Fixes

Yes

### Modpack Version

1.0.3

### What happened?

The Quest for the Cobble Gen states it will auto-output to an oak drawer however on multiplayer this isn't working. A hopper is required but at least that works. Allow fake players is enabled.

**Comment by Hamredahl** [comment]
The drawer has to be directly on top of the Cobble Gen, the Cobble Gen only auto outputs to an inventory above it, no other direction. Drawers also sometimes need a single cobblestone to already be in it before the Cobble Gen sees it as an acceptable inventory. Was this the case with your setup?

**Comment by mikevmark** [comment]
Of course it was, thanks
