### ISSUE TITLE
Ender tots are annoying

### ISSUE THREAD

**Issue by Kami-no-Shi** [AllTheMods/All-the-mods-9-Sky#209]
Hello im trying to disable the mob ender tot from spawning in my multiplayer world and im looking through the configs for forcecraft and it does not seem to have a thing for certain mobspawns. Anything that i could do to disable them?

**Comment by Tim-Odermatt** [comment]
You could add [You Shall Not Spawn! [Forge/Fabric]](https://www.curseforge.com/minecraft/mc-mods/you-shall-not-spawn) mod to the modpack.

**Comment by keeptpa** [comment]
Yeah indeed. I've set up a mob farm using cursed dirt, It works well but after a while I found my sky base was flood by these tiny problem. Tried search for config but found nothing. Finally get mad about this and set up a command block to repeatedly kill this mob.

**Comment by xTyrael** [comment]
> Yeah indeed. I've set up a mob farm using cursed dirt, It works well but after a while I found my sky base was flood by these tiny problem. Tried search for config but found nothing. Finally get mad about this and set up a command block to repeatedly kill this mob.

You can use "Ender Inhibitor" to stop them from teleporting away

**Comment by keeptpa** [comment]
> > Yeah indeed. I've set up a mob farm using cursed dirt, It works well but after a while I found my sky base was flood by these tiny problem. Tried search for config but found nothing. Finally get mad about this and set up a command block to repeatedly kill this mob.
> 
> You can use "Ender Inhibitor" to stop them from teleporting away

You mean the one in MobGrindingUtil? Does not work for me, Those little guy are still every where. But regular enderman indeed trapped by this.

**Comment by Kami-no-Shi** [comment]
> y this.

The ender inhib does block normal ender man but not the little shits or the angry ender man that comes from them, they just phase through a wall to body you.

**Comment by Tim-Odermatt** [comment]
I have made my Mobgrinder out of 2 layer Blocks.

Since the `big Slimes` managed to phase through the 1 Layer and the `Ender Tots` spawned those `Angry Enderman` inside the blocks somehow when they died.

Now all my `Enderman` just Suffocate in the wall when they get spawned by a `Ender Tot`.

I also use the `Ender Inhibitor`

**Comment by Ozzymud** [comment]
I just pushed everyone one block in instead of into the glass. Also using the ender inhibitor, no more angry endermen outside :)
![javaw_WI6m3PGRqH](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/6426344/668997cd-ce48-4acc-9211-1fece0a29d56)

**Comment by oly2o6** [comment]
Thanks for the mod suggestion to prevent the spawns! Will be going into 1.0,5
