### ISSUE TITLE
[Quests issues]: Productive Bees Gene Sequencing Error

### ISSUE THREAD

**Issue by Ridge-Sanders** [AllTheMods/All-the-mods-9-Sky#211]
### Modpack Version

atm9sky-1.0.3

### Productive Bees Quest Error
Automated Shapeless Crafting Recipe when combining bee genes (in the Create Mixer/Basin) produces a single magenta gene with no data. The resulting product from combining ANY genes in this matter is: "Type: 0%". Impossible to progress beyond this point.

**Comment by shade1822226911** [comment]
Try using the Gene Indexer?

**Comment by Ridge-Sanders** [comment]
The Gene Indexer only functions as a bee gene storage block.

**Comment by TheBedrockMaster** [comment]
Why is this a quest bug?
