### ISSUE TITLE
[Quests issues]: Urananite vs Uraninite

### ISSUE THREAD

**Issue by Si3ge-Tech** [AllTheMods/All-the-mods-9-Sky#212]
### Modpack Version

1.0.1

### Describe the issue

Quest line "Powah", quest "Reactor (Starter)" should be Uran**i**nite not Uran**a**nite.

**Comment by MindOfNasser** [comment]
Fixed in the newest updates, just update the pack.

**Comment by Si3ge-Tech** [comment]
Sweet thx, and srry lol
