### ISSUE TITLE
[Bug]: Ancient Debris Bug

### ISSUE THREAD

**Issue by Grant-K** [AllTheMods/All-the-mods-9-Sky#215]
### Possible Fixes

Yes

### Modpack Version

1.0.3

### What happened?

The Laser Drill From Industrial Foregoing seems to have a small niece bug
If the Laser Drill is rotated one way it wont work with the base when rotated the other way it will. The animated face of the laser drill must be again the base (its animated on two opposite sides. Otherwise the laser drill will say 404 error. It also seems that depth doesnt currently matter in this pack.
![2024-06-09_22 28 30](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/26666089/e8e64e9a-2b11-46c4-b02a-468655cb8c81)
![2024-06-09_22 28 37](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/26666089/e32ae19c-7ded-4b59-8e18-41c56c534b88)
![2024-06-09_22 28 43](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/26666089/e7c7f947-caa6-41e4-badd-eda644eb279f)
![2024-06-09_22 28 49](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/26666089/a7695e51-e016-4c9d-9c85-efc4f07c7dc8)

**Comment by Grant-K** [comment]
> If I remember correctly there's a "hole" on the other side of the base that needs to face the base, within a certain range.

That's incorrect if you note the screenshots provided it's the rectangler shape that seems to indicate the issues when the formentioned shape is facing the base no issue if the fromentioned shape is not we encounter the described error. P.S. this was tested in 2 different white-list biomes and with multiple different y levels set in the base block

**Comment by billbertking1** [comment]
Ah! Those pictures didn't load when I originally responded. Some times it takes a minute to register the base but if it's not picking up after 15-30 sec, I recommend posting it on the industrial foregoing GitHub.

**Comment by Grant-K** [comment]
> Ah! Those pictures didn't load when I originally responded. Some times it takes a minute to register the base but if it's not picking up after 15-30 sec, I recommend posting it on the industrial foregoing GitHub.

It's not an issue of not picking up its literally a matter of block orientation determine if the device will function pretty much at all the 404 not found error won't even attempt to run at all while in other orientation it functions as intended

**Comment by Petrify** [comment]
The Laser Drill is directional, the base needs to be in it's working area which is a 3x3x3 cube centered on the face of the laser drill with the hole. If there is no Laser Base found in said area, _404 Not Found_ will show up. The working area can be seen using the button in the UI of the laser drill.

**Comment by Grant-K** [comment]
Ah that very good to know if thats intentional Let me know and ill close this thread

**Comment by Grant-K** [comment]
Seems to be working intentionally closing report!
