### ISSUE TITLE
[Bug]: Smithing Template, too easy recipe

### ISSUE THREAD

**Issue by Bodadis** [AllTheMods/All-the-mods-9-Sky#217]
### Possible Fixes

Yes

### Modpack Version

1.0.3

### What happened?

Smithing Template got a very easy recipe, not intended I guess?

![bild_2024-06-10_102428068](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/171534737/b123a6d5-4b8b-42aa-a449-ece3f4a55d77)

**Comment by billbertking1** [comment]
Fixed in dev...oops
