### ISSUE TITLE
[Bug]: Flux Compactor wont compress Osmium Ore Chuncks

### ISSUE THREAD

**Issue by LayZ4ever** [AllTheMods/All-the-mods-9-Sky#218]
### Possible Fixes

Yes

### Modpack Version

1.0.3

### What happened?

Flux Compactor won't compress Osmium Ore Chunks.
https://github.com/AllTheMods/All-the-mods-9-Sky/assets/118476308/e16565a5-939a-4432-abe0-4e573fe768b0
P.S. The modpack is hosted on a server. If I need to provide more information, please don't hesitate to let me know.

### latest.log

https://gist.github.com/LayZ4ever/e53b539ca0e0e9725838fb1af4b24857

**Comment by Timeraa** [comment]
Can confirm

**Comment by new-3** [comment]
can confirm
https://discord.com/channels/254530689225981953/1245715508381093982/1249601620099072062
