### ISSUE TITLE
[Bug]: Refined Storage not detecting my Crafting Grid

### ISSUE THREAD

**Issue by Nefar1on** [AllTheMods/All-the-mods-9-Sky#219]
### Possible Fixes

Yes

### Modpack Version

1.0.3

### What happened?

Every time I load into my world my cables stop detecting that they are connected to the Controller. I try to access the Crafting Grid on a separate island I built and the crafting grid isn't detected, when I break the cable on the controller and then replace it, it suddenly detects the grid again.

![2024-06-10_20-22-01](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/22462393/459ecc15-8e4f-418b-bcbb-0cd4dd9c9971)

### latest.log

https://gist.github.com/Nefar1on/93355e76184504f4474af7584726b6ec#file-2024-06-10-1-log

**Comment by Tim-Odermatt** [comment]
I have the same issue, every time i load into my world, all my `Drawer Controller` stops getting detected by the `External Storage`.

My External Storage connection is like 2 chunks away from my Refined Storage Controller.

Every time this happens i have to break 1 Cable and place it again. For the System to know that there is something important over there.

**Comment by Nefar1on** [comment]
> I have the same issue, every time i load into my world, my `Drawer Controller` stops getting detected by the `External Storage` Cable.
> 
> My `External Storage` connection is like 2 chunks away from my Refined Storage `Controller`.
> 
> Every time this happens i have to break 1 `Cable` and place it again. For the System to know that there is something important over there.

As of update 1.0.4 this seems to have been fixed for me, can you confirm if it's been fixed for you too.

**Comment by Tim-Odermatt** [comment]
I have updated the modpack, but the bug still happens.

https://mega.nz/file/pzM3kAKT#ogf_7IDxlXLc1jyuYVn3fCnsIVIiDOPQeR_fcxOoe8Q

**Comment by oly2o6** [comment]
I cant fix this.
