### ISSUE TITLE
[Bug]: Quest description mistake in Mekanism questline

### ISSUE THREAD

**Issue by Tim-Odermatt** [AllTheMods/All-the-mods-9-Sky#222]
### Possible Fixes

Yes

### Modpack Version

1.0.3

### What happened?

the last Quest in the Mekanism questline states that you should heat over to the `Mekanism: Reactors` questline, but the only other questline is called `Mekanism: Advanced`.

![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/91256797/99955d87-b3bd-4745-a0a2-e73dcfff20ee)
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/91256797/4696e583-7143-4352-bb64-0c2ad436b853)

**Comment by TheBedrockMaster** [comment]
This is a quest bug.
