### ISSUE TITLE
[Bug]: Productive Trees recipes needed

### ISSUE THREAD

**Issue by rewenx** [AllTheMods/All-the-mods-9-Sky#223]
### Possible Fixes

Yes

### Modpack Version

1.0.3

### What happened?

As of the latest version, there is no apparent way to obtain **Black Ember Sapling**. It is usually obtainable as loot in Bastions.

This has a cascade effect since this tree is needed to obtain other trees via pollination.

As a suggestion, it might be good to somehow inform that the **Soul Tree Sapling** comes from end city loot chests.

**Comment by TheBedrockMaster** [comment]
Bastions are here now :)
