### ISSUE TITLE
[Crash]: "Gateway of Overworldian Nights" causes ticking entity crash on completion

### ISSUE THREAD

**Issue by rewenx** [AllTheMods/All-the-mods-9-Sky#224]
### Possible Fixes

Yes

### Modpack Version

1.0.3

### What happened?

After you defeat all the waves, a crash occurs while generating loot. I generated a fresh new world on the latest version to test this crash, and it is reproducible. 

[crash-2024-06-10_09.00.07-server.txt](https://github.com/user-attachments/files/15774544/crash-2024-06-10_09.00.07-server.txt)

**Comments**
From what I was able to gather, the methods `DungeonLootTables.lambda$static$17`, and `Random.nextInt` (Ars Nouvou) "requires a positive integer as an argument, but a non-positive integer was provided". 

### latest.log

https://mclo.gs/KccF4nT

**Comment by rewenx** [comment]
Oops, I noticed this was already reported. Please ignore.

**Comment by Lauriichan** [comment]
It seems like this was fixed with [Ars Nouveau 4.12.0](https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/5433309) so simply updating the mod should fix this issue
