### ISSUE TITLE
[Bug]: The one probe does not show extended information

### ISSUE THREAD

**Issue by LuciusV** [AllTheMods/All-the-mods-9-Sky#225]
### Possible Fixes

Yes

### Modpack Version

1.0.3

### What happened?

After update to 1.0.3, I can no longer see extended information (fluid levels, bee stats, container content) in TOP overlay (configuration set to probe not needed not). Doesnt matter sneaking or not.

**Comment by Ashenback** [comment]
@TheBedrockMaster What was The One Probe replaced with as I can't find any of the other mods doing a entity tip

**Comment by Ashenback** [comment]
nvm figured it out, Jade replaced it
