### ISSUE TITLE
[INFO] Mod Suggestion ?

### ISSUE THREAD

**Issue by Yan-COSTODE** [AllTheMods/All-the-mods-9-Sky#227]
I wanted to know if we can suggest mod to add like we did in ATM9.

And if we can, i would really like [Mahou Tsukai](https://www.curseforge.com/minecraft/mc-mods/mahou-tsukai)

Thanks you.

**Comment by oly2o6** [comment]
Mahou will not be added, there are a bunch of other options in this modpack and it was a design decision not to include it.
