### ISSUE TITLE
[MOD]: SUGGESTION

### ISSUE THREAD

**Issue by Zanolini21** [AllTheMods/All-the-mods-9-Sky#228]
### Possible Fixes

Yes

### Modpack Version

atm9 to the sky

### What happened?

Im sorry about this but i would love to suggest if you guys could add a mod called toolbelt just like its on atm8 and i think on atm9 as well so i can store all tools and not have them in my inv all the time and store them in backpack

**Comment by Tim-Odermatt** [comment]
you could use `Sophisticated Backpacks` with the `Tool Swapper Upgrade`.

```
Tool Swapper Upgrade 
Automatically swaps item in player's hand for the one effective on the block/entity when these are left clicked. 
Sophisticated Backpacks
```

**Comment by oly2o6** [comment]
Ill add it to the list to be looked into
