### ISSUE TITLE
[Quests issues]: Iesnium (Occultism)

### ISSUE THREAD

**Issue by VerigormHH** [AllTheMods/All-the-mods-9-Sky#231]
### Modpack Version

1.0.3

### Describe the issue

How do you mine Iesnium in a void nether? I tried the Divination rod near some fortresses, but nothing happens.

**Comment by VerigormHH** [comment]
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/168209111/92a121ed-c722-4674-9f5c-9b8f6c28a5c4)

**Comment by billbertking1** [comment]
Sieve blackstone with netherite mesh

**Comment by VerigormHH** [comment]
Because you need Iesnium for the mineshaft?

![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/168209111/5d4ac415-2e77-4793-ba9e-fd6a5c216a78)

Even IF it was possible, the quest tree would still be buggy:

![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/168209111/7fe58426-3a7a-4979-acd7-a25544b1203a)

**Comment by VerigormHH** [comment]
> Sieve blackstone with netherite mesh

Life saver :) Thx.

**Comment by VerigormHH** [comment]
Nether is a void. So you only find fortresses. 
With the hint of @billbertking1  I am able to start the mineshaft-ritual.

So now only quests have to be fixed. :)
