### ISSUE TITLE
[Bug]: Spatial IO causing Corrupted World

### ISSUE THREAD

**Issue by ederekmoore** [AllTheMods/All-the-mods-9-Sky#238]
### Possible Fixes

Yes

### Modpack Version

1.0.3

### What happened?

After using spatial IO to move my AE2 system, my world became stuck on the saving world screen when trying to exit, and upon reentering the game all blocks are missing. The blocks are still represented, but they don't seem to actually exist, also I was able to fall into the void to about -3000 without getting TP'd back up. I have only replicated the bug a couple times, and only with attempting to move my AE2 system since its a pain to recover the world afterwards, but it seems that putting something into a spacial IO drive, moving its location, and reconstructing it in the overworld causes some sort of data corruption.

### latest.log

https://gist.github.com/ederekmoore/4bea54ca74ab19191140579b5c4016b3

**Comment by ederekmoore** [comment]
It seems that spatial IO is not the sole cause of corrupted world data, for some reason using the level emitter from AE2 to restrict an export cable that is running into an RFTools crafter also seems to cause corrupted world data. Another possible cause is stacking too many storage upgrades into a functional storage barrel. Using both of those actions I was able to reliably repeat the bug several times, even after deleting the whole modpack and trying on a fresh install.

**Comment by oly2o6** [comment]
Yeah I think it just depends on what you are moving... that is alot
