### ISSUE TITLE
[Crash]: sophisicated storage hopper upgrade causing chunk ban

### ISSUE THREAD

**Issue by XxTHKxX** [AllTheMods/All-the-mods-9-Sky#239]
### Possible Fixes

Yes

### Modpack Version

1.0.2

### What happened?

Player put an hopper upgrade into a sophisicated storage chest, and now whenever the chunk where that chest is located in loads at all, the entire server crash without even getting a chance to give out a "server closed" message

### Crash Log

https://gist.github.com/XxTHKxX/080911c754aaf6dc601c3a478421b114

### Latest.Log

https://gist.github.com/XxTHKxX/4268395231b0aa33703827ce11774b24

**Comment by oly2o6** [comment]
World/server-config/forge-server.toml, enable the remove erroring block/entities
