### ISSUE TITLE
[Bug]: Botania enchanter dont work

### ISSUE THREAD

**Issue by LayZ4ever** [AllTheMods/All-the-mods-9-Sky#240]
### Possible Fixes

Yes

### Modpack Version

1.0.3

### What happened?

It won't enchant the placed item.

https://github.com/AllTheMods/All-the-mods-9-Sky/assets/118476308/f81d15a1-9866-43ba-b3fc-9e8aa2cadbef

### latest.log

https://gist.github.com/LayZ4ever/651ee21805b87770caf7ab94bb8e347d

**Comment by DevilMayCryIfrit** [comment]
Sharpness on a pickaxe?
