### ISSUE TITLE
[Bug]: summoning alter recipe issues can not progress

### ISSUE THREAD

**Issue by hi4444** [AllTheMods/All-the-mods-9-Sky#241]
### Possible Fixes

Yes

### Modpack Version

1.0.1

### What happened?

In the recipe file "summoning.json," there was an issue where multiple instances of the same item were allowed to be stacked together. For example, when crafting "piglich," you actually needed 3 unobtanium items separately instead of stacked together, as the recipes were allowing multiple stacks.
ServerEvents.recipes(event => {

    //altar
    event.shaped('summoningrituals:altar', [`GRG`, `SWS`, ` S `], {
        G: `minecraft:gold_ingot`,
        R: `minecraft:red_carpet`,
        S: `minecraft:stone`,
        W: `minecraft:oak_log`
    })

    //blizz
    event.recipes.summoningrituals
    .altar('minecraft:blaze_powder')
    .sacrifice('minecraft:blaze')
    .input('2x minecraft:ice')
    .input('4x minecraft:snowball')
    .input('2x minecraft:snow_block')
    .mobOutput('thermal:blizz')

    //basalz
    event.recipes.summoningrituals
    .altar('minecraft:blaze_powder')
    .sacrifice('minecraft:blaze')
    .input('4x #forge:dusts/obsidian')
    .input('2x minecraft:stone')
    .input('minecraft:dirt')
    .mobOutput('thermal:basalz')

    //chicken
    event.recipes.summoningrituals
    .altar('minecraft:wheat_seeds')
    .input('2x minecraft:dirt')
    .input('minecraft:grass')
    .input('2x minecraft:bone_meal')
    .input('minecraft:clay')
    .input('minecraft:grass_block')
    .input('minecraft:stone')
    .mobOutput('minecraft:chicken')

    //cow
    event.recipes.summoningrituals
    .altar('minecraft:wheat')
    .input('minecraft:leather')
    .input('minecraft:grass')
    .input('minecraft:bone_meal')
    .input('minecraft:dirt')
    .input('minecraft:clay')
    .input('minecraft:grass_block')
    .input('minecraft:stone')
    .input('minecraft:hay_block')
    .mobOutput('minecraft:cow')

    //sheep
    event.recipes.summoningrituals
    .altar('minecraft:string')
    .input('2x minecraft:dirt')
    .input('minecraft:grass')
    .input('minecraft:bone_meal')
    .input('minecraft:clay')
    .input('minecraft:grass_block')
    .input('minecraft:stone')
    .input('minecraft:white_wool')
    .mobOutput('minecraft:sheep')

    //pig
    event.recipes.summoningrituals
    .altar('minecraft:carrot')
    .input('2x minecraft:dirt')
    .input('minecraft:grass')
    .input('minecraft:bone_meal')
    .input('minecraft:clay')
    .input('minecraft:grass_block')
    .input('minecraft:stone')
    .input('thermal:carrot_block')
    .mobOutput('minecraft:pig')

    //fox
    event.recipes.summoningrituals
    .altar('minecraft:sweet_berries')
    .input('2x minecraft:dirt')
    .input('minecraft:grass')
    .input('minecraft:bone_meal')
    .input('minecraft:clay')
    .input('minecraft:grass_block')
    .input('minecraft:stone')
    .input('minecraft:spruce_sapling')
    .mobOutput('minecraft:fox')

    //bat
    event.recipes.summoningrituals
    .altar('minecraft:torch')
    .input('2x minecraft:dirt')
    .input('minecraft:grass')
    .input('minecraft:bone_meal')
    .input('minecraft:clay')
    .input('minecraft:grass_block')
    .input('minecraft:stone')
    .input('minecraft:coal_block')
    .mobOutput('minecraft:bat')

    //wolf
    event.recipes.summoningrituals
    .altar('minecraft:bone')   
    .input('2x minecraft:dirt')
    .input('minecraft:grass')
    .input('minecraft:bone_meal')
    .input('minecraft:clay')
    .input('minecraft:grass_block')
    .input('minecraft:stone')
    .input('minecraft:bone_block')
    .mobOutput('minecraft:wolf')

    //cat
    event.recipes.summoningrituals
    .altar('minecraft:cod')   
    .input('minecraft:dirt')
    .input('2x minecraft:grass')
    .input('minecraft:bone_meal')
    .input('minecraft:clay')
    .input('minecraft:grass_block')
    .input('minecraft:stone')
    .input('minecraft:cooked_cod')
    .mobOutput('minecraft:cat')
    
    //bee
    event.recipes.summoningrituals
    .altar('minecraft:glass_bottle')   
    .input('2x minecraft:dirt')
    .input('minecraft:grass')
    .input('minecraft:bone_meal')
    .input('minecraft:clay')
    .input('minecraft:grass_block')
    .input('minecraft:stone')
    .input('minecraft:sugar')
    .mobOutput('minecraft:bee')

    //slime
    event.recipes.summoningrituals
    .altar('minecraft:milk_bucket')
    .input('4x #forge:slimeballs')
    .input('2x minecraft:stone')
    .input('minecraft:dirt')
    .mobOutput('minecraft:slime')

    //squid
    event.recipes.summoningrituals
    .altar('minecraft:water_bucket')
    .input('4x minecraft:black_dye')
    .input('2x minecraft:stone')
    .input('minecraft:dirt')
    .mobOutput('minecraft:squid')

    //piglich
    event.recipes.summoningrituals
    .altar('enderio:frank_n_zombie')
    .input('3x allthemodium:unobtainium_ingot')
    .input('forcecraft:treasure_core')
    .input('projecte:red_matter')
    .mobOutput('allthemodium:piglich')
})

**Comment by oly2o6** [comment]
yes they stack together but the recipes still work, you just need to make sure the .catalyst item goes in last.

**Comment by RobertLSnead** [comment]
Having trouble with spawning pig, not sure what is the hold up and yes the catalyst was added last, it doesn't seem to recognize it no matter what I try, using latest version, correction nothing wants to spawn in...

**Comment by RobertLSnead** [comment]
this appears to be a bug in the mod Summing Rituals for stack items
https://github.com/AlmostReliable/summoningrituals/issues/29

**Comment by Rafrpt** [comment]
I had the same issue what I did was get a lot of cows and turn raw beef with the Force rod into raw porkchop and then use the raw porkchop in the soul extraction in a soul jar then use the soul jars in the infusion crafting to make pig seeds then get pig essence and use it in a soulium spawner then you got pigs. it is annoying but that is how to get pigs.
