### ISSUE TITLE
[Bug]: Frame drop problem

### ISSUE THREAD

**Issue by cnluban** [AllTheMods/All-the-mods-9-Sky#244]
### Possible Fixes

Yes

### Modpack Version

1.0.3

### What happened?

When the game reaches a certain level, it will drop frames after playing for a while and keep adjusting to one frame. However, when entering the end or the hell gate and returning to the main world, the frame will not drop, but it will drop again after a while.

**Comment by oly2o6** [comment]
cant repo, more info needed
