### ISSUE TITLE
[Bug]: unobtainable soul lava

### ISSUE THREAD

**Issue by shade1822226911** [AllTheMods/All-the-mods-9-Sky#245]
### Possible Fixes

Yes

### Modpack Version

1.03

### What happened?

there is no way to get soul lava other than the bee, which needs soul lava itself

**Comment by Ozzymud** [comment]
Not the intended way, but some quest gives a Mekanism tank of it. Not that it has many uses... only one i see is for Pneumaticarft. There is no config for it to work under Powah Thermo gens like in ATM9 normal.

**Comment by shade1822226911** [comment]
Ok, thanks for the info
i thought it actually worked on thermo gens but blazing crystal is the second best option
