### ISSUE TITLE
[Bug]: Gadgets Missing after Updating

### ISSUE THREAD

**Issue by MindOfNasser** [AllTheMods/All-the-mods-9-Sky#248]
### Possible Fixes

Yes

### Modpack Version

1.0.4

### What happened?

after updating from 1.0.3 to 1.0.4 all my items in gadgets slots gone, i might understand because of increasing, the slots but atleast give us a heads up on the Update **Patch Notes**, so we won't lose any items :p
![Screenshot_1](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/45881640/9464c65a-b140-479a-8ecb-553d8592190b)

**Comment by Grant-K** [comment]
Increasing slots shouldn't delete items I did it on my end in 1.0.3 no issue

**Comment by oly2o6** [comment]
Is this on singleplayer or a server?

**Comment by PiggyWhiskey** [comment]
I experienced this on a Single Player instance
