### ISSUE TITLE
[Bug]: Upgrading from 1.0.3 to 1.0.4 - Crash + Missing Items

### ISSUE THREAD

**Issue by PiggyWhiskey** [AllTheMods/All-the-mods-9-Sky#250]
### Possible Fixes

Yes

### Modpack Version

1.0.4

### What happened?

Upgrade from 1.0.3 to 1.0.4
Initial world load crashed (From Immersive Engineering Global Wire Network?)
[crash-2024-06-14_14.11.24-server.txt](https://github.com/user-attachments/files/15831525/crash-2024-06-14_14.11.24-server.txt)

Second world load attempt was successful, however all Baubles were missing (Magnet/Backpack) and ProjectE Alchemical Bag was empty (Repair Talismans + Tools) which was on the hotbar.

I'm unable to replicate the issue after this occurred.
After rolling back to a backup before the update, all baubles are still missing (I hadn't made the Alch bag at this stage)

**Comment by PiggyWhiskey** [comment]
#248 beat me to the report

**Comment by Epicycle23** [comment]
Experienced exactly the same.
On top of the baubles other items are just gone as well, like the netherite smithing template for example.

**Comment by oly2o6** [comment]
Closing this as a duplicate, as for the artifacts:golden_hook that one appears to have snuck into the rewards table, artifacts was never in sky or intended to be
