### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Bodadis** [AllTheMods/All-the-mods-9-Sky#251]
### Possible Fixes

Yes

### Modpack Version

1.0.3 and 1.0.4

### What happened?

When I put in the Upgrade Sanguine Reverter this machine gets this texture.
It's the mod Blood Magic and the machine is Alchemical Reaction Chamber.

![2024-06-14_01 46 13](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/171534737/e0a1ed4b-edba-4c2b-a5ee-1eab3405580d)
![2024-06-14_01 46 21](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/171534737/daa0b872-99a7-4f48-bf57-03ba0e3e38bc)

### Developer reports

https://github.com/WayofTime/BloodMagic/issues

**Comment by TheBedrockMaster** [comment]
I believe this is a bug on Blood Magic's end.

**Comment by oly2o6** [comment]
Correct, this appears to be a blood magic issue
