### ISSUE TITLE
[Bug]: Repair talisman - doubled recipe

### ISSUE THREAD

**Issue by StefanoLazzaroni** [AllTheMods/All-the-mods-9-Sky#253]
### Possible Fixes

Yes

### Modpack Version

1.0.4

### What happened?

![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/44039735/72e65f3a-8f3e-4361-9131-41cf00c1112c)

There is simply a doubled recipe (exact same recipe) for the same item

**Comment by Ozzymud** [comment]
It is not the exact same recipe, it appears to be a mirrored one, still useless imo :P

**Comment by StefanoLazzaroni** [comment]
Damn you're right. I'm so stupid i didn't noticed it

**Comment by TheBedrockMaster** [comment]
This is intended, this can be closed
