### ISSUE TITLE
[Bug]: Angel Ring

### ISSUE THREAD

**Issue by Grant-K** [AllTheMods/All-the-mods-9-Sky#254]
### Possible Fixes

Yes

### Modpack Version

1.0.3

### What happened?

When a User equips the basic angel ring if said user has under aprox 6 levels of xp there will see a red text above their hotbar saying angel ring fuel low or something of that sort. The angel ring is currently set by default not to consume xp. About idk 20 lines below the xp setting is an option it disable the warning message. So could that please be fixed in an future update. Right now 1.0.4 just dropped so maybe 1.0.5?

**Comment by TheBedrockMaster** [comment]
https://github.com/AllTheMods/All-the-mods-9-Sky/issues/176

**Comment by Grant-K** [comment]
Line 42 in angelring-common.toml Should be set to -1 
"#Defines at what XP Level to start displaying a warning of low XP for the Classic Angel Ring. Set to -1 to disable.
	#Range: > -1
	XPWarningLevel = -1"
The quoted text is pertaining to the classic ring and that last line XPWarningLevel needs to equal -1 to disable the text popup and it is line 42 in the formentioned file

**Comment by Xiantrius** [comment]
same problem please fix this mod thx.
