### ISSUE TITLE
[Bug]: Awakened Draconium Dust not obtainable in game

### ISSUE THREAD

**Issue by TheNamesJosh** [AllTheMods/All-the-mods-9-Sky#255]
### Possible Fixes

Yes

### Modpack Version

1.0.4

### What happened?

MOD: Draconic Evolution

Pressing R on awakened draconium dust in the game does nothing.

There is no recipe for it, as it is used to make the bees that im currently in the process of trying to make.

an issue i found here:
https://github.com/Draconic-Inc/Draconic-Evolution/issues/1593

A recipe should be added by crushing ingots.

**Comment by TheBedrockMaster** [comment]
Sounds like that's on the mod's end.

**Comment by TheNamesJosh** [comment]
> Sounds like that's on the mod's end.

The issue is the link I have attached is the mods from DE say it's added but it's up to the modpack or mods of different mods (ie mek thermal) to make a recipe for it. Shoukd I go make a bug ticket on there as well?

**Comment by cnluban** [comment]
I also encountered this bug

**Comment by TheBedrockMaster** [comment]
Weird

**Comment by oly2o6** [comment]
"Awakened draconium dust only exists for possible future implementation and so that mods like thermal or mekanism can add grinding recipes."

**Comment by EpicCraft1997** [comment]
Why has this been closed, without the dust we can’t make the chaos bee spawn egg

**Comment by charlesgael** [comment]
Hello,
Quick proposition, was able to add it through KubeJS adding the following recipe (idk if balanced or not)

```
    event.custom({
        type: 'thermal:pulverizer',
        ingredients: [
            Ingredient.of('draconicevolution:awakened_draconium_ingot').toJson()
        ],
        results: [
            Item.of('draconicevolution:awakened_draconium_dust')
        ],
        processingTime: 100
    })
```

in the file `kubejs/server_scripts/mods/thermal/recipes.js`
