### ISSUE TITLE
[Crash]: Gateway of Otherworldian Nights + Crash log

### ISSUE THREAD

**Issue by Bodadis** [AllTheMods/All-the-mods-9-Sky#256]
### Possible Fixes

Yes

### Modpack Version

1.0.4

### What happened?

I did the Gateway of Otherworldian Nights for fun and I crashed after I completing and the loot rolled. Probably something in the loot-rolls that's causing but I don't know what.

I have not installed any other mod (only resource pack for Pipez-mod)

### Crash Log

https://gist.github.com/Bodadis/09bdd33268fc4b8adea5ad10e5d420dd

**Comment by github-bwb** [comment]
[crash-2024-06-14_08.49.18-server.txt](https://github.com/user-attachments/files/15840397/crash-2024-06-14_08.49.18-server.txt)
[crash-2024-06-14_09.16.33-server.txt](https://github.com/user-attachments/files/15840400/crash-2024-06-14_09.16.33-server.txt)

Same for me, here is a couple more server crash logs.

**Comment by oly2o6** [comment]
Will be fixed in 1.0.5!

**Comment by oly2o6** [comment]
For more context we finally found a way to prevent this issue moving forward

**Comment by phit** [comment]
i posted a fix here basically when the release happened.. https://github.com/AllTheMods/All-the-mods-9-Sky/issues/159#issuecomment-2155227534
