### ISSUE TITLE
"Industrial Foregoing" Quest

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#258]
### Modpack Version

1.0.4

### Describe the issue

The quest "Industrial Foregoing" in the "Star" Chapter requires "Tiny Dry Rubber (Deprecated)" for some reason, I would have it just be dry rubber.
![2024-06-14_22 24 20](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/4b02dcd3-36c1-415e-a031-6736c05f5d20)

**Comment by ToshibaEC0Microwave** [comment]
Now will be normal dry rubber
