### ISSUE TITLE
[Bug]: Refined storage stop working

### ISSUE THREAD

**Issue by Daminin11** [AllTheMods/All-the-mods-9-Sky#261]
### Possible Fixes

Yes

### Modpack Version

1.0.4

### What happened?

The cables of the refined storage mod stop working ramdonly in the server i am playing on. And the crafters, importers, etc. stop working because of the cable but the things connected directly to the controller have no problem

**Comment by oly2o6** [comment]
Just spoke with a few different people and they did not seem to have this issue, have you tried breaking and replacing anything to see if its working?

**Comment by Daminin11** [comment]
> Just spoke with a few different people and they did not seem to have this issue, have you tried breaking and replacing anything to see if its working?

It does but a few moments later it do another time the bug

**Comment by TheAwesomeRat93** [comment]
This happened to me right after updating to 1.0.4
The secondary crafting grid and the drawer controller don't seem to be conected to the main grid anymore.

I did a roll back to 1.0.3 and everything started working again.

**Comment by Daminin11** [comment]
> This happened to me right after updating to 1.0.4
> The secondary crafting grid and the drawer controller don't seem to be conected to the main grid anymore.
> 
> I did a roll back to 1.0.3 and everything started working again.

I solved it by breaking the cable conected to the controller and putting it back again
And if you conect fartest machines by putting a network reciber in the fartest machines it works i dont know why
