### ISSUE TITLE
[Bug] still can't craft osmium ore using flux compactor

### ISSUE THREAD

**Issue by alexzhaozzh** [AllTheMods/All-the-mods-9-Sky#263]
### Possible Fixes

Yes

### Modpack Version

1.0.3

### What happened?

still can't craft osmium ore using flux compactor
<img width="481" alt="1718374492824" src="https://github.com/AllTheMods/All-the-mods-9-Sky/assets/98642083/eeec9528-848f-483e-9d0f-721d027fd733">

**Comment by new-3** [comment]
Would you update your game to 1.0.4?
