### ISSUE TITLE
[Bug]: Farmland Trampling

### ISSUE THREAD

**Issue by krazzykid2006** [AllTheMods/All-the-mods-9-Sky#264]
### Possible Fixes

Yes

### Modpack Version

1.0.4

### What happened?

I am now on 1.0.4 and still don't have or see the "No Trample" mod that was supposed to be added in 1.0.3
Did you remove it again in 1.0.4 and forget to list it in the patch notes?

From the 1.0.3 patch notes,
"Additions:
No Trample"

I have no such mod called "No Trample" or any mods with the name trample at all.
Farmland is still getting trampled as well, so it isn't working either.

**Comment by krazzykid2006** [comment]
Yes, I can add my own mod to fix this.
That doesn't change the fact that the 1.0.3 patch notes claim it was added and it appears it either wasn't ever added or it was later removed in 1.0.4 and not listed.

**Comment by billbertking1** [comment]
Oops, will actually add it in .5
