### ISSUE TITLE
Crafting Silicon

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#265]
### Possible Fixes

Yes

### Modpack Version

1.0.4

### What happened?

Why is Refined Storage Silicon the only thing craftable with Silicon Essence, whose idea was that? I would remove Refined Storage's and EnderIO's silicon and replace it with Applied Energistic's silicon like in ATM9.
![2024-06-15_08 07 56](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/662ca9d0-fd07-4031-bdbb-35b4cd7a5701)

**Comment by oly2o6** [comment]
Remarking as an enhancement as they are tagged and all work with each other anyway

**Comment by TheLastPaladin** [comment]
Please consider including EnderIO's silicon as well. It supports the 'forge:silicon' tag as well. In addition to that mekanisms oredictionaryficator cannot subsitute materials of that tag.
