### ISSUE TITLE
[Bug]: Phytogenic Creating Seeds

### ISSUE THREAD

**Issue by MinecartCopper** [AllTheMods/All-the-mods-9-Sky#273]
### Possible Fixes

Yes

### Modpack Version

1.0.3

### What happened?

Setup a few dirt Phytogenic machines, tossed some dirt seeds in and boosted them to max. I am getting dirt seeds produced along with dirt essence. Started with 16 seeds... after an hour or so, have about 4 stacks now. JEI says chance of seeds is 0%.

**Comment by AdimoUK** [comment]
Duplicate of #237.

Was confirmed this is part of MA and T1 - T4 seeds  have a 1% chance of dropping an extra seed. This is just a display issue.

**Comment by MinecartCopper** [comment]
> Duplicate of #237.
> 
> Was confirmed this is part of MA and T1 - T4 seeds have a 1% chance of dropping an extra seed. This is just a display issue.

I guess when I "searched" I just looked for open issues... so when you say 'display issue' you mean it doesn't display that there is a chance to drop a seed?

**Comment by AdimoUK** [comment]
Yes, the 0% chance in JEI is the bug, but display only. The seeds do still drop.
