### ISSUE TITLE
[Crash]: Crash while placing block, restarted and AE2 system was offline.

### ISSUE THREAD

**Issue by Bodadis** [AllTheMods/All-the-mods-9-Sky#275]
### Possible Fixes

Yes

### Modpack Version

1.0.4

### What happened?

I was building, had just changed the blocks from Light Gray Blocks to Framed Panels and I was gonna place some lattices on the side of the building (where I have Macaw's Windows) and it crashed. Went I restarted my whole AE2 system was offline and I have done no changes.

### Crash Log

https://gist.github.com/Bodadis/2e6e6c424b4ce5e5dfa95b232c209eac

**Comment by oly2o6** [comment]
Cant replicate
