### ISSUE TITLE
[Bug]: Constant UDP pinging while no players are connected to the server

### ISSUE THREAD

**Issue by mouro001** [AllTheMods/All-the-mods-9-Sky#283]
### Possible Fixes

Yes

### Modpack Version

1.0.4

### What happened?

I got a server for TTS running on pterodactyl, and I noticed something weird going in the network when there are no players connected:
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/8522686/6813939d-318d-4e1a-86c9-c33cc917c2e9)

I checked a bit deeper and seems like there's an UDP packet going through every 1 or 2 seconds that could be "advertising" the status of the server. 
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/8522686/85a13e75-9315-4291-a049-4b741394a312)

is this known? what mod would be doing this?
it doesn't happen on other modpacks.

### latest.log

https://gist.github.com/mouro001/00eb5afc9a231e06cc9a7e8903ecde51

**Comment by mouro001** [comment]
I searched for the IP "ff75:230::60" and seems like its a mod that is announcing the server on the local network. Something like this mod: https://modrinth.com/mod/lan-announcer 
This mod however was made for Fabric, so there's a different mod doing this

**Comment by Mitchell5200** [comment]
What program are you using to capture these packets, just so i can do my own investigation with some local server instances (splitting the modlist until i get to the mod causing this)

**Comment by mouro001** [comment]
> What program are you using to capture these packets, just so i can do my own investigation with some local server instances (splitting the modlist until i get to the mod causing this)

That was Wireshark. I setup a server in a sandbox and the messages start when the server is ready.

**Comment by mouro001** [comment]
from @Mitchell5200 in [discord](https://discord.com/channels/254530689225981953/1245715508381093982/1252278889590427649)
> we might have a cause id'd, can you locate the `forge-server.toml` file in `/world/serverconfig/`, and there's a setting to advertise servers to LAN, toggle that off [...]

can confirm this has solved the issue.
if someone else runs into this, remember to shutdown the server, edit the file and start the server again.
