### ISSUE TITLE
[Bug]: Lag while using simple AE2 system

### ISSUE THREAD

**Issue by cloud1661** [AllTheMods/All-the-mods-9-Sky#291]
### Possible Fixes

Yes

### Modpack Version

1.0.4

### What happened?

While playing in a LAN world, experienced FPS drops while one of us was using the AE2 System.  AE2 system currently just consists of a drive bay, and a crafting terminal. A few seconds after we stopped using AE2 System to access inventory or Crafting terminal crafting, FPS picked back up.

Not an expert or anything, but the error log seems to be getting spammed with: Render thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: No value present

Possible contributor to lag experienced while using AE2 System?

Other factor:
Replaced Supplmentieies Mod file, with latest from curseforge to fix LAN playing issue, not sure if related.

Please let me know if you need any other additional information.  Thanks!

### latest.log

https://gist.github.com/cloud1661/b30647053af1d37f0c5dcc62553dacf3

**Comment by oly2o6** [comment]
Should be fixed
