### ISSUE TITLE
[Bug]: Missing ability to get axolotl

### ISSUE THREAD

**Issue by Nox-iv** [AllTheMods/All-the-mods-9-Sky#295]
### Possible Fixes

Yes

### Modpack Version

1.0.4

### What happened?

From what I can see there is no possible way to get an axolotl. Wandering traders do not have the trade for the bucket of axolotl.

The axolotle is needed to summon the possessed warden which can drop the music disc needed for wannabees.

**Comment by DeeJayhX** [comment]
Can confirm.

- Cannot get lush cave biome to spawn axolotl naturally
- Bucket of axolotl does not spawn on wandering trader
- Cannot force spawn axolotl with clay and animal summoning ritual in other biomes
- No summon altar recipe for axolotl
- No possessed ritual for axolotl

This prevents harvesting from the possessed warden. While not progress-breaking, it does mean the only other early-mid alternative to echo shards is sieving crushed end stone, or mid bees.

**Comment by Surfytom** [comment]
Bump. Also facing this issue (built two what i think are valid farms for them with no spawns).

**Comment by lordlethis** [comment]
Botania's Cocoon of Caprice can spawn axolotls when submerged in water. It's a rare result, though, so you might need a few dozen attempts.

**Comment by Surfytom** [comment]
After trying about 40 cocoon of caprices i can confirm axolotl's spawn from it if submerged like @lordlethis said.

**Comment by ReikoAldrakar** [comment]
You can force the cocoon to spawn a rare mob, if in water that is dolphin, glowing squid or axolotl
If only I knew this sooner...
