### ISSUE TITLE
[Bug]: When placing items, they get placed at random locations around the claim

### ISSUE THREAD

**Issue by BeastyCloak** [AllTheMods/All-the-mods-9-Sky#297]
### Possible Fixes

Yes

### Modpack Version

1.0.4

### What happened?

When I place blocks on the patreon server, they are displaced in the world south west and about 30 y levels lower.

It is happening more consistently after making the SPS and getting my first anti-matter. Don't know if it has anything to do with it, but it didn't occur prior to building the SPS. I have previously seen it on Volcano block and same issue after making the SPS. I don't know if it is the reactor or the SPS itself that's correlative.

Placed a fluid importer on the sink:

![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/104786983/15b5b2ff-a293-4a57-8398-3ef66f346ca8)

LIving its best life in the void.

![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/104786983/8ce75ac7-b9cd-4bd7-b8b0-78d65801b45d)

**Comment by BeastyCloak** [comment]
I just noticed it does this 100% of the time when shift-placing an item but infrequently when placing with out shift.

**Comment by oly2o6** [comment]
Shrink? message me about this if its still happening
