### ISSUE TITLE
[Bug]: Mob health

### ISSUE THREAD

**Issue by Licflagg** [AllTheMods/All-the-mods-9-Sky#298]
### Possible Fixes

Yes

### Modpack Version

1.0.4

### What happened?

When using a Draconic Evolution Mob Grinder, sometimes mobs have their health and absorption values set to NaN, and become unkillable. They can still move around and even hurt, but their animations are frozen. They can still despawn like normal.

A video/gif of the mobs in a spawner:

https://github.com/AllTheMods/All-the-mods-9-Sky/assets/11251795/060ab47f-c89c-464a-9e40-b59a3e35fc0a

Here's the data from that one skeleton: 
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/11251795/1d718217-3c7e-401b-8562-0ba9b481b43d)

Note: The log was pruned down to when I loaded into the world (singleplayer)

### latest.log

https://gist.github.com/Licflagg/f079ccccda4e113f381ea85de06b8e72

**Comment by oly2o6** [comment]
Please report to the mod authors.
