### ISSUE TITLE
[Bug]: Translocator Crafting grid not working as expected

### ISSUE THREAD

**Issue by DiggityMan420** [AllTheMods/All-the-mods-9-Sky#299]
### Possible Fixes

Yes

### Modpack Version

1.0.4

### What happened?

I have the key set to a key bind not used by anything else cant not place items in grid see pics no error in log just not placing a item I was trying a simple wooden shovel no luck I don't know if its your end or mod end
![2024-06-16_19 57 29](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/45196448/9bbde122-26a1-41cb-a7bc-6221ab522ed2)
![2024-06-16_19 57 38](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/45196448/4766c995-fcc6-4e51-ab96-f10122761185)

**Comment by oly2o6** [comment]
Mod bug, not a pack bug
