### ISSUE TITLE
[Quests issues]: Uranium Oxide in Mekanism: Advanced not working 

### ISSUE THREAD

**Issue by LezeyQ** [AllTheMods/All-the-mods-9-Sky#301]
### Modpack Version

1.0.4

### Describe the issue

When trying to complete the Uranium Oxide quest, one part of the quest can not be complete. On part of the quest says to observe Uranium Oxide inside of a Machine. But when looking at it in every possible gui it doesn’t register.

**Comment by oly2o6** [comment]
closing in favour of the other issue
