### ISSUE TITLE
[Bug]: Recipe for Mekanism Infused Alloy isnt working properly

### ISSUE THREAD

**Issue by Kaioss32** [AllTheMods/All-the-mods-9-Sky#303]
### Possible Fixes

Yes

### Modpack Version

1.0.4

### What happened?

I cant craft the "Infused Alloy" from the Mekanism mod. When i try to put redstone and iron into the "Metallurgic Infuser" or the "Infusing Factories" nothing happens. I tried to craft the "Basic Controll Circuit" and it worked just fine.

**Comment by lobo235** [comment]
This is happening in 1.0.5 for me as well.

**Comment by lobo235** [comment]
When this happens a server reboot seems to fix the issue. It happens intermittently.

**Comment by oly2o6** [comment]
Cant repo, but also restarting fixes it so closing
