### ISSUE TITLE
[Bug]: ATM star shards don't have a recipe to make stars

### ISSUE THREAD

**Issue by Seear1** [AllTheMods/All-the-mods-9-Sky#305]
### Possible Fixes

Yes

### Modpack Version

1.0.4

### What happened?

![Screenshot_324](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/38769578/a4c09114-693f-4812-b5e8-de839b1033c2)

**Comment by Seear1** [comment]
![Screenshot_325](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/38769578/4f3d83cb-aff1-436d-b1c5-9bd5712ed4fb)

**Comment by Pyario** [comment]
There is a Recipe..  The 3 Option you must click on!
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/44146318/67573092-7e79-4be5-a44a-504b0db80b45)

**Comment by Seear1** [comment]
I know. I have made all 18 to get the ATM star bee and block to feed it. It makes ATM star shards that cannot be crafted into stars like in ATM9 with 54 shards and 1 Patrick bee.

**Comment by TheBedrockMaster** [comment]
> There is a recipe, you just have to select the 3rd this "altar"! ![image](https://private-user-images.githubusercontent.com/44146318/340460904-67573092-7e79-4be5-a44a-504b0db80b45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4ODE5MjIsIm5iZiI6MTcxODg4MTYyMiwicGF0aCI6Ii80NDE0NjMxOC8zNDA0NjA5MDQtNjc1NzMwOTItN2U3OS00YmU1LWE0NGEtNTA0YjBkYjgwYjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDExMDcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmODYxN2EyNjA0MjRkNGRkMWM4ZDk1YzVjMDJkZDVlMzc5OWMwMmU0Nzc5ZDVhNWZhOTExMmFiYzc1MTc4NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u9fLz02nnBjQdrs532qAdDameKDDysaIeJ90iLQFd7Q)

The title even says shards

**Comment by joeychin01** [comment]
Still open, no shard recipe as of yet

**Comment by TheBedrockMaster** [comment]
I believe this is now implemented.

**Comment by joeychin01** [comment]
Yes it has!
