### ISSUE TITLE
[Bug]: Spacial Anchor from AE2 has no recipe

### ISSUE THREAD

**Issue by ajdjyt** [AllTheMods/All-the-mods-9-Sky#308]
### Possible Fixes

Yes

### Modpack Version

1.0.4

### What happened?

Cant craft the spacial anchor from AE2 as it has no recipe, which prevents you from 100%ing the AE2 questline, 
The AE2 guide shows an error
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/26516505/1f2a3b42-9c69-419b-a7fd-e105771aa23f)

### latest.log

https://gist.github.com/ajdjyt/7e22ce7cb3091cacd93aff00d02a5e01

**Comment by billbertking1** [comment]
Disabled intentionally as it is used to bypass FTBChunks chunkloading, which isn't a good thing.

**Comment by ajdjyt** [comment]
Its still in the AE2 Questline, maybe replace it with a checkbox saying that its disabled and to use FTBChunks instead.

**Comment by billbertking1** [comment]
The AE questline is in the process of getting redone completely so it won't be an issue much longer

**Comment by ajdjyt** [comment]
Alright, closing the issue then
