### ISSUE TITLE
Indents and quest text being slightly off.

### ISSUE THREAD

**Issue by 5ully** [AllTheMods/All-the-mods-9-Sky#31]
This is all minor stuff, but looks a bit off so Ill compile a list of the quests ive found so far where the text looks a bit weird. This weirdness includes the Indent that is on some quest pages but not all, so if this is intended just skip those. For me at least the indent looks a bit out of place.

After looking at this the indent might be a problem with any quest with more than 1 paragraph so might be a FTB Quests issue, or not? Looked through even more quests and found that its not all quests but a lot of multi paragraph quests.

The "To the End! quest text is wider than the quest box boundary, leading it to be cut off on the edges. Looks like its not related to GUI scale from a bit of quick testing.
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/9050688/ca09f067-8cac-41be-bfe3-c667ed0c956a)

Gold upgrade quest text looks like it has been recently edited since the sentence doesn't start with an uppercase letter.

**Comment by ToshibaEC0Microwave** [comment]
1. The indent isn't necessary it was just what happens when you do line spacing with the json file. If it's annoying to people I can go and fix it but it's not high on the list. 
2. Don't worry the end quest is being fixed just needed bigger window space. 
3. It'll be capitalized next update.
