### ISSUE TITLE
[Bug]: Modular Router Camouflage Upgrade 

### ISSUE THREAD

**Issue by Rah-creator** [AllTheMods/All-the-mods-9-Sky#315]
### Possible Fixes

Yes

### Modpack Version

1.0.4

### What happened?

Used the Camouflage Upgrade to copy an annihilation plane , which caused the router to become invisible and not interactable. I also cannot break the router or place another block in that same spot.  If i Fly through the  space in which the router is i pass through however take suffocation damage on the way through 
https://imgur.com/VR25iMw

**Comment by oly2o6** [comment]
mod issue

**Comment by EnderAki** [comment]
place a router next to it and veinmine it but the router got bugged cant be reuse again

**Comment by amauriastronomico** [comment]
I used a router to break the bugged one, then a put on the ground and right-clicked really fast (because would bug again) and take off the camuuflage upgrade, and its useble again
