### ISSUE TITLE
[Bug]: Twerking bypasses the need for a crux under MA Nether Star or Dragon Egg seeds

### ISSUE THREAD

**Issue by AdimoUK** [AllTheMods/All-the-mods-9-Sky#317]
### Possible Fixes

Yes

### Modpack Version

1.0.4

### What happened?

When twerking (spamming shift), the Dragon Egg Seeds or Nether Star Seeds grow, even without a crux underneath. Very similar to #195 report, except still working with current mods in the pack.

**Comment by oly2o6** [comment]
Not super concerned with this, by that point you should have a phyto so you can still do it without the crux, and automated

**Comment by oly2o6** [comment]
Mainly a wont fix as we would have to turn it off for MA completely
