### ISSUE TITLE
[Bug]: ITEM: [MEGA Bulk Item Storage Cell] tanks FPS if visible in inventory or toolbar.

### ISSUE THREAD

**Issue by Kamiijes** [AllTheMods/All-the-mods-9-Sky#319]
### Possible Fixes

Yes

### Modpack Version

1.0.4

### What happened?

There is a performance issue with the item [MEGA Bulk Item Storage Cell].
Just having the item in my inventory or visible on my toolbar tanks my FPS.

**Extra info:**
Removing all my textures packs mitigates the issue, the fps still tanks by 50% but it has less of an impact.
Shader on/off doesn't make a difference.
No extra mods added.
Restarted PC / Allocated more RAM / Tried different Graphics settings - No noticeable difference.

**Proof:**
https://i.imgur.com/XtRxqzO.jpeg - The item not on toolbar - 144 fps
https://i.imgur.com/LLsXprb.jpeg - The item on toolbar - 70 fps
https://i.imgur.com/xzfPWNm.jpeg - The item on toolbar + the item in hand - 56 fps
https://i.imgur.com/o5wDTSs.png - Inventory filled with the item and inventory opened - 15 fps
https://i.imgur.com/Ep0PK0v.jpeg - Random items in inventory and inventory opened - 144 fps

**Specs:**
**CPU:** AMD Ryzen 7 5800x3D
**GPU:** NVIDIA GeForce RTX 3080 Ti
**RAM:** 32GB 3200Mhz (20Gb allocated to minecraft)

### Developer reports

https://github.com/62832/MEGACells

**Comment by oly2o6** [comment]
Cant repo
