### ISSUE TITLE
[Quests issues]: Alchemistry questline missing.

### ISSUE THREAD

**Issue by hnagd1** [AllTheMods/All-the-mods-9-Sky#320]
### Modpack Version

1.0.5

### Describe the issue

Although in the [curseforge](https://www.curseforge.com/minecraft/modpacks/all-the-mods-9-to-the-sky/files/5442876) it says that an alchemistry questline was added, there seems to be no such questline in the pack.

Edit: Nevermind. I guess it was removed.

**Comment by TheBedrockMaster** [comment]
👀
