### ISSUE TITLE
[Bug]: Possessed Elder Guardian Ritual not initiating

### ISSUE THREAD

**Issue by tiniestfeet** [AllTheMods/All-the-mods-9-Sky#321]
### Possible Fixes

Yes

### Modpack Version

1.0.5

### What happened?

Trying to start elder guardian ritual, have the correct circle, have the correct ingredients, won't let me place book to initiate.
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/131112012/3bb6bdfd-8a71-4b0e-8511-938fce245589)

**Comment by DevilMayCryIfrit** [comment]
I'm looking at your picture and I don't see the dark primaries. Did you place it?
