### ISSUE TITLE
"Complete Chapter 2" Quest Title

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#330]
### Modpack Version

1.0.5

### Describe the issue

The highlighted part only goes through some of it. 🤔
![2024-06-19_20 57 10](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/7f3f3a6f-0309-4a32-b2be-2cdcf6f8624e)

**Comment by oly2o6** [comment]
Im not actually sure how to fix this one, ill ask an expert and come back to it :D

**Comment by TheBedrockMaster** [comment]
Seems to have fixed itself after relogging twice 🤔
