### ISSUE TITLE
[Quests issues]: A lot of quests/chapters have broken text

### ISSUE THREAD

**Issue by Ugnasijus** [AllTheMods/All-the-mods-9-Sky#332]
### Modpack Version

1.0.5

### Describe the issue

![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/102345753/bc2a61bc-6e1a-4bf8-9ef0-5f09e97fe8aa)
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/102345753/194f47b4-bfc1-482d-9c37-264a5af0f43b)
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/102345753/b0c7c14e-2c11-41f0-aef2-b5fb4d53d4fb)
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/102345753/7d80591a-2ab3-4ecd-b600-ce8b9d83cfe8)
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/102345753/c8be345e-2141-4a22-af09-6520f37bb51b)
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/102345753/869c5e86-6bf8-48d3-81cb-2ffb816d213b)

**Comment by oly2o6** [comment]
Can you try a fresh install? I cannot reproduce these errors
