### ISSUE TITLE
[Crash]: After updating to 1.0.5 crash after a while

### ISSUE THREAD

**Issue by Glich440** [AllTheMods/All-the-mods-9-Sky#333]
### Possible Fixes

Yes

### Modpack Version

1.0.5

### What happened?

After a while playing in the new update to fix a crash I was getting previously the install completely bricks, but no data is lost. The world is saved, the game exits and refuses to launch again

### Crash Log

https://gist.github.com/Glich440/ee88e5ff78545dfff2d8a345a3e03091

### Latest.Log

https://gist.github.com/Glich440/cae344eb7ad9412ce213792e633ea90c

**Comment by oly2o6** [comment]
Can you try a fresh install?
