### ISSUE TITLE
[Suggestion] EMC Interface

### ISSUE THREAD

**Issue by brainshead** [AllTheMods/All-the-mods-9-Sky#336]
To give both virtual storage systems connection to EMC instead only AE2 

This is an addon to ProjectE
It adds a single block: EMC Interface

You can connect it to many virtual storage mods such as Refined Storage or AE2.
Once connected, you can put and take items using EMC directly from your virtual storage.

 

If you are using Refined Storage:
Put an External Storage on the EMC Interface in order to connect it.

If you are using AE2:
Put an ME Storage Bus on the EMC Interface in order to connect it.

note that you can connect it to other mods as well
[https://www.curseforge.com/minecraft/mc-mods/emc-interface](url)

**Comment by oly2o6** [comment]
I dont believe this works with our current addon set
