### ISSUE TITLE
No Recipe for Awakened Draconium Dust  [Bug]: 

### ISSUE THREAD

**Issue by Remains808** [AllTheMods/All-the-mods-9-Sky#338]
### Possible Fixes

Yes

### Modpack Version

1.0.5

### What happened?

Just no current way to get the Awakened Draconium Dust yet it is called for in the recipies to craft the Awakened Draconium and Chaotic bee spawn eggs

**Comment by charlesgael** [comment]
Made a PR about this, using crusher.
OFC all details cost and process time are to define by modpack makers
https://github.com/AllTheMods/All-the-mods-9-Sky/pull/358
