### ISSUE TITLE
[Quests issues]: All custom "Observe" quests can not be completed

### ISSUE THREAD

**Issue by MrSelenix** [AllTheMods/All-the-mods-9-Sky#341]
### Modpack Version

1.0.4 - 1.0.5

### Describe the issue

All quests - that ive tested so far - that use the custom "Observe {XYZ}" tasks are unable to be completed.
Thus far, ive tested; 
**Observe Uranium Oxide in a machine [Uranium Oxide]** _[3AF4E5D4839CEF8B]_
**Observe a Completed induction Matrix [Completing the matrix]** _[07ECC87DFF2D3991]_
**Observe a completed SPS [Build the SPS!]** _[2B3F2F470E06BC40]_.

While ive not tried yet, i imagine this would also extend to the turbine, fusion reactor, and anything else that requires an "observe" task.

Currently ive only noticed these types of tasks in **[Mekanism: Advanced]**, but if there are more elsewhere, they may too be broken tasks.

_This Issue expands on issues #201 and #301_

**Comment by EndDragon438** [comment]
I'll second this, tried different methods a few times, got the right particles, no completion.
ended up just going into editor mode and making it a checkmark.

**Comment by Manbeartooth** [comment]
Just curious why these type of quests are even in the pack as they almost never work properly due to some other addon or issue, why not make it be something like, fill up and tank with the gas and hold it in the inventory or something along those lines, that way you don't have to worry about setting something up exactly as needed to work?

**Comment by Catta1997** [comment]
Any news?

**Comment by TheBedrockMaster** [comment]
Why don't you make the quests then?

> Just curious why these type of quests are even in the pack as they almost never work properly due to some other addon or issue, why not make it be something like, fill up and tank with the gas and hold it in the inventory or something along those lines, that way you don't have to worry about setting something up exactly as needed to work?

**Comment by Manbeartooth** [comment]
> Why don't you make the quests then?
> 
> > Just curious why these type of quests are even in the pack as they almost never work properly due to some other addon or issue, why not make it be something like, fill up and tank with the gas and hold it in the inventory or something along those lines, that way you don't have to worry about setting something up exactly as needed to work?

Really? its called a suggestion, perhaps you have heard of them?
I have seen these type of "observe" quests many times in the past and most of the time they don't work as opposed to a turn in quest
I honestly love the pack and am very grateful for all the hard work you guys do to bring these packs together.  I had just wanted to ask why those type of quests are used when they seem to be pretty unreliable to get working and then made a suggestion of something else that could be done instead.

I didn't make the comment to offend anyone, so please no need to be snarky.

**Comment by TheBedrockMaster** [comment]
> > Why don't you make the quests then?
> > > Just curious why these type of quests are even in the pack as they almost never work properly due to some other addon or issue, why not make it be something like, fill up and tank with the gas and hold it in the inventory or something along those lines, that way you don't have to worry about setting something up exactly as needed to work?
> 
> Really? its called a suggestion, perhaps you have heard of them? I have seen these type of "observe" quests many times in the past and most of the time they don't work as opposed to a turn in quest I honestly love the pack and am very grateful for all the hard work you guys do to bring these packs together. I had just wanted to ask why those type of quests are used when they seem to be pretty unreliable to get working and then made a suggestion of something else that could be done instead.
> 
> I didn't make the comment to offend anyone, so please no need to be snarky.

I'm so sorry, I really thought you were someone else... (last unneeded GitHub message ever right now).

**Comment by asottile** [comment]
@ToshibaEC0Microwave thanks for fixing (most) of these!  it looks like "Observe a Completed Induction Matrix" is still present in 1.0.8a in "Advanced Mekanism"

**Comment by JakeMoe** [comment]
I've just finished making an induction matrix so I can complete the Mek Advanced chapter.  Already had a T8 Draconic ball, so didn't really need it, just put it together to fulfill this quest.  But it seems the quest is still broken?  I can't get it to complete, despite my matrix taking in and supplying RF.

**Comment by gatekeeper258** [comment]
atm9 0.3.2 cant complete observe a completed reactor, got the red particles but cant complete

**Comment by beadily10** [comment]
> atm9 0.3.2 cant complete observe a completed reactor, got the red particles but cant complete

same thing happening to me

**Comment by laurad2423** [comment]
All of the "observe" quests are not working for me. The workaround has been using the edit tool in the bottom right, then right click the quest, and click "complete Instantly"
![image](https://github.com/user-attachments/assets/1a74bdc8-0e5c-4429-9b86-0543ec22e771)
![image](https://github.com/user-attachments/assets/fe0cbd4a-e9ce-4400-bc62-c10c4aa80b5d)

**Comment by dsf3449** [comment]
+1 the observe quests are broken

**Comment by WTFRichard** [comment]
The "The Fission Reactor Interface" quest is broken for me right now as well. Have tried a couple different configurations, which all complete and allow me to interact with the interface, but none of them have popped the completed quest. Was really looking forward to working through the advanced section quest tab. :/

**Comment by DisruptionSystemsINC** [comment]
+1 Still broken

**Comment by Greenskulllord** [comment]
still broken. made the reactor, quest isnt completing

**Comment by Wazbat** [comment]
I'm also having this issue. What version or commit was this fixed with?
