### ISSUE TITLE
[Bug]: refined storage bug

### ISSUE THREAD

**Issue by DevilMayCryIfrit** [AllTheMods/All-the-mods-9-Sky#344]
### Possible Fixes

Yes

### Modpack Version

1.0.5

### What happened?

When you have refined storage crafter set up to mek enricher with enriched items such as enriched Redstone and enriched diamonds. You take out the storage disk and put it back it sets off a auto craft. I have not tried it in a new world so I don't know if it is repeatable.

**Comment by oly2o6** [comment]
I cant replicate this,
