### ISSUE TITLE
Piglich Spawn Egg in JEI

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#345]
### Possible Fixes

Yes

### Modpack Version

1.0.5

### What happened?

The Piglich spawn egg in JEI has a broken texture and name... and it's there.
![2024-06-20_17 40 41](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/ded75179-5e1d-410d-b72f-7d5df19482a5)

**Comment by oly2o6** [comment]
Reported to vortex
