### ISSUE TITLE
Quest category names are misaligned when the language is set to Japanese

### ISSUE THREAD

**Issue by Abbage230** [AllTheMods/All-the-mods-9-Sky#36]
This phenomenon might also occur in other translated languages (unverified).
![2024-05-31_15 05 34](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/153836307/5179a44a-39d7-4203-9fcf-3cadc5472a8f)

The Japanese translation file is taken directly from ATM9, and there are many TTS-specific quests that have not been translated. Therefore, the solution is to update the translation or remove it from the TTS.

**Comment by oly2o6** [comment]
Will be fixed when we merge in #107
