### ISSUE TITLE
[Bug]: immersive block of steel

### ISSUE THREAD

**Issue by lopadama** [AllTheMods/All-the-mods-9-Sky#367]
### Possible Fixes

Yes

### Modpack Version

1.0.5

### What happened?

some immersive engineering multiblock will not form with the steel block form: alltheores, and specificaly require the mod native "block of steel"
![2024-06-22_00 16 13](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/165173326/eba38ce7-d0fc-40c2-850e-8a0204f85a81)
here is the block of steel from immersive engineering
![2024-06-22_00 28 51](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/165173326/107a67e6-d5e5-4b35-aa0c-ce73db6ab619)
and here is the block of steel from alloftheores

no mater what the player do the multiblock will not form

**Comment by Mitchell5200** [comment]
Forms fine for me in base ATM9, but you're also missing a layer
![2024-06-22_10 08 35](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/45913837/78626c17-ee29-4dfd-8472-8386338ccb03)
![2024-06-22_10 08 40](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/45913837/45a9ba46-cfdd-4be8-bd73-aab99c892d30)
![2024-06-22_10 09 50](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/45913837/70e6acc8-4b70-4b20-a5e9-369a7e91157c)

**Comment by TheBedrockMaster** [comment]
Is it possible to change the image in the book to be ATO steel? Probably too much work anyway.
