### ISSUE TITLE
[Bug]: Max tier Flux Linkage Amp has low base power

### ISSUE THREAD

**Issue by UncannyBoi** [AllTheMods/All-the-mods-9-Sky#368]
### Possible Fixes

Yes

### Modpack Version

1.0.5

### What happened?

Twinite Flux Linkage Amplifier, which is an upgrade from Shellite Flux Linkage Amplifier has lower Base power. I do not know if this is intentional, but it seemed wrong for it to be slower. 

![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/82063038/468055c7-e274-4bec-82c3-e6e7043ddb5f)
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/82063038/e0894a7a-f0de-4970-8750-fca819a687e7)

**Comment by Koupius** [comment]
Not a bug. While the base power may seem lower, the process energy multiplier is what makes this worth it. The AlltheGuides page for Mystical Agriculture goes more into detail on why this ends up being faster than shellite.

**Comment by UncannyBoi** [comment]
> Not a bug. While the base power may seem lower, the process energy multiplier is what makes this worth it. The AlltheGuides page for Mystical Agriculture goes more into detail on why this ends up being faster than shellite.

Why would they reduce the base power by 10%? Why not have it stay at 120% but improve upon the energy multiplier instead?

**Comment by Koupius** [comment]
Base Power increases the amount of FE/t until it reaches the amount of energy required to complete the process. With Shellite, the energy requirement is raised to 22,000 FE and the consumption rate becomes 44FE/t. Twinite on the other hand raises to 20,200 FE at 42FE/t. Dividing these we come to Shellite at 500 ticks per operation vs Twinite at 480. With 20 ticks per second that comes to 25 vs 24 seconds per operation. The upgrade to Shellite from Enderium also shares this pattern of increasing processing time by 1 second.

**Comment by UncannyBoi** [comment]
> Base Power increases the amount of FE/t until it reaches the amount of energy required to complete the process. With Shellite, the energy requirement is raised to 22,000 FE and the consumption rate becomes 44FE/t. Twinite on the other hand raises to 20,200 FE at 42FE/t. Dividing these we come to Shellite at 500 ticks per operation vs Twinite at 480. With 20 ticks per second that comes to 25 vs 24 seconds per operation. The upgrade to Shellite from Enderium also shares this pattern of increasing processing time by 1 second. If the dev of Thermal Extra had kept it at 120% at 1.01x the process speed would come to 22 seconds which would break the pattern of 1 second saved per upgrade.
> 
> Edit: For reference, the machine I am basing these around would be for the Phytogenic Insolator which has a base processing requirement of 20000 and operates at 20FE/t.

Now that makes sense.. Its just a very efficient upgrade, needing less FE requirement for about the same processing power per tick as you've mentioned. I had no idea it had that.

**Comment by 9Valjew** [comment]
Although closed I will state:
now that thermal endergy is in the pack, there is a way faster flux linkage amplifier
