### ISSUE TITLE
[Quests issues]: DRACONIUM QUESTS

### ISSUE THREAD

**Issue by KzKush** [AllTheMods/All-the-mods-9-Sky#369]
### Modpack Version

ATM9 TO THE SKY

### Describe the issue

WHEN WILL YOU ADD QUESTS DRACONIUM?

**Comment by TheBedrockMaster** [comment]
Soon, this isn't a bug, they're being worked on.

**Comment by KnotRex** [comment]
Soon because draconic evolution is a complicated mod
