### ISSUE TITLE
Bigger Reactors Moderators

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#370]
### Possible Fixes

Yes

### Modpack Version

1.0.5

### What happened?

The Bigger Reactors moderators need to be changed to not include blocks that aren't obtainable in the game.
![2024-06-22_08 37 58](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/3008c2ee-9e42-497e-890d-cf0b13d783fc)
![2024-06-22_08 38 08](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/950f5942-cb4d-473b-8e27-127c03ba39f2)
![2024-06-22_08 38 19](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/2781e7de-37ae-4448-b547-036b6c2ddf43)
![2024-06-22_08 38 29](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/42a8581d-c8d6-42c0-9311-80cb307ff009)
![2024-06-22_08 50 45](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/41069189-f270-4283-bcc1-a1bce8eb2016)
![2024-06-22_09 15 07](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/9d80ba86-2cf2-456c-9361-c9cce68a762a)

**Comment by oly2o6** [comment]
The mod just reports everything, as they are hidden but still present, I dont think this is fixable

**Comment by TheBedrockMaster** [comment]
I'll have a look into it, if I find a way I'll make a commit.
