### ISSUE TITLE
Block Heat Properties - Recipes not Needed

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#371]
### Possible Fixes

Yes

### Modpack Version

1.0.5

### What happened?

These recipes in JEI using PneumaticCraft aren't needed, there are probably more. These blocks/fluids aren't obtainable anyway.
![2024-06-22_09 25 20](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/2a0fc96b-f99c-451a-98db-07fbf1263cfd)
![2024-06-22_09 25 31](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/ae167dd8-4773-40ac-b56a-a7c3265a5cb4)
![2024-06-22_11 08 03](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/1c9f1ff1-3014-408f-a0d2-226ab76c099c)

**Comment by oly2o6** [comment]
Future jei cleanup
