### ISSUE TITLE
Soul Lava still in JEI

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#373]
### Possible Fixes

Yes

### Modpack Version

1.0.5

### What happened?

I believe Soul Lava is unobtainable in 9sky and yet it's still in JEI.
![2024-06-22_10 21 07](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/803080cb-3680-4eeb-b6cd-401fa50a0c5c)
![2024-06-22_10 21 17](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/1b561d90-56b2-4e0a-a372-256f7ffa44a4)
![2024-06-22_10 21 18](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/62bcc5ba-e72c-4a29-9939-7ebb9959a5dd)
![2024-06-22_10 21 28](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/88adfd91-4da9-4508-922a-3064ac18488a)
![2024-06-22_10 21 30](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/659694c6-8da3-4a94-ab57-58412a402104)

**Comment by oly2o6** [comment]
Alot of things are still in jei, not a bug but will most likely be cleaned up in the future once we have other bugs figured out
