### ISSUE TITLE
Liquid Obsidian is Unobtainable

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#374]
### Possible Fixes

Yes

### Modpack Version

1.0.5

### What happened?

Liquid Obsidian from Bigger Reactors is in JEI yet it isn't obtainable.
![2024-06-22_11 07 12](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/649b9e27-f20e-4537-89dc-10f6e3585551)
![2024-06-22_11 08 13](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/863d3fb0-1f6a-42d2-a1e2-31c47ac45e36)

**Comment by oly2o6** [comment]
Future jei cleanup

**Comment by TheBedrockMaster** [comment]
Made sure it wasn't in the spreadsheet. :)
