### ISSUE TITLE
[Crash]: Summoning Altar crash on Summoning Bee

### ISSUE THREAD

**Issue by Teck1015** [AllTheMods/All-the-mods-9-Sky#384]
### Possible Fixes

Yes

### Modpack Version

1.0.5

### What happened?

I was attempting to summon a regular vanilla Bee on the Summoning Altar. 

The process started then said I did not have the required reagents to complete the summon.

Of note: I was in a hyperbox when attempting to complete the summon. Additionally, the recipe calls for 1 piece of grass (not the grass block the grass item) and I had accidentally input 4 grass items into the summoning altar.

The subsequent crash was an ArrayIndexOutofBounds exception pointing to the Summoning Alater

### Crash Log

https://gist.github.com/Teck1015/0a5c0b1fc0f1f4295f65e196a3871108

**Comment by xmaniaxz** [comment]
I can recreate this with a squid. but i did have all the correct items
[debug.log](https://github.com/user-attachments/files/15994280/debug.log)
[latest.log](https://github.com/user-attachments/files/15994282/latest.log)
