### ISSUE TITLE
[Bug]: Cant craft awakened draconium dust

### ISSUE THREAD

**Issue by sheet315** [AllTheMods/All-the-mods-9-Sky#385]
### Possible Fixes

Yes

### Modpack Version

1.0.5

### What happened?

There was no recipe to craft Awakened draconium dust for the Chaos Bee

### latest.log

i play on a server

### Developer reports

https://www.curseforge.com/minecraft/mc-mods/draconic-evolution

**Comment by Pandy420** [comment]
You can get awakened draconium via fusion crafting. It gives you Awakened draconium blocks.
