### ISSUE TITLE
[Suggestion] [QoL] Add Measuring Tape from Measurements Mod.

### ISSUE THREAD

**Issue by AdimoUK** [AllTheMods/All-the-mods-9-Sky#392]
For those of us who have OCD and need pixel perfect floating islands, I'm really missing out on the Tape Measure that used to be included in every pack with Chisel & Bits mods. Fortunately, there is a replacement: Measurements mod! https://modrinth.com/mod/measurements/version/EHwSQ3lX

It's small, non intrusive, will not require much work to implement but would be a great QoL addition!

**Comment by TheBedrockMaster** [comment]
Looks like it was added in 1.1.1.
