### ISSUE TITLE
[Quests issues]: 

### ISSUE THREAD

**Issue by Feeeeble** [AllTheMods/All-the-mods-9-Sky#394]
### Modpack Version

1.0.4

### Describe the issue

the entirety of the mekanism questline implies that the player uses the raw form of a metal (like raw iron) when after you craft the chunks you get the ore form (like iron ore), making the questline inconsistent with how the player may set it up (and yes, you can put all of the ores through the tier 4 ore factory no problem, giving more than if you made them raw)

**Comment by oly2o6** [comment]
Technically either works fine... adding to dev notes
