### ISSUE TITLE
Mekanism transportation unclear

### ISSUE THREAD

**Issue by Feeeeble** [AllTheMods/All-the-mods-9-Sky#395]
The pipes and machines from mekanism are a bit finicky to work with, so some clarity on it would be appreciated. Things like:

Introducing the pipes and configurator in the main questline and explaining them
     - ex. "While energy pipes are easy to use for everything, when using the other pipes with non-mekanism blocks, a configurator can be used to specify where the item/liquid/gas/etc is going by shift right clicking the end of the pipe"
Explaining how to properly filter the machines
     - ex. "On the sides of the filter menu, you can change whether you're filtering items, gasses, liquids, and others, make sure you configure the right tab"
Explain the correct pipe for uncertain materials (like slurrys (they're gas btw))
      - ex. "all liquids will have 'liquid' in the title, otherwise it's a gas"
How to connect the nuclear waste barrel
     - i'd provide an example but i still dont know how

**Comment by oly2o6** [comment]
Ill add this to our dev notes, closing here as its an enhancement
