### ISSUE TITLE
ATM9 Server Missing Mods

### ISSUE THREAD

**Issue by rreilly-edr** [AllTheMods/All-the-mods-9-Sky#40]
Installed the 1.0 version of both modpack and server files get a mod mismatch, server missing mods:
[https://justpaste.it/fq4vv](https://justpaste.it/fq4vv)
![atm9](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/31705381/c4873835-74cc-468d-93a0-e8cedb54cf0d)

**Comment by billbertking1** [comment]
Are you the host? Is it local or are you paying a host?
