### ISSUE TITLE
[Bug]: ATM9 -To The Sky Inventory Bug

### ISSUE THREAD

**Issue by MehmetCanWT** [AllTheMods/All-the-mods-9-Sky#406]
### Possible Fixes

No

### Modpack Version

1.0.5

### What happened?

![image](https://github.com/AllTheMods/ATM-9/assets/52177084/0fda14ce-5d90-421b-9aad-b8430716e205)
when i open crafting table inventory look like this my inventory is full but i only see the first row i cant open the second chest to its look empty but its not

### latest.log

https://gist.github.com/MehmetCanWT/eb177756efcc04d768c104fc24dabea0

**Comment by MehmetCanWT** [comment]
Is there any fix for this bug

**Comment by oly2o6** [comment]
Does this happen on a new world, have you tried moving the crafting station away from the chests?

**Comment by desagas** [comment]
ATM, come on, at least revert the update. This is not obscure, you added these updates to your packs which broke them, at least fix it, rather than simply ignoring it.

**Comment by sxweet** [comment]
Still going on in latest 1.0.10 update. 1.0.8a not have it unless you use chests.

**Comment by rannday** [comment]
Still happening in 1.1.0

**Comment by mikaba-eu** [comment]
Still a thing in 1.1.3
Its shows my playerinventory and its very buggy.

![Image](https://github.com/user-attachments/assets/ff66e9c8-9c5c-4854-9b55-95e7b1783288)
