### ISSUE TITLE
Unobtainable Ores in JEI

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#408]
### Possible Fixes

Yes

### Modpack Version

1.0.5

### What happened?

A lot of the ores from ATO are unobtainable in 9sky, yet they're still in JEI.
![2024-06-25_17 23 45](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/d7f23719-c932-485a-947d-0dcb8bbd1c8b)

**Comment by oly2o6** [comment]
Going to switch this over to enhancement as it isnt exactly a bug... but it is something I want to go over at some point
