### ISSUE TITLE
"It's Clippin' Time" Quest doesn't Accept Shears

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#409]
### Modpack Version

1.0.5

### Describe the issue

The Quest "It's Clippin' Time" in the "Food and Farming" Chapter only accepts Flint Shears and not regular Shears.
![2024-06-25_17 26 21](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/cfbcd761-b488-447a-a731-bbc50de10fdf)

**Comment by oly2o6** [comment]
Fixed in 1.0.6
