### ISSUE TITLE
[Bug]: Refined Storage issue with Functional storage and ore chunks

### ISSUE THREAD

**Issue by FuuNoKamiOka** [AllTheMods/All-the-mods-9-Sky#412]
### Possible Fixes

Yes

### Modpack Version

1.0.5

### What happened?

I have a drawer set up with refined storage and an external storage. I decided to see if I put an exporter on a drawer with a crafting card if it would autocraft the ore chunks from "Ex Deorum" and put the final ore in said drawer. It works...until I use the linking tool and connect the drawer with the completed ore to the other drawers on the RS System. Then it stops autocrafting. 

I have a video here of what I did and show how it's working before linking and not working after linking.
https://i.gyazo.com/735afa69c465fca4830fe1cf6cc13643.mp4

**Comment by oly2o6** [comment]
^ Also not a pack issue so im closing this

**Comment by FuuNoKamiOka** [comment]
I see your point but my problem got worse. Now the external storage bus isn't working at all with functional Storage. So I don't know what happened. *shrug*
