### ISSUE TITLE
[Quests issues]: industrial foregoing missions page loot reward is empty

### ISSUE THREAD

**Issue by lmn563** [AllTheMods/All-the-mods-9-Sky#413]
### Modpack Version

1.0.5

### Describe the issue

on the industrial foregoing missions page there are several (almost all from "advanced machine frame" onwards) missions with loot rewards that do not give anything when claimed

**Comment by FuuNoKamiOka** [comment]
I am also experiencing this. Meant to say something and kept forgetting.

**Comment by EndDragon438** [comment]
Same issue for me. Claim reward, pops up the tinted reward screen while not displaying an item, and I get nothing.
