### ISSUE TITLE
[Bug]: No recipe for Deuterium from Mekanism

### ISSUE THREAD

**Issue by thebilge** [AllTheMods/All-the-mods-9-Sky#419]
### Possible Fixes

Yes

### Modpack Version

1.0.5

### What happened?

There is a quest in the Mekanism Advanced section called "Fueling the Reactor: Deuterium". The quest explains the crafting process but the Electrolytic Separator recipe is missing to conver Heavy Water into Deuterium

**Comment by SalazarElite** [comment]
did you double checked your machine? here this bug does not exist..

![2024-06-26_15 36 02](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/19766906/ad0c1641-74f5-4412-9ca2-45825b753a09)
![2024-06-26_15 36 16](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/19766906/eb4e8277-bc24-46c5-8042-b1f709988890)

**Comment by Satherov** [comment]
all observation quests are currently bugged

**Comment by thebilge** [comment]
Then it must be a problem in my client, this is the only recipe I see
![deuterium](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/859913/cb154f58-049a-473d-aafa-ebad1da805e5)

**Comment by thebilge** [comment]
Repairing the profile fixed the issue. Thank you @SalazarElite
