### ISSUE TITLE
[Crash]: DraconicEvolution/BuildingGadets

### ISSUE THREAD

**Issue by bazsi248** [AllTheMods/All-the-mods-9-Sky#421]
### Possible Fixes

No

### Modpack Version

1.0.5

### What happened?

ATM9Sky 1.0.5 version

Describe the bug
Builder Gadget right clicking on a Chaos Crystal (The natural one, the Chaos Guardian is dead) from DraconicEvolution mod crashes the game instantly. The crash log says rendering bug, and can't login to the server, because of the instant crash.

Log Files
The game crashed whilst rendering block entity
Error: java.lang.IllegalStateException: Not filled all elements of the vertex

### Crash Log

https://gist.github.com/bazsi248/f02ea97a88f698ee75884587059c7679

**Comment by oly2o6** [comment]
Please report this to the mod authors
