### ISSUE TITLE
[Bug]: Plutonium pellet reciepe missing

### ISSUE THREAD

**Issue by bogeux** [AllTheMods/All-the-mods-9-Sky#425]
### Possible Fixes

Yes

### Modpack Version

1.0.6

### What happened?

The reciepe is simply missing now, not available in JEI and the PRC don't accept the fluorite dust anymore since 1.0.6.

No problem on the polonium one.

**Comment by Pandy420** [comment]
https://imgur.com/a/sbhe1dK
still there for me after updating to 1.0.6

**Comment by bogeux** [comment]
It might not be related to this exact update.

Aditionnaly this issue was also reported by other players in discord : https://discord.com/channels/254530689225981953/1245715508381093982/1255227114723086499 I don't think it's related to this exact update.

And some other reciepe seems to be "randomly" disapearing for other players on mekanism.

Maybe a bug happening after an update in some cases ?

**Comment by Hiltuska** [comment]
if ur on server. and u host it urself
take ur clients mekanism mod and replace the servers mod with it. worked for me.
otherwise redownload the modback. remeber to backup world

**Comment by bogeux** [comment]
> if ur on server. and u host it urself take ur clients mekanism mod and replace the servers mod with it. worked for me. otherwise redownload the modback. remeber to backup world

Restarted was enougth, also i'm not on server
