### ISSUE TITLE
[Crash]: cant start game

### ISSUE THREAD

**Issue by CookieKiller01** [AllTheMods/All-the-mods-9-Sky#428]
### Possible Fixes

Yes

### Modpack Version

1.0.6

### What happened?

after the update the game crashes with exit code 1 when starting. i already updated my graphics driver, and tried some solutions from reddit without any change.
i also don't get an crash log.

### Crash Log

-

### Latest.Log

https://gist.github.com/CookieKiller01/d91a19286b8c8eb920e18464ff4c2566

**Comment by Damalas75** [comment]
Also unable to start the game as it crashes using 7G Memory

-- Head --
Thread: Render thread
Suspected Mods: 
	Draconic Evolution (draconicevolution), Version: 3.1.2.575 at TRANSFORMER/draconicevolution@3.1.2.575/com.brandon3055.draconicevolution.client.render.tile.RenderTilePotentiometer.<init>(RenderTilePotentiometer.java:67)

	CodeChicken Lib (codechickenlib), Version: 4.4.0.512
		Issue tracker URL: https://github.com/TheCBProject/CodeChickenLib
		at TRANSFORMER/codechickenlib@4.4.0.512/codechicken.lib.render.model.ModelMaterial$1.copyRange(ModelMaterial.java:14)

**Comment by Intruderhere29** [comment]
> ### Possible Fixes
> Yes
> 
> ### Modpack Version
> 1.0.6
> 
> ### What happened?
> after the update the game crashes with exit code 1 when starting. i already updated my graphics driver, and tried some solutions from reddit without any change. i also don't get an crash log.
> 
> ### Crash Log
> 
> ### Latest.Log
> https://gist.github.com/CookieKiller01/d91a19286b8c8eb920e18464ff4c2566

same issue with me

**Comment by CookieKiller01** [comment]
it works like normal again. i just played other modpacks, and now it functions again
