### ISSUE TITLE
[Quests issues]: Sleep Charm should be in Tips and Tricks

### ISSUE THREAD

**Issue by adamvan2000** [AllTheMods/All-the-mods-9-Sky#432]
### Modpack Version

1.0.6

### Describe the issue

Despite being a relatively important early-game item, The sleep charm is not featured anywhere in the quests. The sleep charm should be included in the tips and tricks section, as in a skypack, phantoms are a major player concern depending on the island type players choose. It'd be nice to see the sleep charm included there, where new players can see and utilize it earlier.

**Comment by TheBedrockMaster** [comment]
This isn't a bug, it's more of an enhancement, but good idea.

**Comment by qerty2006** [comment]
I agree

**Comment by TheBedrockMaster** [comment]
I'll have a look in a minute.

**Comment by TheBedrockMaster** [comment]
There you go.

**Comment by adamvan2000** [comment]
Thanks!!
