### ISSUE TITLE
[Bug]: Kivi recipe missing from Igneous Extruder

### ISSUE THREAD

**Issue by NiSiSuinegEht** [AllTheMods/All-the-mods-9-Sky#435]
### Possible Fixes

Yes - Add recipe

### Modpack Version

1.0.5

### What happened?

The quest to create the Igneous Extruder on the Xycraft quest tab states to place the igneous extruder over obsidian with lava and water beside it to generate kivi.  This produces cobblestone instead.  Checking the recipes for igneous extruder output, there is no kivi listed.

**Comment by NiSiSuinegEht** [comment]
Works in single player, problem is in server files and not a pack issue

**Comment by basttrey** [comment]
Same problem even on single player!
Solution: I modified the mod file Thermal_foundation-1.20.1-11.0.6.70 and added the recipe.
I think there are more problems with the recipes, and the reason for this is that the kubejs scripts are not working properly.

Attached edit file:
[thermal_foundation-1.20.1-11.0.6.70akr.jar.zip](https://github.com/user-attachments/files/16167655/thermal_foundation-1.20.1-11.0.6.70akr.jar.zip)
