### ISSUE TITLE
[Bug]: Inventory is Full when upgrade is in slot for Flux Hammer

### ISSUE THREAD

**Issue by FinestGit** [AllTheMods/All-the-mods-9-Sky#444]
### Possible Fixes

Yes

### Modpack Version

1.0.5

### What happened?

When attempting to insert an upgrade into my flux hammer it gives an inventory is full.

![image_2024-06-28_131925375](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/5387800/6bd0af9b-34ef-4aca-a24f-1ca2f72ef21c)

**Comment by FinestGit** [comment]
An additional thing for this, when I attempted to connect it directly to a sieve and not to a functional storage drawer this works.

**Comment by oly2o6** [comment]
This is due to the way drawer systems work, there is not enough room in the current stack to process it once you add the upgrades.

**Comment by FinestGit** [comment]
So even when I use sophisticated storage this is still a problem. So it seems to be more than just the drawer system having this issue.

**Comment by MTVicy** [comment]
hope you already figured it out but all you need is to upgrade your mechanism pipes the pump rate and speed is to slow with basic pipes simple fix would be to use advanced or better then you can use gold/diamond upgrade took me 5 mins or trying to figure out why it wouldn't work when I rebuilt with basic pipes over the advanced ones. hope this helped
