### ISSUE TITLE
[Quests issues]: Arcane Crystal Dust Quest not completing even though all requirements were met. 

### ISSUE THREAD

**Issue by giopro7053** [AllTheMods/All-the-mods-9-Sky#445]
### Modpack Version

1.06

### Describe the issue

Arcane Crystal Dust Quest not completing even though all requirements were met and it says its 100% complete.
![Screenshot 2024-06-28 213049](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/63805161/69cfaa19-5c69-4349-8985-71ddf6b91447)

**Comment by TheBedrockMaster** [comment]
Seems like a bug with FTBQuests, might need to go into editing mode and force complete it.
