### ISSUE TITLE
[Crash]: embeddium is not installed

### ISSUE THREAD

**Issue by AndyNg195** [AllTheMods/All-the-mods-9-Sky#446]
### Possible Fixes

Yes

### Modpack Version

1.20.1

### What happened?

i downloaded atmsky-1.0.6 and server-1.0.6, then installed the modpack manually. I have made sure the files are not broken due to downloading issues. Run forge 1.20.1 and then got the mod missing thing.

### Crash Log

https://gist.github.com/AndyNg195/73d10dec55ef1f9607918147d39f42e0

### Latest.Log

https://gist.github.com/AndyNg195/dc43a09454aca4371677528edbe608a1

**Comment by billbertking1** [comment]
Why not use CurseForge or Prism?
