### ISSUE TITLE
[Quests issues]: Productive Bee's Questline, Quest Named "Oak Expansion Box"

### ISSUE THREAD

**Issue by FaithfulRyan** [AllTheMods/All-the-mods-9-Sky#448]
### Modpack Version

1.0.6 (June 26th Update)

### Describe the issue

There is a simple typo in the description of this quest. At the end of the description there are a set of parenthesis that have "They're are insane" in it. The correct sentence would be, "They're insane" or "They are insane".

**Comment by TheBedrockMaster** [comment]
Also missing a full stop.
