### ISSUE TITLE
[Suggestion] Unify Rubber

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#449]
Rubber should be unified so there isn't 2 types.
![2024-06-29_15 45 37](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/31681339-ea22-4102-b7d5-b6723fc48251)
![2024-06-29_15 45 48](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/13094525-7dde-454d-ab0e-1ee28425c56e)

**Comment by TheLastPaladin** [comment]
This would conflict with Thermal and IF crafting recipes:
- Raw Rubber (IF) furnace smelting into Plastic
- Raw Rubber (TH) furnace smelting into cured rubber

**Comment by TheBedrockMaster** [comment]
Updated it.
