### ISSUE TITLE
'Mystical Green Flower' Quest Missing Reward

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#45]
The 'Mystical Green Flower' Quest in the 'Botania' Chapter doesn't have a reward even though the rest of the mystical flower quests do (I'm guessing this is the same in ATM9).
![2024-06-01_10 48 29](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/81d05050-13d0-46e9-9b5d-56d3f8c61cc8)
![2024-06-01_10 48 42](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/fa481cf3-2ce7-4fe5-ad32-ac0cc63c5cee)

**Comment by ToshibaEC0Microwave** [comment]
Might just be a bug because on my side the reward is there. It'll for sure be in on next update though. I don't think too many people are missing the 10xp

**Comment by TheBedrockMaster** [comment]
I need it 😢
