### ISSUE TITLE
[Quests issues]: Productive Bees Duplicate Quest Line

### ISSUE THREAD

**Issue by giopro7053** [AllTheMods/All-the-mods-9-Sky#451]
### Modpack Version

1.06

### Describe the issue

Previously, I had an issue where I had to go into editing mode to force complete a quest because it wouldn't complete even though all requirements were met (arcane crystal dust quest). After I force completed it, the next day a duplicate Productive Bees Quest Line appeared with no arrows? I didn't know if it was because of me force completing a different quest but, I just deleted it in editing mode. For some reason, when I relogged into the exact same world the quest would appear again even though I deleted it. To see if it was only my world that had the bug and I went into another world that I had already made and it was also there. I created another world and it was there again. ![Screenshot 2024-06-29 102035](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/63805161/2fc6e3fd-bdba-46c9-8106-325cf7961f56)

**Comment by EndDragon438** [comment]
Exact same issue for me.
I force completed the "Completing the Matrix" (Observe a Mekanism Energized Induction Matrix) and the next day the Productive Bees questline duplicated with no progression, and started giving me rewards until I deleted it in editor mode.

**Comment by TheBedrockMaster** [comment]
Seems to happen whenever someone goes into editing mode, weird...

**Comment by kristi71111** [comment]
Issues persists in 1.0.7. Editor mode does seem to play a role.

**Comment by LegendaryTicket9** [comment]
Modpack version 1.0.8 still has the same problem.

**Comment by Abs-Zero** [comment]
> Exact same issue for me. I force completed the "Completing the Matrix" (Observe a Mekanism Energized Induction Matrix) and the next day the Productive Bees questline duplicated with no progression, and started giving me rewards until I deleted it in editor mode.

I have encountered the same situation before, but it was resolved as downloading new game files.
