### ISSUE TITLE
[Bug]: Text on guide books (Ars, Botania, Blood magic etc) are glitchy

### ISSUE THREAD

**Issue by WDevil3221** [AllTheMods/All-the-mods-9-Sky#452]
### Possible Fixes

Yes

### Modpack Version

1.0.6

### What happened?

![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/2744737/8c5968fd-3f08-42e5-a5a3-02059ee923de)
Its happening to most books in my game currently, disabling the font resource pack didn't fix it nor changing my UI size.

**Comment by Furious85** [comment]
This is more to do with the GUI scale. I play with GUI scale 2x but when i change to 3x or 4x the text is much more better.

**Comment by TheBedrockMaster** [comment]
> This is more to do with the GUI scale. I play with GUI scale 2x but when i change to 3x or 4x the text is much more better.

They said that didn't help.
