### ISSUE TITLE
[Quests issues]: Spatial Anchor: has no crafting recipe

### ISSUE THREAD

**Issue by asottile** [AllTheMods/All-the-mods-9-Sky#459]
### Modpack Version

server-1.0.5

### Describe the issue

the "Spatial Anchor" quest in the AE2 questline appears to have no crafting recipe -- looks like it's intentionally disabled:

```console
$ git grep spatial_anchor
config/ftbquests/quests/chapters/applied_energistics_2.snbt:                            item: "ae2:spatial_anchor"
kubejs/client_scripts/jei_hide.js:    event.hide('ae2:spatial_anchor')
kubejs/server_scripts/disable.js:    event.remove({ id:'ae2:network/blocks/spatial_anchor' })
```

**Comment by EndDragon438** [comment]
I'll second this, quest requires the item, no recipe shown in JEI, AE2 wiki shows the correct recipe ([here](https://guide.appliedenergistics.org/1.20.1/items-blocks-machines/spatial_anchor)) and when you put it in manually there's no result.

**Comment by joeychin01** [comment]
Plus one, cannot finish the questline

**Comment by asottile** [comment]
fwiw you can hack around this with `/give` if you have access to server commands
