### ISSUE TITLE
Mystical Flowers needed to unlock Floral Fertilizer Quest

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#46]
### Modpack Version

1.0

### Describe the issue

The Quest 'Floral Fertilizer' requires the completion of the quest 'Welcome to Botania' which requires mystical flowers, which can't be obtained without getting floral fertilizer, so these quests need to be switched around.
![2024-06-01_14 05 07](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/a9799c53-8b68-4a91-a20c-09efee1a8a64)

**Comment by ToshibaEC0Microwave** [comment]
Noted, these quests are being moved around for tts now!
