### ISSUE TITLE
ae2 channels

### ISSUE THREAD

**Issue by CheatIsHere** [AllTheMods/All-the-mods-9-Sky#462]
Is there any way to disable the whole channel thing in ae2 or at least give the cables a lot more channels?

**Comment by TheLastPaladin** [comment]
As long as you have admin priviledges you can simply use:
/ae2 channelmode [default, x2, x3, x4, infinite]

Please consider that this is not the right place to ask those questions, especially if there already is an answer to this online:
https://www.reddit.com/r/feedthebeast/comments/ssvjqc/how_to_turn_ae2_channels_off_now_that_the_config/
If this works for you, please close this issue ticket.
