### ISSUE TITLE
[Quests issues]: Hide an go seek (!) quest completes

### ISSUE THREAD

**Issue by DiggityMan420** [AllTheMods/All-the-mods-9-Sky#468]
### Modpack Version

1.0.6

### Describe the issue

! quest completes behind icon i take it see attachments

Lets play Hide and go seek
![letsplayfind](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/45196448/4900d5ea-bf96-45b5-b1f3-6286d0e4ed03)

there it is
![Screenshot_17](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/45196448/a65805be-88f0-4023-ac46-e44b0df4154e)

**Comment by DiggityMan420** [comment]
this maybe a FTB quests bug i didnt check not a fan of ftb

**Comment by ToshibaEC0Microwave** [comment]
I can't seem to replicate it in game appears to be just a bug on your end
