### ISSUE TITLE
[Crash]: Draconic Evolution Teleporting Issue 

### ISSUE THREAD

**Issue by dopa2077** [AllTheMods/All-the-mods-9-Sky#469]
### Possible Fixes

Yes

### Modpack Version

1.0.6

### What happened?

I have a 4 chunk wide mob farm and i use the dislocator portal thingy from draconic evolution to teleport large amount of entities into a single spot and kill them using mob mashers.

Ever since i remove the portal the crash didn't happened anymore.

![Mob Farm and Mashers](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/84304638/208b950e-376c-40e9-a0f0-6f8cdafb8c6a)

### Crash Log

https://gist.github.com/dopa2077/6116f66c382af64f985c691e2dfdf1d1

### Latest.Log

https://gist.github.com/dopa2077/5b2a2c0bf9eeb53a241b165ea0f20490

**Comment by oly2o6** [comment]
Please report this to draconic evolutions github: https://github.com/Draconic-Inc/Draconic-Evolution/issues 

This does not appear to be a pack issue.
