### ISSUE TITLE
'Archwood logs' Quest not Updated for 9sky

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#47]
### Modpack Version

1.0

### Describe the issue

The quest doesn't tell you that you need to sieve moss to get archwood saplings, instead it says you can find them in the overworld.
![2024-06-01_14 17 18](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/4ac975fe-e0e4-4423-b2ca-74072da41bb3)

**Comment by ToshibaEC0Microwave** [comment]
Don't worry next update it should be skyblock friendly for (most) of the quests
