### ISSUE TITLE
[Bug]: integrated dynamics squeezer no longer turns ores into raw

### ISSUE THREAD

**Issue by SudzBud** [AllTheMods/All-the-mods-9-Sky#470]
### Possible Fixes

Yes

### Modpack Version

1.06

### What happened?

Put ore in and it compresses to a point but never completes to convert into raw ore chunks.

**Comment by DragarX** [comment]
Take off any armor that has negative gravity.

**Comment by SudzBud** [comment]
Thanks, that did it.
