### ISSUE TITLE
Cactus bug?[Bug]: 

### ISSUE THREAD

**Issue by arielggs** [AllTheMods/All-the-mods-9-Sky#471]
### Possible Fixes

Yes

### Modpack Version

1.0.6

### What happened?

![bug cactus](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/59850201/e53fda76-364c-406a-a614-87145ac998aa)
with this setup it autobreaks and grows every second . I don`t know if it`s considered a bug but i posted here anyways

**Comment by Tim-Odermatt** [comment]
Cactus breakes when it sides touches a block.

did you use snad? then the growthspeed is normal, i think.
