### ISSUE TITLE
[Quests issues]: Summon A Piglich quest could be more clear about using the Summoning Altar

### ISSUE THREAD

**Issue by AdimoUK** [AllTheMods/All-the-mods-9-Sky#475]
### Modpack Version

1.0.6

### Describe the issue

Currently the **Getting Started: 2** chapter quest for the Piglich heart (Summon A Piglich)

![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/667616/035033bc-23ca-4c04-b1f2-8c984f33bea3)
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/667616/9d62f415-4f11-40a5-a3ed-03598c2d3c8b)

shows that you need the Piglich heart. Clicking on the heart shows this recipe:

![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/667616/e629df1b-678e-4257-b8ef-8042cdcefa64)

The only thing shown is that Piglich Heart is only obtained by killing the Piglich or by Hostile Neural Networks loot, The quest however talks about summoning a Piglich and not obtaining the heart itself. It is impossible to click over via JEI on any of the tabs to get to how to summon the Piglich using the summoning altar. Only by looking through the Summoning Altar all recipes (had to figure out that must be related since it's stemming off the summoning altar) I found the recipe for summoning the Piglich. So it's not immediately obvious.

To make it clearer, this quest should probably either explain this in detail in the description, or perhaps even better to show this recipe instead:
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/667616/fb21b21f-4573-421d-9a37-acb2e0dc024d)

A suggested change to the description could be along the lines of:

> You can summon one of these _**using a Summoning**_ altar in order to get a Piglich Heart needed for the star. This is extremely expensive though so don't worry about it now.

**Comment by joeychin01** [comment]
It could be slightly more clear, yes, but the quest right before it is the summoning altar quest for a reason

**Comment by TheBedrockMaster** [comment]
This is a suggestion, not a bug.
