### ISSUE TITLE
[Bug]: Totem of Undying unobtainable ?

### ISSUE THREAD

**Issue by thominhaz** [AllTheMods/All-the-mods-9-Sky#478]
### Possible Fixes

Yes

### Modpack Version

1.0.5

### What happened?

I've tried every way I could think of, I even thought about transforming mobs with ProjectE, but it doesn't work, is there an easier way to do this?, if there is...

**Comment by 755437985** [comment]
triger a raid using bad omen and capture the spawned evokers, then just farm them to get infinite totems.

**Comment by EndDragon438** [comment]
you can also kill one of the randomly spawning Evoker bosses from Apotheosis in The End if you just need a couple

**Comment by thominhaz** [comment]
> triger a raid using bad omen and capture the spawned evokers, then just farm them to get infinite totems.

but I need to kill some Pillagers for that to happen xd

**Comment by thominhaz** [comment]
> you can also kill one of the randomly spawning Evoker bosses from Apotheosis in The End if you just need a couple

i will try

**Comment by TheBedrockMaster** [comment]
This can be closed.

**Comment by 755437985** [comment]
> > triger a raid using bad omen and capture the spawned evokers, then just farm them to get infinite totems.
> 
> but I need to kill some Pillagers for that to happen xd

there is also a ability totem of bad omen you can get from a mobfarm

**Comment by thominhaz** [comment]
> > > triger a raid using bad omen and capture the spawned evokers, then just farm them to get infinite totems.
> > 
> > 
> > but I need to kill some Pillagers for that to happen xd
> 
> there is also a ability totem of bad omen you can get from a mobfarm

yes, but it needed to drop 5x to get to the level of spawning evoker, and it doesn't drop these totems so easily...

**Comment by thominhaz** [comment]
> you can also kill one of the randomly spawning Evoker bosses from Apotheosis in The End if you just need a couple
I tried this method, spent about 3 hours exploring the End, and didn't succeed.

**Comment by banana190** [comment]
The End -> Evoker boss -> Mob Imprisonment Tool -> Mob Duplicator -> HNN model

**Comment by thominhaz** [comment]
ok..., but how do i find the evoker boss ?, i flew in the end for 3+ hours and nothing..

**Comment by EndDragon438** [comment]
> ok..., but how do i find the evoker boss ?, i flew in the end for 3+ hours and nothing..

they'll randomly spawn. you just have to get lucky, it's not a super consistent method. you'll probably get a few other Apotheosis spawns before you get an evoker.

**Comment by DreamingLamb** [comment]
I've been buying mine from Wandering Traders.

Use a Mob Swab on one, make the chicken feed, feed that to a chicken to get a Wondering Trader Spawn Egg, put it in a spawner and boom, unlimited Totems (You can only buy 1 per trader that has them) and Sturdy Bee Cages (11 per trader), among other items.

Edit: Zombie Heads too, for EnderIO

**Comment by thominhaz** [comment]
> I've been buying mine from Wandering Traders.
> 
> Use a Mob Swab on one, make the chicken feed, feed that to a chicken to get a Wondering Trader Spawn Egg, put it in a spawner and boom, unlimited Totems (You can only buy 1 per trader that has them) and Sturdy Bee Cages (11 per trader), among other items.
> 
> Edit: Zombie Heads too, for EnderIO

bro no way hahahahahsha, i will try
