### ISSUE TITLE
[Bug]: Broken prediction for wither compass is uncraftable

### ISSUE THREAD

**Issue by mdusevic** [AllTheMods/All-the-mods-9-Sky#479]
### Possible Fixes

Yes

### Modpack Version

1.0.6

### What happened?

![image_2024-07-02_150205742](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/63990279/ecbf50f1-4d96-4929-ab2e-326e68f68212)

Trying to craft the atm star and I'm stuck on the wither compass, can't seem find a way to create this broken prediction to complete it. Is this a bug or intentional?

**Comment by raccoonKannapit** [comment]
It’s JEI bug
the quest description said that is wither prediction
