### ISSUE TITLE
'Welcome to Forbidden & Arcanus' Quest not Updated for 9sky

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#48]
### Modpack Version

1.0

### Describe the issue

The Quest 'Welcome to Forbidden & Arcanus' in the 'Forbidden & Arcanus' Chapter, doesn't explain how you get the darkstone required for the quest.
![2024-06-01_14 15 11](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/5dcd3baf-97e6-4d0d-9e2e-4668d29279c1)

**Comment by ToshibaEC0Microwave** [comment]
Now it will!
