### ISSUE TITLE
[Bug]: Twerk Growing bypasses Tier 6 Mystical Agriculture Cruxes

### ISSUE THREAD

**Issue by EndDragon438** [AllTheMods/All-the-mods-9-Sky#480]
### Possible Fixes

Yes

### Modpack Version

1.0.5

### What happened?

Twerking to grow crops lets you grow tier 6 mystical agriculture crops without a crux underneath them.
This breaks the intentional removal of Gaia Spirit Cruxes to stop players from farming Gaia Spirits.
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/80794635/a162ec3e-5425-4d5c-b888-c64665caa05b)

### latest.log

https://gist.github.com/EndDragon438/e869654845f17ea29d88f47352080481

**Comment by TheBedrockMaster** [comment]
https://github.com/AllTheMods/All-the-mods-9-Sky/issues/317 Duplicate and won't fix.

**Comment by EndDragon438** [comment]
oh oops had an "open" filter on when i checked. thanks @TheBedrockMaster
