### ISSUE TITLE
[Bug]: Squat grow still works with chipped moss blocks

### ISSUE THREAD

**Issue by TanyaPegasus** [AllTheMods/All-the-mods-9-Sky#481]
### Possible Fixes

Yes

### Modpack Version

1.0.6

### What happened?

Squatting near decorative chipped moss blocks causes them to grow and convert the nearby area. This makes it quite difficult to use them for decoration. 
Related to issue #145 
Fixed for minecraft moss blocks here https://github.com/AllTheMods/All-the-mods-9-Sky/commit/583f3893d10c732a0035a50a96fc65775ecb192a

**Comment by oly2o6** [comment]
Adding every single chipped variant there would quite literally make my head explode, going to close this as a wont fix for now, if someone wants to PR in a change I would be all for it

**Comment by TheBedrockMaster** [comment]
> Adding every single chipped variant there would quite literally make my head explode, going to close this as a wont fix for now, if someone wants to PR in a change I would be all for it

Just did it :)
