### ISSUE TITLE
[Crash]: Game Crash When Using Sophisticated Backpack with Dank Storage Dock

### ISSUE THREAD

**Issue by ffcr** [AllTheMods/All-the-mods-9-Sky#482]
### Possible Fixes

Yes

### Modpack Version

1.0.6

### What happened?

When I try to use the Sophisticated Backpack to deposit or restock items from the Dank Storage Dock, the game crashes instantly.

Steps to reproduce the bug:

/give @s sophisticatedbackpacks:backpack
/give @s sophisticatedbackpacks:deposit_upgrade
/give @s sophisticatedbackpacks:restock_upgrade
/give @s dankstorage:dank_1
/give @s dankstorage:dock

Add the Deposit or Restock upgrade to the backpack.
Place items into the backpack or the dock.
Hold the backpack and right-click while sneaking on the dock.

### Crash Log

https://gist.github.com/ffcr/73280a033d7a64945a1ff84b5d1943d5

**Comment by oly2o6** [comment]
These are 2 VERY custom inventories so using them in such a way... I am not surprised it crashed. I would suggest reporting this issue to the mod authors, and just keeping them separate
