### ISSUE TITLE
[Quests issues]: Apatite quest not being completed

### ISSUE THREAD

**Issue by ForlornWolf** [AllTheMods/All-the-mods-9-Sky#484]
### Modpack Version

1.0.6

### Describe the issue

Apatite quest in Mystical Agriculture is not being completed although all the requirements are full fulled including iron mesh quest dependency.
![javaw_07JwAm7rXy](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/101683916/63ad111e-9bc3-4a25-9229-d3482eb8923e)
![javaw_sJOehVnjFN](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/101683916/f1894b26-4ba7-4ca9-8ed9-ff27d15cd86a)

**Comment by ForlornWolf** [comment]
I fixed it by resetting the progress on the both quests

**Comment by TheBedrockMaster** [comment]
Sounds like an FTBQuests issue.

**Comment by oly2o6** [comment]
cant reproduce
