### ISSUE TITLE
[Crash]: Server crash on login @appliedE transmutation importer

### ISSUE THREAD

**Issue by Warzer1** [AllTheMods/All-the-mods-9-Sky#489]
### Possible Fixes

Yes

### Modpack Version

1.0.6

### What happened?

was working fine last night on logout.  left server running overnight.
on login this morning after a server reset the server crashes on login.

I just got unobtainium before logging out for the night.

This seems to be the causes:
<html>
<body>

Description: Ticking GridNode
--
6 |  
7 | java.lang.ArithmeticException: / by zero
8 | at gripe._90.appliede.me.service.EMCStorage.insert(EMCStorage.java:72) ~[appliede-0.13.1-beta.jar%23413!/:?] {re:classloading}
9 | at appeng.me.storage.NetworkStorage.insert(NetworkStorage.java:136) ~[appliedenergistics2-forge-15.2.4.jar%23414!/:15.2.4] {re:classloading}
10 | at appeng.api.storage.StorageHelper.poweredInsert(StorageHelper.java:166) ~[appliedenergistics2-forge-15.2.4.jar%23414!/:15.2.4] {re:mixin,re:classloading}

</body>
</html>Description: Ticking GridNode

java.lang.ArithmeticException: / by zero
	at gripe._90.appliede.me.service.EMCStorage.insert(EMCStorage.java:72) ~[appliede-0.13.1-beta.jar%23413!/:?] {re:classloading}
	at appeng.me.storage.NetworkStorage.insert(NetworkStorage.java:13[6](https://mclo.gs/jpVNB3b#L6)) ~[appliedenergistics2-forge-15.2.4.jar%23414!/:15.2.4] {re:classloading}
	at appeng.api.storage.StorageHelper.poweredInsert(StorageHelper.java:166) ~[appliedenergistics2-forge-15.2.4.jar%23414!/:15.2.4] {re:mixin,re:classloading}

### Crash Log

https://gist.github.com/Warzer1/9c761280285a88c40c2c280461abdd23

### Latest.Log

https://gist.github.com/Warzer1/93521ec6cfe1a2fc83b031a42aa29c35
**current fix** is to use Amulet to delete the block then reload the world.

Edit: more info after i was able to delete the the block using amulet.
this was an transmutation importer (I think) attached to an energy condenser mk1 crafting phantom membranes.  around the energy condenser was a power flower - AM relays then energy collectors attached to them.
This was setup a few days ago so no idea what choked.
edit2: was able to replicate the crash.  as soon as i attached a cable to the transmutation importer with 4 acc cards but no listed filters it crashed with the divide by 0

**Comment by oly2o6** [comment]
ill close this for now as it does appear to be a mod issue
