### ISSUE TITLE
Nipa Plants Quest 

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#49]
### Modpack Version

1.0

### Describe the issue

The quest 'Nipa Plants' in the 'Forbidden & Arcanus' Chapter says you can find the islands in the sky, but I haven't seen any.
![2024-06-01_14 15 34](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/96387621-26d2-4f77-a39f-b47dde35a0b0)

**Comment by ToshibaEC0Microwave** [comment]
You can't find them in the overworld

**Comment by Eragonawesome** [comment]
Okay, where CAN you find them? I've explored the nether and the end with no luck. I'm not sure what I'm missing.

**Comment by TheBedrockMaster** [comment]
They were removed from being needed.

**Comment by Eragonawesome** [comment]
Ah, I'm a few versions behind it seems. thank you!
