### ISSUE TITLE
Broken Apotheosis Quest Items

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#493]
### Modpack Version

1.0.7

### Describe the issue

These quests now require missing items to complete.
![2024-07-04_13 00 37](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/cc311295-c9b7-4f4d-8c2e-091cf19c7b70)
![2024-07-04_13 00 39](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/f57e1d72-e9bb-40e4-ae0e-516ca8da5283)
![2024-07-04_13 00 41](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/71db85fd-ccdf-4bdf-8f47-e4ee2a2bc88d)
![2024-07-04_13 00 45](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/bcca9181-e741-457b-baf1-042fd677cc8f)

**Comment by Legrems** [comment]
If this can help, this is due to the upgrade of apotheosis from 7.3.x to 7.4
