### ISSUE TITLE
Mystical Agriculture Broken Quest Names

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#495]
### Modpack Version

1.0.7

### Describe the issue

These quest names are broken. Probably because of the multiple lang files.
![2024-07-04_14 41 19](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/fb1934d3-2b62-4e04-b09a-61d23cd9c598)
![2024-07-04_14 41 17](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/6db0c646-75b8-48b7-98a0-582ff0386262)
![2024-07-04_14 41 16](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/d24bd69b-7705-4f28-968f-6067bc2e4ea1)

**Comment by llearch** [comment]
FYI: A quick (hacky, somewhat ugly) grep loop shows that these titles are set in elmysticalagriculturerr.snbt, but not in [en_us|es_es|jp_jp].json:

atm9.quest.ma.bonemeal
atm9.quest.ma.inferiumarmor
atm9.quest.ma.inferiumtools
atm9.quest.ma.elementalseeds

That last one is also broken in the same fashion, but I suspect it's relatively easily resolved by writing something usable into the json. It is unclear (to me) if there is any specific place in said file it should be, however, and I'd not like to mess up the code more than it already is...

**Comment by TheBedrockMaster** [comment]
I'm aware why, they didn't copy it from my PR.
