### ISSUE TITLE
[Bug]: Invalid Rewards - Missing Item

### ISSUE THREAD

**Issue by SnowbankNL** [AllTheMods/All-the-mods-9-Sky#498]
### Possible Fixes

Yes

### Modpack Version

1.0.7

### What happened?

I dont know if it is also other tiers, but the Rare Rewards have Invalid rewards.

![invalid rewards](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/1788120/6b242278-da9d-4240-96c3-d0ed3f5d3812)

I got this 'mininggadgets:mininggadget_simple as a reward for the tier 4 stack upgrade for the backpack.
![mininggadget_simple](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/1788120/b848be81-5747-4b30-87e2-a393bbeab085)

**Comment by TheBedrockMaster** [comment]
This is a quest bug.
