### ISSUE TITLE
[Bug]: Magma Cream no longer has an EMC value as of 1.0.7

### ISSUE THREAD

**Issue by alexsch01** [AllTheMods/All-the-mods-9-Sky#499]
### Possible Fixes

Yes

### Modpack Version

1.0.7

### What happened?

version 1.0.6 - magma cream has an EMC value
version 1.0.7 - magma cream doesn't have an EMC value

The correct value should be 64

**Comment by TheBedrockMaster** [comment]
I'll make sure this is fixed :)
