### ISSUE TITLE
'Arcane Crystals' Quest not updated for 9sky

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#50]
### Modpack Version

1.0

### Describe the issue

The quest 'Arcane Crystals' in the 'Forbidden & Arcanus' Chapter says to go out and mine some instead of mentioning how you get them from sieving.
![2024-06-01_14 15 23](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/b3f1f50c-eb9d-4dac-99ad-f9fe752a90e4)

**Comment by ToshibaEC0Microwave** [comment]
Next update there won't be any mentions of mining
