### ISSUE TITLE
[Bug]: superior socketing?

### ISSUE THREAD

**Issue by DevilMayCryIfrit** [AllTheMods/All-the-mods-9-Sky#503]
### Possible Fixes

Yes

### Modpack Version

1.0.7

### What happened?

I don't know if this is a bug or what and I can't find anything in change logs. But the apotheosis sigil of superior socketing has been removed. Is not craftable and the ones already made are gone even the ones on item frames.

**Comment by Legrems** [comment]
Apotheosis was upgraded to version 7.4 (changelog of apotheosis [here](https://github.com/Shadows-of-Fire/Apotheosis/blob/1.20/changelog.md#740)). Therefor supersior sigil were removed
