### ISSUE TITLE
[Bug]: Occulstism Ritual Abra' s Conjure doesn't place correctly from the Dictionary of Spirits

### ISSUE THREAD

**Issue by bign0se1** [AllTheMods/All-the-mods-9-Sky#506]
### Possible Fixes

Yes

### Modpack Version

1.0.7

### What happened?

If you visualize Abra' s Conjure from the dictionary, you get the wrong ritual. It appears to be the ritual for Abra's Commanding Conjure. I can't figure out how the ritual for Abra's Conjure is supposed to go.

**Comment by bign0se1** [comment]
Sevira's Permanent Confinement seems to also use the same pentacle setup

**Comment by Kevin-Marsh** [comment]
Allthemods features a revised pentacle that has 4 stages and is built as a single master ritual. A lot of the ritual names will use the same pentacle. Every single ritual can be performed in Uphyxes Inverted tower at the end. The rituals you are clicking in the dictionary are all correct.

https://imgur.com/a/ritual-rework-uVYhEML
