### ISSUE TITLE
'Welcome to Powah!!!' Quest not updated for 9sky

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#51]
### Modpack Version

1.0

### Describe the issue

The Quest 'Welcome to Powah!!!' in the 'Powah' Chapter says to get uraninite from mining.
![2024-06-01_16 41 04](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/338002fa-fa26-4f3a-8f5b-ab95c8fc9f53)

**Comment by ToshibaEC0Microwave** [comment]
Now it's changed to cooked uraninite and now explains how to make them
