### ISSUE TITLE
[Bug]: Diamond Gears recipe broken for multiservo press

### ISSUE THREAD

**Issue by DriesDelanghe** [AllTheMods/All-the-mods-9-Sky#510]
### Possible Fixes

Yes

### Modpack Version

Atm9-To the Sky 1.0.7

### What happened?

the recipe for diamond gears from the AllTheOres mod using the multiservo press with a gear die displays a broken recipe using JEI.
Using 4 diamonds in the multiservo press does also not result in a diamond gear.
This can either be a broken recipe, or a recipe that was not meant to be included?

![afbeelding](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/75736368/4abd34a7-7ba5-40aa-bcfc-adeaa3503944)

**Comment by LuciusV** [comment]
And it is already been here for one month: https://github.com/AllTheMods/All-the-mods-9-Sky/issues/198 seems they consider it low priority

**Comment by LuciusV** [comment]
So any hope for fix?
