### ISSUE TITLE
[Quests issues]: Dupe of #493. Please delete

### ISSUE THREAD

**Issue by Nilser05** [AllTheMods/All-the-mods-9-Sky#515]
Dupe of #493. Please delete

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/All-the-mods-9-Sky/issues/493

**Comment by Nilser05** [comment]
> Dupe: #493

Sorry, I even looked at the other issues there were. Must've overlooked it.

**Comment by TheBedrockMaster** [comment]
You can close this yourself
