### ISSUE TITLE
[Bug]: Flux Compactor does not compact non Vanilla Ore Chunks

### ISSUE THREAD

**Issue by Satherov** [AllTheMods/All-the-mods-9-Sky#52]
### Possible Fixes

Yes

### Modpack Version

1.0

### What happened?

The Flux compactor does not compact any non-vanilla ore chunks. Iron, Copper & Gold work fine, but everything else does not get compacted, even though the machines says it's operational

**Comment by TheBedrockMaster** [comment]
Already known issue: https://github.com/AllTheMods/All-the-mods-9-Sky/issues/43
