### ISSUE TITLE
[Crash]: I can't start the game

### ISSUE THREAD

**Issue by pik4li** [AllTheMods/All-the-mods-9-Sky#520]
### Possible Fixes

Yes

### Modpack Version

1.0.7

### Issue Description

I downloaded the modpack with GD-Launcher. When I start the pack, it loads until the following screen appears:
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/67532734/62dd2430-8dba-4910-8d19-235e54fb8a80)

It stays there for about 10-20 seconds and then just closes out—no crash, no error message, just closes. There isn't even a `/instance-name/crash-reports/` folder. I'll upload the latest.log for reference.

I'm on Arch Linux and other modpacks, such as Seaopolis Submerged, run fine without issues. I had the same issue with Version 1.0.6 and hoped, that the next release will fix it..

Any help would be appreciated.

### Additional Information

- **Operating System**: Arch Linux
- **Log File**: [latest.log]

### Crash Log

https://gist.github.com/pik4li/e62ac07e3ffc172151fed0fb30162c79

**Comment by pik4li** [comment]
## Update

I tried installing ATM9, and it works.. Maybe this info will help..

**Comment by smbarbour** [comment]
That log shows a lot of missing classes and model definitions...  It seems like it definitely did not install properly.

**Comment by pik4li** [comment]
The odd thing is, why is ATM9 running without a problem? Same procedure, I even cleared all cache and all the mod folder, reinstalled eveything, same error..

**Comment by Koupius** [comment]
With this being Linux and TTS being affected where ATM9 is not, I want to say this is a libopenal issue in which case the fix is to create a ".alsoftrc " config file in your $HOME folder with the contents "devices=pulse". Other than that, the latest.log doesn't seem to provide much in what frame caused the crash.

**Comment by pik4li** [comment]
> With this being Linux and TTS being affected where ATM9 is not, I want to say this is a libopenal issue in which case the fix is to create a ".alsoftrc " config file in your $HOME folder with the contents "devices=pulse". Other than that, the latest.log doesn't seem to provide much in what frame caused the crash.

Thanks mate! Will try it out in a bit 👍

**Edit:** still no luck.. Even updated to the 1.0.8a release..

**Comment by TomSmithThe3rd** [comment]
The following fixed this issue for me (linux only guide):
1. ensure openal is installed using your preferred package manager. For me it was:
`sudo pacman -S openal`

2. create the .alsoftrc in your home directoy:
`touch ~/.alsoftrc`

3. open the file in your preferred text editor:
`nano ~/.alsoftrc`

4. add the following configuration
```
[general]
drivers=pulse
hrtf=true
```

5. reboot for good measure and test.

**Comment by arkan501** [comment]
I was having this issue too on Garuda, arch-based distro. The steps that @TomSmithThe3rd outlined fixed the issue for me and allowed me to run the modpack.
