### ISSUE TITLE
[Quests issues]: Mekanism in-world triggers broken

### ISSUE THREAD

**Issue by RLeendertz** [AllTheMods/All-the-mods-9-Sky#522]
### Modpack Version

Atm9-To the Sky 1.0.7 (Release)

### Describe the issue

In the **Mekanism: Advanced** questline, there are some quests that require you to look at a certain completed multiblock.
All of these do not complete:
- Completing the matrix: _Observe a completed induction matrix_
- Uranium oxide: _Observe uranium oxide in a machine_
- Creating power with the turbine!: _Observe a completed turbine_
- Build the SPS!: _Observe a completed SPS_
- I think we're ready: _Observe a completed fusion reactor_

I've looked at each machine, broken&replaced a block and waited a bit, interacted with the machines, and activated them. In the case of the uranium oxide i've also put the it in a chemical tank and looked inside that.

![2024-07-07_19 15 45](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/33118960/22bdacce-f0bc-430f-88da-13d0fe8b5e87)
![2024-07-07_19 20 40](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/33118960/b4877949-96a7-45df-ba48-ff0da50ff6b7)
(NB: I've force completed the uranium oxide quest so I could keep on progressing. All the other quests mentioned are still uncompleted.)

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/All-the-mods-9-Sky/issues/341
