### ISSUE TITLE
[Bug]: Blood Magic - Alchemical Reaction Chamber - Missing Texture

### ISSUE THREAD

**Issue by JCrider2** [AllTheMods/All-the-mods-9-Sky#523]
### Possible Fixes

Yes

### Modpack Version

1.0.07

### What happened?

When the Sanguine Reverter of Blood magic is placed into the Alchemical Reaction Chamber, the texture of the Alchemical Reaction Chamber breaks, game still playable.

**Comment by TheBedrockMaster** [comment]
Seems to be an issue with the mod, not this pack.

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/All-the-mods-9-Sky/issues/429
