### ISSUE TITLE
[Quests issues]: Mystical Agriculture not allowing the questline to begin.

### ISSUE THREAD

**Issue by CWinger282** [AllTheMods/All-the-mods-9-Sky#532]
### Modpack Version

1.0.7

### Describe the issue

Mystical Agriculture questline is not allowing me to begin.  It appears as if it requires another quest to be completed, but there are no required dependencies.

**Comment by TheBedrockMaster** [comment]
Can you show an image of this?

**Comment by Nionor** [comment]
I have the same problem
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/36626165/526acfd6-9d38-407f-92fa-1e27a986d853)
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/36626165/a0e40754-4f43-4d83-bec9-57df7a91e9b9)
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/36626165/316e222a-a6be-4df6-9658-da4b9b7032c1)

**Comment by Nionor** [comment]
I "solved" it by resetting the quest with the _/ftbquests editing_mode_ command and then right clicking the quest.

**Comment by CWinger282** [comment]
> I "solved" it by resetting the quest with the _/ftbquests editing_mode_ command and then right clicking the quest.

This did it.  Thank you for recommending it.
