### ISSUE TITLE
[Bug]: Mistake Maybe creative items

### ISSUE THREAD

**Issue by DiggityMan420** [AllTheMods/All-the-mods-9-Sky#533]
### Possible Fixes

Yes

### Modpack Version

1.0.7

### What happened?

see pics maybe just adding the star to fix but placing a the item in and waiting will get you a creative item all the wireless grids are like this just 2 examples

![Screenshot_20](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/45196448/66039f16-c703-404b-a6d9-e7675740b93d)
![Screenshot_19](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/45196448/e880d9e7-92e8-47c6-a87f-acbb55774c6c)

**Comment by TheBedrockMaster** [comment]
I don't think these are useful enough to need a star to craft, I guess it could be a bug though.
