### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by Smrots** [AllTheMods/All-the-mods-9-Sky#535]
### Possible Fixes

Yes

### Modpack Version

1.0.7

### What happened?

It crashes at the end of loading the mods then the client freezes then closes.

### Crash Log

https://gist.github.com/Smrots/9a94080878092ea5d44b105e54b7907f

### Latest.Log

https://gist.github.com/Smrots/aa6ea4bbbcd310f39914955e3257ef05

**Comment by Koupius** [comment]
This is a known issue with Linux with atm9tts, you will need to create a ".alsoftrc " config file in your $HOME folder with the contents "devices=pulse".

**Comment by Smrots** [comment]
> This is a known issue with Linux with atm9tts, you will need to create a ".alsoftrc " config file in your $HOME folder with the contents "devices=pulse".

Thank you this did the trick.
