### ISSUE TITLE
[Bug]: Mekanism Lithium chain broken

### ISSUE THREAD

**Issue by dcaster19** [AllTheMods/All-the-mods-9-Sky#536]
### Possible Fixes

Yes

### Modpack Version

1.0.7

### What happened?

The 'Rotary Condensetrator' decondensentrating recipe for liquid lithium to 'chemical' lithium is missing, breaking the chain. This invalidates "Advanced Power Storage" Quest information in Mekanism: Advances The only way to get lithium is currently through Alchemistry.

**Comment by klaujesi** [comment]
I was experience same issue, but re-starting the game, solve it. It's was working fine, then stop. I've restarted and anything works again.
![Lithium](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/6095955/26d112b2-107d-4df4-a41c-a94a80a6e1d7)

**Comment by dcaster19** [comment]
Yep, restarted the same world this afternoon and the recipe is back as it supposed to be. Still weird that it failed to register the first time but doesn't seem to be a bug for the pack.
