### ISSUE TITLE
[Bug]: Un-craftable refined obsidian 

### ISSUE THREAD

**Issue by Lolimpo** [AllTheMods/All-the-mods-9-Sky#540]
### Possible Fixes

Yes

### Modpack Version

1.0.7

### What happened?

Refined obsidian currently is uncraftable. You need to put 'Refind Obsidian Dust' to 'Osmium Compressor', but to get the dust you need to crush 'Refind Obsidian Ingot'. The only way is to use bees combination of Osmium and Obsidian bees. But I don't see this way in quest line and it's pretty unclear for that stage of a game.

![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/35700154/0d41c72b-5143-4037-9d64-e78537fe79b3)
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/35700154/617347d2-e08b-4113-9775-1d606dab3cd5)

**Comment by Koupius** [comment]
Please try restarting the game completely as JEI can occasionally stop providing recipes and this is a common solution. If that does not work, please try deleting Mekanism completely and reinstalling it.

**Comment by Lolimpo** [comment]
Restarting the game and re-installing mekanism didn't help at all. Even reinstalled the modpack. 
Installed version 1.0.8 and all fixed :)

**Comment by Lilyririone** [comment]
Im on 1.0.8 cannot craft, restarted the game multiple times
