### ISSUE TITLE
[Bug]:  Wireless crafting grid disappears after dying and respawning!

### ISSUE THREAD

**Issue by Pyario** [AllTheMods/All-the-mods-9-Sky#541]
### Possible Fixes

No

### Modpack Version

1.0.7

### What happened?

The title says it all, when you die and respawn the wireless-crafting grid from Refined Storages disappears from your inventory. That's really annoying!

**Comment by 755437985** [comment]
maybe it's equipped in your curio slot

**Comment by Pyario** [comment]
No, it's only in the inventory or in the hotbar.
