### ISSUE TITLE
[Bug]: Refined Storage Crafting Grid not showing Items after a while of playing

### ISSUE THREAD

**Issue by Zombexx** [AllTheMods/All-the-mods-9-Sky#542]
### Possible Fixes

Yes

### Modpack Version

1.0.6

### What happened?

The Refined Storage Crafting Grid (and also the wireless version) wont show items after a while of playing. It still works for crafting. Every other Grid still works (e.g. normal grid or fluid grid.

The only way to get it working again is to restart the game

![2024-07-12_01 33 25](https://github.com/user-attachments/assets/030af186-96d1-4df5-8ae6-9e1c1c4f18fa)

### latest.log

https://gist.github.com/Zombexx/e6e2d7ef5395b10f9908c600c77edd1f

**Comment by Zombexx** [comment]
Update:

I saw that i had a pattern in the crafting grid, removing it fixed it.

BUT:  The issue still is there and for all of the grids!

**Comment by Nilser05** [comment]
I have this problem as well. Mostly after crafting multiple thousands of items quickly by hand (e.g. Autoclicker). But without the filter in the grid of course
