### ISSUE TITLE
[Quests issues]: Iesnium quest missing text lines & odd requirements

### ISSUE THREAD

**Issue by RLeendertz** [AllTheMods/All-the-mods-9-Sky#548]
### Modpack Version

1.0.7 (Release)

### Describe the issue

The quest for Iesnium ore (_Iesnium: The ore of the otherworld_) has missing text lines:
![2024-07-12_22 27 59](https://github.com/user-attachments/assets/aebe7142-7422-4021-96ea-f09c4c5010a2)

Furthermore, the quest misdirects you, requiring Iesnium ore directly, while it asks you to sieve blackstone. Blackstone sieving produces raw Iesnium:
![2024-07-12_22 32 41](https://github.com/user-attachments/assets/2be1ae52-ac36-41a1-9e92-389e84864a7e)
So this method of obtaining Iesnium does not complete the quest. 

I believe the fixing of issue https://github.com/AllTheMods/All-the-mods-9-Sky/issues/231 caused the missing text.

**Comment by asoshinsky** [comment]
the bug persists in the version 1.0.8a
