### ISSUE TITLE
Quests don't tell you how to get Uranium

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#55]
### Modpack Version

1.0

### Describe the issue

The quest 'Welcome to Bigger Reactors!' in the 'Bigger Reactors' Chapter doesn't explain how you get uranium from sieving crushed deepslate.
![2024-06-01_21 52 39](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/44da051d-c933-44a8-99c6-ca1198654d5b)

**Comment by ToshibaEC0Microwave** [comment]
I had some problems with finding it via JEI but it does work and quests now reflect that
