### ISSUE TITLE
[Quests issues]: storage controller

### ISSUE THREAD

**Issue by llearch** [AllTheMods/All-the-mods-9-Sky#553]
### Modpack Version

1.0.8

### Describe the issue

The storage controller quest title is missing, resulting in it reporting the title as "atm9.quest.storage.f_controller", with the subtext "atm9.quest.storage.subt.f_controller"
en_us.json has atm9.quest.storage.desc.f_controller, but not the other two.

**Comment by Jmpp2909** [comment]
Ill have a look, thanks

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/All-the-mods-9-Sky/issues/551
