### ISSUE TITLE
[Quests issues]: rewards missing from alchemistry quests

### ISSUE THREAD

**Issue by llearch** [AllTheMods/All-the-mods-9-Sky#554]
### Modpack Version

1.0.8

### Describe the issue

The "Random Reward" for the Alchemistry quests returns nothing. This applies to at the very least, Lead Oxide, Silicon Dioxide, Yttrium, Tungsten, Fission Reactor, Fusion Reactor,  Graphite, Graphite Dust, and Nether Stars quests.

Note that Lead Oxide has a different icon to the others, and shows a reward screen that is blank, rather than just nothing at all.

**Comment by TheBedrockMaster** [comment]
I can't seem to reproduce, although the lead oxide quest is claimed differently for some reason. They all still give me basic elements though.
