### ISSUE TITLE
[Bug]: no recipe for hdpe pellets

### ISSUE THREAD

**Issue by ghost** [AllTheMods/All-the-mods-9-Sky#557]
### Possible Fixes

Yes

### Modpack Version

Atm9-To the Sky 1.0.8

### What happened?

![Screenshot 2024-07-13 133354](https://github.com/user-attachments/assets/bb4e7448-70a3-4346-8d3a-46fbbf74f42f)

### latest.log

https://gist.github.com/anne022599/35acec554dac0f333671c48f060fa4fe

**Comment by Necrozma222** [comment]
please respond I have the same problem

**Comment by Feurio90** [comment]
Restart your game. This is an one-time bug.
