### ISSUE TITLE
'Meteorite Hunting' Quest not updated for 9sky

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#56]
### Modpack Version

1.0

### Describe the issue

The quest 'Meteorite Hunting' in the 'Applied Energistics' Chapter says you need to find a meteorite in order to obtain the presses.
![2024-06-01_22 14 10](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/5f4f9317-3aea-428c-b70b-f0a31f6c4bc2)

**Comment by billbertking1** [comment]
AE2 questline is getting a rework done, unsure when will be finished.
