### ISSUE TITLE
[Quests issues]: Blood Magic Rune Requirements

### ISSUE THREAD

**Issue by 404jamesnotfound** [AllTheMods/All-the-mods-9-Sky#564]
### Modpack Version

1.0.7

### Describe the issue

The quest requirements for each tier of blood altar all require the number of blank runes. This sets the expectation that the player will not create any other types of rune until the altar is complete. I made 8 runes for tier 1 and immediately crafted them into speed runes. This means I have to make 8 redundant runes to meet the requirements for the tier 2 quest. A potential fix would be to set the quests to simply require any of the types of runes.

**Comment by TheBedrockMaster** [comment]
Have you tried updating?

**Comment by 404jamesnotfound** [comment]
yeah 1.0.8 is good
