### ISSUE TITLE
[Quests issues]: Guardian Crystal kills not registering

### ISSUE THREAD

**Issue by Meryl** [AllTheMods/All-the-mods-9-Sky#568]
### Modpack Version

1.0.8a

### Describe the issue

I've been attempting to kill the chaos guardian. After about an hour and a half of cheesing it using the /back command, I had managed to destroy 10 crystals. I ended up bailing, because it's just too tedious, but none of those kills counted. It's still at 0/14 guardian crystals killed.

**Comment by asottile** [comment]
I destroyed all 14 (twice) and the achievement did not register as well

**Comment by markuskoeppen** [comment]
Same here.

**Comment by SaturatedMatt1** [comment]
same

**Comment by 007Bondo** [comment]
Same issue, still on 1.1.1. I think it has something to do with the crystals not being enemies. I found the bug and tried checking the mobs stats page and it didn't show up there. I even died to one and it still didn't show up. May need to change requirement?

**Comment by VioletRailgun** [comment]
If you're still having issues completing the quest you can use the command: /ftbquests change_progress <Insert name here> complete 106D08542AAFA166
and it'll complete the quest for you. Same goes for all other quests, in the files of the game under FTBQUESTS you can find the list of all the codes for each quest.
