### ISSUE TITLE
'Edelwood Trees' Quest not updated for 9sky

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#57]
### Modpack Version

1.0

### Describe the issue

The quest 'Edelwood Trees' in the 'Forbidden & Arcanus' Chapter says to find them in a Dark Forest biome.
![2024-06-01_22 21 48](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/4325c33b-47a1-4542-9f52-7956a49be8af)

**Comment by ToshibaEC0Microwave** [comment]
It's gonna be changed in next update
