### ISSUE TITLE
[Bug]: Dragon Scales needed for the ATM star - not dropping from the Ender Dragon

### ISSUE THREAD

**Issue by alexsch01** [AllTheMods/All-the-mods-9-Sky#578]
### Possible Fixes

Yes

### Modpack Version

v1.0.8a

### What happened?

I have killed the Ender Dragon at least 5 times - no luck and i have a magnet

**Comment by desagas** [comment]
I have gotten scales nearly every time I have killed the dragon, in every version they have been in the pack, and even the most recent versions.
