### ISSUE TITLE
[Bug]: Viewing a JEI recipe in a Crafting Station lags the Game

### ISSUE THREAD

**Issue by Alex-265** [AllTheMods/All-the-mods-9-Sky#58]
### Possible Fixes

Yes

### Modpack Version

1.0.0

### What happened?

When I open the recipe for a water wheel (Create) in a crafting station, the game lags.

https://github.com/AllTheMods/All-the-mods-9-Sky/assets/63714415/4b50c5ce-57d4-4ac2-8c11-15b706a82138

### latest.log

https://mclo.gs/RQz3E5k

**Comment by oly2o6** [comment]
#156
