### ISSUE TITLE
[Quests issues]: Occultism quest descriptions not translated

### ISSUE THREAD

**Issue by ReikoAldrakar** [AllTheMods/All-the-mods-9-Sky#595]
### Modpack Version

1.0.9

### Describe the issue

In the occultism questline, quest: Iesnium: Ore of the Otherworld: 
![image](https://github.com/user-attachments/assets/28c6a817-d31d-4b52-b036-b53785db755c)

**Comment by TheBedrockMaster** [comment]
Forgot to add this one, I'll put a fix for it in my next PR, sorry.
Also dupe of: https://github.com/AllTheMods/All-the-mods-9-Sky/issues/548
