### ISSUE TITLE
Complete Translation of Modpack Quests to Portuguese

### ISSUE THREAD

**Issue by GuilhermeHSMarinho** [AllTheMods/All-the-mods-9-Sky#596]
# Please include the complete translation of the modpack to Brazilian Portuguese that I have completed.

Modpack version: 1.0.9
Translation: 100% finished
[pt_br.json](https://github.com/user-attachments/files/16325938/pt_br.json)

**Comment by DarcZera** [comment]
Up
Approved, Eu so colocaria o nome dos titulos dos mod originais como, Mekanism, Blood Magic.... e alguns nomes como, Overworld, coisas mais classicas do minecraft, fica mais facil para identificar as coisas.

**Comment by ArcTrooper210** [comment]
You can submit a PR following this guide. [https://allthemods.github.io/alltheguides/guides/translations/](https://allthemods.github.io/alltheguides/guides/translations/)

**Comment by GuilhermeHSMarinho** [comment]
@DarcZera fiz a modificação deixando o nome dos mods sem serem traduzidos

**Comment by nitrog0d** [comment]
You're translating mod names (Like Mystical Agriculture -> Agricultura Mística), Minecraft things like Overworld and stacks, mod item names and the Modpack name. This is not ideal I believe, it's the equivalent of translating a game name to another language, not only it looks weird but also very much makes Google searching for things harder, and likely other problems I can't think of right now...

This is very likely AI translated and that means low quality...

**Comment by GuilhermeHSMarinho** [comment]
@nitrog0d In the version I sent in the pull, I've corrected this and left the original name of the mods
