### ISSUE TITLE
[Quests issues]: AllTheModium chapter not completing - duplicate step

### ISSUE THREAD

**Issue by JakeMoe** [AllTheMods/All-the-mods-9-Sky#597]
### Modpack Version

1.0.9

### Describe the issue

I've completed all the steps for the AllTheModium chapter, but it wouldn't show complete.  Looking closely, I noticed the Nitro Crystal step had the green tick mark obscured, like it was under the step instead of on top.  Went in to editing mode and move the nitro crystal step out of the way, and found a second nitro crystal step underneath it.  Getting out of editing mode and putting a nitro crystal in my inventory allowed the second one to complete, and finished the chapter for me.

![01-NitroCrystalTickObscured](https://github.com/user-attachments/assets/92bee443-ba6e-4fcb-8434-9354919719fc)
![02-NitroCrystalDuplicated](https://github.com/user-attachments/assets/efe5dc2c-b5cd-4b31-8be8-b5a71cb0cc13)

**Comment by ReikoAldrakar** [comment]
I noticed the checkmark, but wasn't done with the chapter so I didnÄt have a problem, but yes can confirm, this is a problem for me too
