### ISSUE TITLE
[Quests issues]: Productive Bees duplicate

### ISSUE THREAD

**Issue by JCrider2** [AllTheMods/All-the-mods-9-Sky#605]
### Modpack Version

1.0.9

### Describe the issue

A duplicate of the productive bees quest tab has appeared and all the quest are incomplete. The original tab still contains original completed quests. Within the duplicated quest tab, the guidance arrows are missing,
Updated pack from 1.0.8a to 1.0.9 played signed off, on a new day the issue has appeared.

**Comment by Nilser05** [comment]
Dupe #594

**Comment by MoonDance911** [comment]
this is fixed

**Comment by realTIMematrix** [comment]
Not fixed. Using 1.1.0 and Questline appears twice

**Comment by nitrog0d** [comment]
^^

**Comment by MoonDance911** [comment]
> this is fixed

sorry mb guys i was on the wrong version

**Comment by psxlover** [comment]
1.1.1 still has the issue.
