### ISSUE TITLE
[Bug]: Item hover window synced with advancement completion window fade

### ISSUE THREAD

**Issue by Leviathan1132** [AllTheMods/All-the-mods-9-Sky#61]
### Possible Fixes

Yes

### Modpack Version

1.0.0

### What happened?

![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/74594063/592c9d2c-472b-4a68-8109-e8d9f8ff5eb0)
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/74594063/1b6f8e51-c595-4c2a-9a5c-e5e6b95c31e8)
When you hover over an item, the box will fade in and out if you have completed an advancement that spawns that box that fades out with some sound to it

**Comment by oly2o6** [comment]
fixed in 1.0.2
