### ISSUE TITLE
[Quests issues]: No recipe Reinforced Alloy

### ISSUE THREAD

**Issue by josdani** [AllTheMods/All-the-mods-9-Sky#610]
### Modpack Version

ATM9 To the SKy

### Describe the issue

In Mekanism modpack there's no recipe for Reinforced Alloy, the only way to get it is from rewards

**Comment by ReikoAldrakar** [comment]
I had that problem before, restarting the game fixed it, I had it with Infused alloy, there seems to be a bug that ppl had before
I don't have the link anymore but I think there was a lot of talk bout it on reddit saying "clear your config" and stuff

For me all recipes are there: 
![image](https://github.com/user-attachments/assets/c15828a7-168f-412c-9e79-a641f0577ab9)
