### ISSUE TITLE
[Bug]: No recipe for Limestone

### ISSUE THREAD

**Issue by ReikoAldrakar** [AllTheMods/All-the-mods-9-Sky#611]
### Possible Fixes

Yes

### Modpack Version

1.0.9

### What happened?

There's no recipe for limestone which blocks me in getting ALL mystical agriculture seeds
Totally not one of my private goals in thais pack >.>

**Comment by TheBedrockMaster** [comment]
Make a cobble gen, but with honey instead of water.

**Comment by ReikoAldrakar** [comment]
This works!
Important: You need a bucket of create honey for it to work, Productive bees honey does not work.
