### ISSUE TITLE
[Quests issues]: Final Quest in Productive bees has an outdated/wrong description

### ISSUE THREAD

**Issue by ReikoAldrakar** [AllTheMods/All-the-mods-9-Sky#612]
### Modpack Version

1.0.9

### Describe the issue

The Quest "2x ATM Star Block" says "Normally you'd need 2 ATM Star Blocks to get Starry Bees up and running, but this skyblock doesnt have those in :("

There is a breeding recipe for the starry bee: Conversion -> Patrick Bee + ATM Star Block
And Patrick Bee has a recipe saying it can be found by fishing

So I believe the text is wrong/outdated. And if it's not, the the "doesnt" in the text is missing an apastrophe xD

**Comment by TheBedrockMaster** [comment]
I have changes for this that should be coming at some point soon.

**Comment by ReikoAldrakar** [comment]
As in fixing the text or as in removing the bee? Or what is the plan there
