### ISSUE TITLE
[Bug]: Difficulty cannot be set to normal

### ISSUE THREAD

**Issue by dylan-mulligan** [AllTheMods/All-the-mods-9-Sky#613]
### Possible Fixes

Yes

### Modpack Version

1.0.7

### What happened?

When changing the difficulty on my dedicated server (/difficulty), all usages of the command work except `/difficulty normal`, which results in "commands.difficulty.failure" being thrown in server console and a command unrecognized message when done in game. This works for all other difficulty levels, so no clue what the issue is

**Comment by oly2o6** [comment]
Try turning the server off and changing it in the server.properties directly, we are not doing anything that should be effecting the difficulty and I cannot reproduce why this command is not working for you, also make sure to update to the latest version od the modpack.
