### ISSUE TITLE
[Bug]: Mekanism: Creative Energy Cube - energy is not stored

### ISSUE THREAD

**Issue by Co0kies** [AllTheMods/All-the-mods-9-Sky#615]
### Possible Fixes

Yes

### Modpack Version

1.0.9

### What happened?

Mekanism: Creative Energy Cube eating energy from Flux Point through Ultimate cable that is visually with energy, but show 0 as all power goes through, the Cube itself show "0/Infinity" stored , no visual filling , no energy can be outputed from cube. Already spotted on 1.0.8.

![image](https://github.com/user-attachments/assets/c22be982-78c3-44d9-bf91-1cbf0a05bddf)

**Comment by TheBedrockMaster** [comment]
Have you energised it?

**Comment by Co0kies** [comment]
FF , nope , my bad :)

**Comment by Ta-Du** [comment]
I guess author didn't modify its NBT, causing it to become an energy trash can. ：）
