### ISSUE TITLE
[Crash] local server freeze



### ISSUE THREAD

**Issue by Noemkinator** [AllTheMods/All-the-mods-9-Sky#617]
After a singleplayer world starts, there is a possibility that the server will freeze and will not run, with more then 30+ minutes of 0 TPS but 60FPS all the time. World is run with a refined storage system that has about 350k items inside. Also the tps bug happens when afking, after about 5-6 hours sometimes 

After trying to run the world several times with no success of TPS ressurection, i left the world open overnight and got an error message:

Internal Exception: com.refinedmods.refinedstorage.network.PacketSplittingException: Failure Splitting on Channel "refinedstorage:main_channel". Number of Packets sent 10, Number of Packets expected 12, maximum number of packets for a message of this type 0

**Comment by Noemkinator** [comment]
After crash, tried to run it again, and TPS and everything was functioning for some time, until i opened a Refined Storage Crafting Grid, and the screen went black and the server froze, but the game still running with screen black but no possibility of any interaction with the game.

**Comment by Noemkinator** [comment]
The world and last three logs on gdrive  [here](https://drive.google.com/drive/folders/1nlllY8kbiH50_0iUE3IaN7e22bo_zKDS)

**Comment by oly2o6** [comment]
That appears that your refined storage system is corrupted, possibly by too many item types
