### ISSUE TITLE
[Quests issues]: 'RFTools Storage' Quest Cannot Be Completed

### ISSUE THREAD

**Issue by AscendInTime** [AllTheMods/All-the-mods-9-Sky#618]
### Modpack Version

1.0.9

### Describe the issue

Cannot complete the first RFTools Storage Quest under "Basic Storage". I have tried editing mode to complete the quest and still it will not complete. Completely closing out and relaunching the game did not fix the issue. Not sure if it could be relevant but the world was started in 1.0.5 I believe i had completed all other quests in the 'Basic Storage' tab around then and am only returning to this section now just to 100% everything, I could not find a config file either to complete it that way.

I'm not sure what steps would need to be taken to recreate the issue. I haven't changed any settings that I know of with FTB quests as all other quests have been working as normal and I have also been able to complete other quests I have come across that have the same task as this one. 

![1](https://github.com/user-attachments/assets/169204aa-7e28-4e50-93c5-58b936efc26b)
![2](https://github.com/user-attachments/assets/3e20fc34-5a47-40e8-9cd4-13e4d16f0a03)

**Comment by oly2o6** [comment]
Check the dependencies for the quests by hovering the item in the top left, it has quests that need to be completed on other pages.

**Comment by AscendInTime** [comment]
Says no dependencies. I did check that when I was first trying to figure it out so I'm guessing if there are dependencies I've already completed them.

**Comment by AscendInTime** [comment]
Nevermind I guess. I click on the check mark again thinking it still wouldnt work and it actually went through. Not sure what the issue could have been. Like I said I had check the dependencies to see if i was missing something, didnt see anything, tried to force it through with editing mode, still didnt work but now for some reason it went through.
