### ISSUE TITLE
[Bug]: ProjectE

### ISSUE THREAD

**Issue by 10BamberJ** [AllTheMods/All-the-mods-9-Sky#62]
### Possible Fixes

Yes

### Modpack Version

1.0

### What happened?

Not much of a bug but more of a question on why everything has no EMC.
Why add projectE but dont allow any kind of equivelent exchange?

**Comment by billbertking1** [comment]
It was decided that ProjectE would be used for building blocks and such rather than resources as ProjectE tips the scales of balance too much when used with resources. Only building blocks will be added, nothing else.
