### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Cabot892** [AllTheMods/All-the-mods-9-Sky#621]
### Possible Fixes

Yes

### Modpack Version

1.20.1

### What happened?

I went to open my world but it did not appear so i tried the quickplay menu on the launcher to boot up my world but i keep on getting the same prompt: (FAILED TO LOAD DATA PACK ) it gives me 2 prompts 1. Safe mode. But when clicked it says the same i can go to title screen and resolve it there. 2. Go Back Title Screen. go to the title screen and resolve there. Please help i have had that world for a while and i dont want to lose it

**Comment by oly2o6** [comment]
reinstall the modpack, something has not downloaded correctly. You will just need to open folder and grab your saves folder, and then put that into the freshly installed modpack.
