### ISSUE TITLE
[Bug]: silent stick

### ISSUE THREAD

**Issue by Ta-Du** [AllTheMods/All-the-mods-9-Sky#622]
### Possible Fixes

Yes

### Modpack Version

1.09

### What happened?

The quest reward gave me a Blaze Rod as a material for the handle, but I can't use it for crafting, and the same goes for bones. I'm not sure if this is a bug or some other issue.
![image](https://github.com/user-attachments/assets/9cee9d40-113e-4bd8-9f25-c27d61de832f)
![image](https://github.com/user-attachments/assets/05030568-7f7c-43d3-abed-882138f38219)
![image](https://github.com/user-attachments/assets/47e3f268-a6e0-4542-bdbc-c72b679c49ba)
![image](https://github.com/user-attachments/assets/cae7cb99-b1a2-4b52-994f-c1253d96b41e)
![image](https://github.com/user-attachments/assets/737ab907-fbf2-47ad-a146-925c6e993c5f)
![image](https://github.com/user-attachments/assets/3e3ffecc-3c9e-4631-b70d-61ef78bfe88c)

**Comment by YocyCraft** [comment]
Blaze rod itself is already a stick, you can use it to craft tools and gears directly

**Comment by Ta-Du** [comment]
> 烈焰棒本身已经是一根棍子了，你可以直接用它来制作工具和齿轮

The problem has been solved, thank you
![image](https://github.com/user-attachments/assets/5b7f2794-7379-41e3-b5cf-52c2a44f4076)
