### ISSUE TITLE
[Bug]: JEI Crash When press R on mekanism:alloy_reinforced or mekanism:alloy_atomic items

### ISSUE THREAD

**Issue by YocyCraft** [AllTheMods/All-the-mods-9-Sky#627]
### Possible Fixes

Yes

### Modpack Version

1.0.9

### What happened?

Every time when I press R on mekanism:alloy_reinforced items to look recipes, the game crashes.

### latest.log

https://gist.github.com/YocyCraft/ca6fba1aefa2d5094e3c9e3b9761e902

**Comment by YocyCraft** [comment]
Fix please

**Comment by YocyCraft** [comment]
Fix please

**Comment by YocyCraft** [comment]
Fix please!! If this bug can't be fixed I can't play this modpack

**Comment by Demsli** [comment]
> Fix please!! If this bug can't be fixed I can't play this modpack

You can still use left click to see the recipe instead of R, right? It is a minor inconvenience, but not pack breaking really

**Comment by YocyCraft** [comment]
> > Fix please!! If this bug can't be fixed I can't play this modpack
> 
> You can still use left click to see the recipe instead of R, right? It is a minor inconvenience, but not pack breaking really

Left click also trigger the same bug I've tested

**Comment by YocyCraft** [comment]
updated to 1.1.0 and problem fixed. Don't know why.
