### ISSUE TITLE
[Quests issues]: Is there a bug in the quest or in the game?

### ISSUE THREAD

**Issue by laise2811InMinecraft** [AllTheMods/All-the-mods-9-Sky#63]
### Modpack Version

1.0.0

### Describe the issue

in the quest it says that I can sift through 64 blocks at a time, but I can only sift through 25 blocks and in the quest it says that I can set it up somehow with an ultimain, but I don’t know how, tell me how to do it(
![Skjermbilde 2024-06-01 220411](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/171450245/b4c9f00f-fec7-4979-9bc1-cdbed8ff39cd)

**Comment by billbertking1** [comment]
To increase max manual sieving range, firstly close your world/server.
Next, navigate to `/instance/world/serverconfig/` and find `exdeorum-server.toml`
Open it with the editor of your choice (Notepad is fine if you don’t have any others, though personally I recommend vscode)
Replace the contents of that config with what’s found here: https://github.com/AllTheMods/All-the-mods-9-Sky/blob/dev/defaultconfigs/exdeorum-server.toml
Save the file, and load your world/server and enjoy!

(I copied this from discord, hopefully it doesn't get too messed up)
