### ISSUE TITLE
[Quests issues]: How Can I Get Milk In Atm 9 In The Sky?

### ISSUE THREAD

**Issue by Cabot892** [AllTheMods/All-the-mods-9-Sky#635]
### Modpack Version

new one

### Describe the issue

How do i get milk. i need slime for a quest and it says to make it i need MILK

**Comment by Amoerrt** [comment]
Make a grassland and wait for cows and other animals to show up

**Comment by Cabot892** [comment]
how large?

**Comment by Amoerrt** [comment]
The larger the range, the greater the probability of generation.
