### ISSUE TITLE
2 Quests for Personal Shrinking Device

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#64]
### Modpack Version

1.0

### Describe the issue

In the Quest Chapter 'Tips and Tricks' there are 2 quests for getting a personal shrinking device, the right one seems useless.
![2024-06-02_09 37 36](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/59d71f37-4611-4c25-98d6-1065502f788a)
![2024-06-02_09 37 24](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/b3b60db8-fe34-413b-a841-63d0add19a69)

**Comment by ToshibaEC0Microwave** [comment]
Boom tips and tricks is getting reworked
