### ISSUE TITLE
Impossible to complete bee quests that require drops from possessed warden. 

### ISSUE THREAD

**Issue by asoshinsky** [AllTheMods/All-the-mods-9-Sky#647]
### Modpack Version

1.1.0

### Describe the issue

To get a warden disc we have to kill the possessed warden. But to summon the possessed warden we have to sacrifice axolotl! and so far there is no way of acquiring axolotl or generating lush cave biomes... 
![image](https://github.com/user-attachments/assets/8fddeee4-91eb-4ad2-81f0-8b7239fba705)
![image](https://github.com/user-attachments/assets/84f573e2-f16c-4c5d-a3be-e34381aa4ce8)
![image](https://github.com/user-attachments/assets/147f88d2-cbae-49b6-aaf8-cfb175a30e8e)

**Comment by TheBedrockMaster** [comment]
> Botania's Cocoon of Caprice can spawn axolotls when submerged in water. It's a rare result, though, so you might need a few dozen attempts.

**Comment by asoshinsky** [comment]
@TheBedrockMaster thank you so much! I was totally unaware of this method!

**Comment by ReikoAldrakar** [comment]
In addition to this:
Use a gaia spirit on the Cocoon to force a rare summon -> Axolotl, Dolphin or Glow Squid
Else the chance for any of these is 5% I think or less

I was very unlucky and had ~50 cocoons before using the gaia spirit on it, then I had it first try
