### ISSUE TITLE
'Compact Machines # delete?' Quest

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#65]
### Modpack Version

1.0

### Describe the issue

The quest 'Compact Machines # delete' in the 'Tips and Tricks' Chapter says 'This item is serves' instead of 'This items serves', Quest probably needs to be redone anyway.
![2024-06-02_13 49 11](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/b56dd4e9-7855-413c-a613-02ae0c4fa5b8)

**Comment by ToshibaEC0Microwave** [comment]
Same as before
