### ISSUE TITLE
[Crash]: JEI/Alchemistry LiquifierScreen

### ISSUE THREAD

**Issue by Jared87** [AllTheMods/All-the-mods-9-Sky#650]
### Possible Fixes

Yes

### Modpack Version

1.1.0

### What happened?

Client is crashing every time when i  try to open the JEI recipesof the Alchemistry Liquifier.

### Crash Log

https://gist.github.com/Jared87/5d3bf50442743079e58b91417050a00a

**Comment by TheBedrockMaster** [comment]
Duplicate of https://github.com/AllTheMods/All-the-mods-9-Sky/issues/641
