### ISSUE TITLE
Seems impossible to get the Elder Guardian kill for bounty quest

### ISSUE THREAD

**Issue by asoshinsky** [AllTheMods/All-the-mods-9-Sky#652]
### Modpack Version

1.1.0

### Describe the issue

The bounty board quest says to kill the elder guardian, however, I don't see any option on how to summon it. You can summon a possessed elder guardian but it doesn't count towards the completion of the bounty quest.
![image](https://github.com/user-attachments/assets/2101e5d8-058a-4cbf-9379-33cc806554be)
![image](https://github.com/user-attachments/assets/d9436229-3b7f-4298-ac88-150189724fe4)

**Comment by ReikoAldrakar** [comment]
As said [here in Reddit](https://www.reddit.com/r/allthemods/comments/1du6wb7/how_do_you_kill_the_elder_guardian_in_atm9_to_the/):

> There's an Ars ritual to summon guardians (it's aptly named "Summon Guardians"). Augmented with sea lanterns, it should spawn an elder guardian.
