### ISSUE TITLE
[Bug]: Mystical Agriculture silicon seed gives refined storage silicon and not ae2

### ISSUE THREAD

**Issue by sasufler** [AllTheMods/All-the-mods-9-Sky#664]
### Possible Fixes

Yes

### Modpack Version

1.1.1

### What happened?

Hello the silicon seed give refined storage silicon and not the ae2 one so i cant use it with my ae2 setup is it normal?

**Comment by TheBedrockMaster** [comment]
It should still be able to be used for AE2 recipes.
