### ISSUE TITLE
[Bug]: Netherite meshes are unobtainable in latest version

### ISSUE THREAD

**Issue by timurinal** [AllTheMods/All-the-mods-9-Sky#665]
### Possible Fixes

Yes

### Modpack Version

1.1.1

### What happened?

Since updating from 1.0.9a, the recipe for netherite meshes have changed making the netherite mesh unobtainable. The recipe used to be 1 netherite ingot, 1 smithing template, and 1 diamond mesh. Now the recipe wants 1 netherite mesh instead of 1 diamond mesh.

![image](https://github.com/user-attachments/assets/4827637b-8e4c-4d75-a390-631dddc83d6d)

### latest.log

https://gist.github.com/timurinal/b453ee28bf492b618d617968cad541c1

**Comment by psxlover** [comment]
Same is true for netherite tools and armor. They require a netherite tool/armor instead of a diamond one.

**Comment by timurinal** [comment]
Appears to just be a JEI visual bug, if you press 'U' over something diamond, it shows the correct recipe but if you look at the smithing recipe for anything netherite by pressing 'R' over the netherite item, it only shows Netherite Item -> Netherite Item instead of Diamond Item -> Netherite Item
