### ISSUE TITLE
[Bug]: Nether does not Generate w/ Any Natural Terrain

### ISSUE THREAD

**Issue by DrMkdaddy** [AllTheMods/All-the-mods-9-Sky#667]
### Possible Fixes

Yes

### Modpack Version

1.1.1

### What happened?

The nether does not generate with any natural terrain, only structures like Bastions and Nether Fortresses spawn, leaving a wide sprawling empty abyss. I attempted to delete the DIM-1 folder in order to regenerate the nether but that did not have any effect. 

### latest.log

https://mclo.gs/78POxde

**Comment by DrMkdaddy** [comment]
I tried again to send the logs and it seems like nothing turned out differently :(

**Comment by timurinal** [comment]
I think this is intentional, only the end generates normally

**Comment by Soeinfloo** [comment]
This is intentional, its a Skyblock Modpack

**Comment by Mitchell5200** [comment]
Fully intentional.

*Closing*
