### ISSUE TITLE
[Bug]: Item Filter Can Dupe Any Item

### ISSUE THREAD

**Issue by amoeba1125** [AllTheMods/All-the-mods-9-Sky#673]
### Possible Fixes

Yes

### Modpack Version

1.1.0

### What happened?

The item filter in the Ender IO mod can dupe any item. The steps to reproduce this are as follows:

1. Place the item you want to dupe into the filter's slot; this won't consume the item.
2. Use any item to left-click on the same slot, which will cause the two items to swap.
3. At this point, you will have the original item, as well as the item swapped out from the filter.

I recorded a video to explain this more clearly: [https://www.youtube.com/watch?v=H7532FSAFYU&ab_channel=%E9%98%BF%E7%B1%B3%E5%B7%B4Amoeba](https://www.youtube.com/watch?v=H7532FSAFYU&ab_channel=%E9%98%BF%E7%B1%B3%E5%B7%B4Amoeba)
Left-clicking the used slot can clear the slot and allow for repeated use.

**Comment by psxlover** [comment]
Duplicate to #653 and there is also a bug ticket in EnderIO github.
