### ISSUE TITLE
[Quests issues]: Apotheosis Quest missing item

### ISSUE THREAD

**Issue by Dexos07** [AllTheMods/All-the-mods-9-Sky#674]
### Modpack Version

Force 47.2.20

### Describe the issue

I can't complete this quest
![2024-08-13_22 24 08](https://github.com/user-attachments/assets/7aeba0d7-1934-4257-80a9-6987d6b3f9ad)

**Comment by TheBedrockMaster** [comment]
Update, this has since been fixed. Also it is asking for the modpack version, not the forge version.
