### ISSUE TITLE
[Bug] Current Version of JEI doesn't show ExDeorum drop rates

### ISSUE THREAD

**Issue by alexandreclalex** [AllTheMods/All-the-mods-9-Sky#676]
### Possible Fixes

Yes

### Modpack Version

1.1.1

### What happened?

Same issue as: https://github.com/thedarkcolour/ExDeorum/issues/108

Fixed in JEI 15.12.2.52

**Comment by ReikoAldrakar** [comment]
Dupe of #669

**Comment by alexandreclalex** [comment]
my b, missed that in my search. Closing.
