### ISSUE TITLE
[Quests issues]: Mystical Agriculture

### ISSUE THREAD

**Issue by lafflam** [AllTheMods/All-the-mods-9-Sky#683]
### Modpack Version

1.1.1

### Describe the issue

On the Phytogenic Isolator branch, the questline fails to acknowledge that I have successfully completed sand, dirt and fire seeds, and PhytoGro. The gray check marks won't turn green and give me credit for completing these steps.

Possibly related, drilling down into the Dirt Seeds quest, the the quest correctly recognizes that I have made dirt seeds, however the quest fails to recognize that I have also made the fire seeds.

![2024-08-18_14 22 38](https://github.com/user-attachments/assets/4288ee26-4996-482f-9314-481dff03fbb8)

**Comment by ToshibaEC0Microwave** [comment]
It's showing that the dependencies are not completed yet. The dirt seeds one needs the sand one completed and the sand one needs the welcome quest completed.

**Comment by TheBedrockMaster** [comment]
If you have a quest that isn't completing, you need to check if you completed all of it's requirements, you can check this by clicking on the quest, and clicking the small triangle/arrow on the top left of the quest popup. That will show all requirements.

If all the requirements are met, then the quest is probably actually stuck, which sometimes happens with FTB Quests:
To complete it, you need to be an OP (/op "username" from console) or have cheats enabled (if you didn't enable cheats in the world creation, open to LAN with cheats enabled).
With that, open the quests window.
Click the pencil icon on the bottom right, which enables editing mode.
Right click the quest in question.
Click Complete Instantly.

That will complete the quest, then disable the pencil button afterwards.

"I want the reward from the quest though"
In that case, in the quest popup, right click the reward, and click Reset Progress, that will let you claim the reward.
