### ISSUE TITLE
[Quests issues]: 

### ISSUE THREAD

**Issue by givemehelpnow** [AllTheMods/All-the-mods-9-Sky#688]
### Modpack Version

ATM9 TTS

### Describe the issue

Apotheosis Quest "Infusion Enchanting" is complete but can't be checked off. like, even though i complete the quests beyond that quest, i get no rewards.
![Screenshot 2024-08-21 180236](https://github.com/user-attachments/assets/e2a9cdf5-60be-47e2-b19e-13dc653c29b7)
![Screenshot 2024-08-21 180311](https://github.com/user-attachments/assets/952595d2-a56a-4d68-81df-0c13c50e9b5d)

**Comment by ToshibaEC0Microwave** [comment]
Just a bug with FTBQuests. Try restarting the progress of the quest via (having editing mode on) and right clicking it then selecting resetting progress.
