### ISSUE TITLE
[Quests issues]: THE ULTIMATE PHYTO Requirements

### ISSUE THREAD

**Issue by 007Bondo** [AllTheMods/All-the-mods-9-Sky#690]
### Modpack Version

1.1.1

### Describe the issue

The requirements for the "THE ULTIMATE PHYTO" quest are 3 Twinite Flux Linkage Amplifier and 1 Draconic Integral Compnent, and the description for the quest says "The fastest augments for a Phyto, good job." (thanks) However, while the Twinite Flux Linkage is the highest Flux Linkage tier, there are 2 higher Integral Component tiers than the Draconic. The Melodic provides an 8.5x boost and the Stellar provides a 12x boost.
The two extra tiers are from Thermal Endergy, which also has the Efficiency Nullifier Augment which, while not a direct crafted upgrade, is a straight base power upgrade from the Twinite F.L.A. My guess is this mod was added after the questline was written and forgotten about when the mod was added.

**Comment by 007Bondo** [comment]
Did some more math on optimal augment setups. So far, the most efficient and the fastest setup seems to be 1x Stellar Integral Components, 2x Twinite Flux Linkage Amplifiers, and 1x Energy Nullifier Augment.

I am more than happy to be proven wrong if someone else finds a better setup. My math was done in a manic state in google sheets.

**Comment by MoonDance911** [comment]
Hi the server i play on did some experimenting and the best setup is 1x stellar, 2x energy nullifier augment, and 1x efficiency nullifier augment.
