### ISSUE TITLE
[Quests issues]: Quests names and descriptions are bugged

### ISSUE THREAD

**Issue by Captn138** [AllTheMods/All-the-mods-9-Sky#691]
### Modpack Version

1.1.1

### Describe the issue

Hello, I started playing the pack on **server** on version 1.1.0 and noticed some Draconic evolutions quests names and descriptions were not properly evaluated.
I updated the modpack today on version 1.1.1 and they still are. Moreover the new creative and oreberries quests are all in the same state.
![image](https://github.com/user-attachments/assets/6b39b5d4-5ca6-403a-9af6-781b861a4db2)

Is there some manual fix I can do because is is the consequence of updating the pack, or is this a real issue in the pack ?

Thanks

**Comment by MaxwellRU** [comment]
i have the same issue, but not only with OreBerries.. with a several quest lines..

**Comment by riley094** [comment]
Why was this closed? There was no resolution, I'm still having this issue
