### ISSUE TITLE
[Bug]: Productive trees Black ember sapling

### ISSUE THREAD

**Issue by Zoom3756** [AllTheMods/All-the-mods-9-Sky#694]
### Possible Fixes

Yes

### Modpack Version

1.1.1

### What happened?

you cant find the black ember sapling anywhere it is supposed to be found in bastions I've looked in over 30 so far and have only found nether wood saplings. you cannot progress with this mod without the dark ember sapling.

**Comment by Rapchor** [comment]
Got the same issue - just can't find the sapling

**Comment by Vigodard** [comment]
Same issue. I've been to over 50 bastions at least. Even have mystical agriculture luck 3 applied. So frustrating

**Comment by pellizzari-corey** [comment]
You have to go to Treasure bastions to find them. They only spawn in the bottom chests next to the gold blocks. They are pretty rare. But i found 1 in ATM9 To the Sky 1.1.1

**Comment by Vigodard** [comment]
> You have to go to Treasure bastions to find them. They only spawn in the bottom chests next to the gold blocks. They are pretty rare. But i found 1 in ATM9 To the Sky 1.1.1

I had been to at least 8 of those bastions, and knew exactly the chest you were talking about, but never found it. But after seeing your post I thought I'd give it another try. And the very first new one I found had the sapling! Thanks
