### ISSUE TITLE
[Bug]: Can't craft awakened Activation Crystal from Blood magic

### ISSUE THREAD

**Issue by erdanilevicius** [AllTheMods/All-the-mods-9-Sky#695]
### Possible Fixes

Yes

### Modpack Version

1.1.1

### What happened?

Clicking on the recipe of the Awakened Activation Crystal there's no crafting recipe for it. Cannot progress further into questline.
![image_2024-08-24_160015670](https://github.com/user-attachments/assets/030c97ac-5107-4143-9b38-5f0c923dc17c)

**Comment by Mitchell5200** [comment]
the Awakened activation crystal is not used in any BM quests, and is listed as a NYI item in the blood magic guide book "Sanguine Scientiem".
All current BM rituals only need the weak activation crystal at this stage.
