### ISSUE TITLE
Gate Pearl Quests Autocompleting

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/All-the-mods-9-Sky#70]
### Modpack Version

1.0

### Describe the issue

I made the first gateway and it completed tasks in any quests requiring any gateways.
![2024-06-02_19 34 53](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/82f6ffe2-af50-402d-baf8-227b7618f2d1)
![2024-06-04_17 12 28](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/164738841/2639688c-217d-4a3c-bc68-96e030466580)

**Comment by ToshibaEC0Microwave** [comment]
This one is a bug that because of the way the gateways work it registers that any gateway counts as the specific one. Should be fixed with it being told to match NBT with hopefully no problems
