### ISSUE TITLE
[Quests issues]: cant craft vibranium

### ISSUE THREAD

**Issue by witherofek** [AllTheMods/All-the-mods-9-Sky#704]
### Modpack Version

1.1.1

### Describe the issue

i have all necessary items on the summoning altar, i placed the allthemodium ingot last, and nothing happened and i dont understand why
![2024-09-06_17 10 36](https://github.com/user-attachments/assets/a62ecd58-f182-4830-9424-ea6f87d93737)
![2024-09-06_17 10 38](https://github.com/user-attachments/assets/d6b68f6f-0175-4833-8c5e-9fea222c40f8)

**Comment by ToshibaEC0Microwave** [comment]
Can't see how this is a quest issue but are we sure that's a bucket of life from blood magic? And sometimes bug happens, resetting the pattern and even breaking and replacing the altar should fix it.
