### ISSUE TITLE
[Bug]: Recipe for Graphite Seeds ( Mystical Agriculture ) not present.

### ISSUE THREAD

**Issue by A-LonelyWolf** [AllTheMods/All-the-mods-9-Sky#707]
### Possible Fixes

Yes

### Modpack Version

1.1.1

### What happened?

Graphite essence is enabled, and can be used to craft graphite ingots, however the recipe for graphite seeds is none-existant.
See screenshot, no recipe with infusion altar.
![2024-09-08_11 20 42](https://github.com/user-attachments/assets/d1d6a4fe-a635-4540-9fcd-aab75e624d6b)

Found a possible fix though, not sure if it's enough.
Here is the fix I found:
In the file crafting.js, you have the path to find in at the top of the screenshot.

![image_2024-09-08_112456558](https://github.com/user-attachments/assets/d493baa2-2e86-44cf-bdf8-661436f004a2)

The name of the block that should be used for crafting recipe is bigreactors:graphite_block, change it to biggerreactors:graphite_block. Same with cyanite but cyanite is disabled in the pack.

**Comment by nysos3** [comment]
Can confirm this fixed for me, so thank you!
