### ISSUE TITLE
[Crash]: Alchemistry Liquifier JEI crush

### ISSUE THREAD

**Issue by Aghanimoff** [AllTheMods/All-the-mods-9-Sky#709]
### Possible Fixes

Yes

### Modpack Version

atm9sky-1.1.1

### What happened?

An error occurs every time I try to view recipes from liquefier from the Alchemistry mod.

step 1: PCP for Liquifier in JEI 
step 2: Switch in JEI to the tab with the device
step 3: Crush

![image](https://github.com/user-attachments/assets/5aaa6c7f-7653-4246-95cf-be94e00cf78c)

### Crash Log

https://gist.github.com/Aghanimoff/3136d492d09f0288a4307f422fe33f13

### Latest.Log

https://gist.github.com/Aghanimoff/585a2899757b6e9f6fa457ff965bf63b

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/All-the-mods-9-Sky/issues/641
