### ISSUE TITLE
[Bug]: wrong created time in Curseforge. It shows this pack is been create in Jan 28, 2024. Which need to be change to May 28, 2024

### ISSUE THREAD

**Issue by alexzhaozzh** [AllTheMods/All-the-mods-9-Sky#71]
### Possible Fixes

Yes

### Modpack Version

1.0.0

### What happened?

wrong created time in Curseforge. It shows this pack is been create in Jan 28, 2024. Which need to be change to May 28, 2024

<img width="310" alt="1717325207133" src="https://github.com/AllTheMods/All-the-mods-9-Sky/assets/98642083/b834f8f2-ccc8-4942-a05e-e17fe0b61649">

**Comment by billbertking1** [comment]
That's because the page was created back in January to prevent from stealing the page and causing a delay in release.
