### ISSUE TITLE
[Quests issues]: Quest Chapters from ATM9

### ISSUE THREAD

**Issue by Armicane** [AllTheMods/All-the-mods-9-Sky#710]
### Modpack Version

1.1.2

### Describe the issue

There are duplicates of the Allthemodium and Mystical Agriculture questlines, and the quest decriptions are all code.

**Comment by magnite5** [comment]
Just want to add that i've got the same issue, with two different mystical-agriculture questlines, and bugged descriptions and names in the new one as of updating my pack (see below)
![image](https://github.com/user-attachments/assets/9cc32d71-4f53-43df-84e5-89eef6897883)
![image](https://github.com/user-attachments/assets/e74d6e69-c2db-4aaa-9616-596cb322dc78)

**Comment by Armicane** [comment]
and the alloy tools from atm9 dont have crafting recipes but they have quests

**Comment by Crasben** [comment]
> Just want to add that i've got the same issue, with two different mystical-agriculture questlines, and bugged descriptions and names in the new one as of updating my pack (see below) ![image](https://private-user-images.githubusercontent.com/87040030/365837793-9cc32d71-4f53-43df-84e5-89eef6897883.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NjY4MDYsIm5iZiI6MTcyNTk2NjUwNiwicGF0aCI6Ii84NzA0MDAzMC8zNjU4Mzc3OTMtOWNjMzJkNzEtNGY1My00M2RmLTg0ZTUtODllZWY2ODk3ODgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDExMDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZGQxOGIyNTFjNjA3YzI2OTI4Y2I3NTM5MTEzYzkxMDI0MDQwNWI1NDMzMjgxZDMwNzIyNDc1ZjlmZGEzNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._bfqhpVlUz0S40HLR6lwQTmSiC8_0KVpqYNGzeWeHvw) ![image](https://private-user-images.githubusercontent.com/87040030/365838533-e74d6e69-c2db-4aaa-9616-596cb322dc78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NjY4MDYsIm5iZiI6MTcyNTk2NjUwNiwicGF0aCI6Ii84NzA0MDAzMC8zNjU4Mzg1MzMtZTc0ZDZlNjktYzJkYi00YWFhLTk2MTYtNTk2Y2IzMjJkYzc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDExMDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1YTBhNWM5ZmZjMTExNWRlOTM4MzFlYzk0NmM0OGNhZGYxMzVjMDg1ZjVmMzkxMzA4MjMzNTk4MDdhMmVhNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M9hRcfQct4fH1JWmOGbqNgvkpXg1CE6pu8EiBQG_0c4)

Yeah, i'm having the same issue.

**Comment by GesundesWasser** [comment]
Same here

**Comment by Eric130700** [comment]
Any solution on that?

**Comment by TheBedrockMaster** [comment]
> Any solution on that?

The solution is deleting the chapters.
