### ISSUE TITLE
Error while loading game

### ISSUE THREAD

**Issue by PanikHuhn** [AllTheMods/All-the-mods-9-Sky#72]
### Possible Fixes

Yes

### Modpack Version

1.0

### What happened?

![2024-06-02 15_57_30-Minecraft Forge_ 1 20 1](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/150162069/cc0bfe05-edee-411d-8404-d55bc4b366ab)

I get this Error when I try to load the game which is weird because 4 hours ago it worked flawless.

### Crash Log

https://gist.github.com/PanikHuhn/791d461bf6b9811b1ba74f28d64373ef

### Latest.Log

https://gist.github.com/PanikHuhn/8272d72d42d4476daf959c99c66b4fda

**Comment by PanikHuhn** [comment]
UPDATE: After reinstalling the Modpack it works again. I just had to copy-paste my savefile to the new Modpack.

**Comment by oly2o6** [comment]
Yeah your game did not install correctly, glad you got it sorted! closing
