### ISSUE TITLE
[Quests issues]: Ultimate Phyto Quest Broken

### ISSUE THREAD

**Issue by sicklyFoxJay** [AllTheMods/All-the-mods-9-Sky#720]
### Modpack Version

1.1.2

### Describe the issue

Seems that the flux linkage amplifier for this quest no longer exists, but the quest itself wasn't updated with the new max amplifier.
![image_2024-09-14_045510312](https://github.com/user-attachments/assets/60cd1932-b1d1-493f-8dd2-778a732cc74f)

**Comment by Arrowpuppet** [comment]
The item still exists, thermal extra just updated the item ID so the old one isn't recognized anymore. 

For now you can do what I did and open up the "elmystical_agriculturerr.snbt" file in "(.minecraft location)/config/ftbquests/quests/chapters" with any text editor and replace "thermal_extra:machine_speed_augment_4" with "thermal_extra:dragonsteel_machine_speed_augment". 

If you're playing on a server though, all you can really do is try to convince the server admin to implement that same fix server-side.
