### ISSUE TITLE
[Bug]: Teleport Pad not available

### ISSUE THREAD

**Issue by Shurugwi** [AllTheMods/All-the-mods-9-Sky#722]
### Possible Fixes

Yes

### Modpack Version

1.1.2

### What happened?

Teleport Pad cannot be crafted. The text in the allthemodium quest line is not  available either.
![image](https://github.com/user-attachments/assets/973084c1-3b76-44aa-9cc6-06b3a86e3931)

**Comment by TheRasmus42** [comment]
Same issue. Teleport Pad is not available.

**Comment by itskenny7** [comment]
Wasn't this a mistake that got added from ATM9?

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/All-the-mods-9-Sky/issues/710
