### ISSUE TITLE
[Bug]: Items dont have emc values

### ISSUE THREAD

**Issue by rainiermix** [AllTheMods/All-the-mods-9-Sky#724]
### Possible Fixes

Yes

### Modpack Version

1.1.2

### What happened?

While playing I noticed that most stuff cant be learned in the transmutation table and most things do not have an EMC value like they are supposed to. Even items from the original mod like, a Klein star, alchemical coal, and dark/red matter don't have any EMC values and cannot be used.

**Comment by TheBedrockMaster** [comment]
This is 100% intentional. Most of the items with EMC are mob drops or building blocks.

**Comment by rainiermix** [comment]
> This is 100% intentional. Most of the items with EMC are mob drops or building blocks.

But you cant progress through ProjectE properly because there aren't even values for the alchemical coal or dark matter.

**Comment by TheBedrockMaster** [comment]
You can craft them.
