### ISSUE TITLE
[Bug]: JEI Recipes Error out when using usage key on Configuration Tool

### ISSUE THREAD

**Issue by Tukermine** [AllTheMods/All-the-mods-9-Sky#73]
### Possible Fixes

Yes

### Modpack Version

1.0

### What happened?

This is an issue I discovered when I used the JEI Usage key bind (U) on the Functional Storage Configuration Tool and it caused about 99% of items in JEI to turn into an error symbol.
![image](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/30537523/a5066a2c-9afe-48af-afea-e384c4b033d5)

I used the /reload command, as well as restarted my world with no luck
I managed to fix it by going to curseforge and using the repair profile.
This is repeatable as I tested it after I loaded the game back up and it caused the bug once again.

### latest.log

https://gist.github.com/Tukermine/98d5451c23ab819d31627fc338d550d1

**Comment by oly2o6** [comment]
Can you check what else you have bound to U?
