### ISSUE TITLE
[Crash]: FastSuite Crash Server when log is put in crafting slot

### ISSUE THREAD

**Issue by Rizel67** [AllTheMods/All-the-mods-9-Sky#74]
### Possible Fixes

Yes

### Modpack Version

1.0.0

### What happened?

Hi.
I just want to let you know that i had to remove Fastsuite from atm 9 TTS to avoid crashing my server.
I've just setup a instance in my pterodactyl panel and everytime i put an oak log in my crafting slot my server crash.
So straight to the beggining.
I did delete the world once to try and i tried to run it with java 16 and java 17.
Did not have issue in solo

Let me know if need more informations.

### Crash Log

https://pastebin.com/y8EHTT2P

**Comment by oly2o6** [comment]
I cannot seem to reproduce this error, I see your crash report states outofmemory error, how much do you have allocated for the modpack?

**Comment by Rizel67** [comment]
Hi. 
The issue vanished with atm9 tts 1.0.1 but it appears again with 1.0.3 and 1.0.4

For the allocated memory part i've put 16gb for this instance.

**Comment by oly2o6** [comment]
That crash report is stating a ticking block entity error, could you go into world/server-config/forge-server.toml and change RemoveErroringblockentites=true?

**Comment by Rizel67** [comment]
It did fix my issue. I was able to remove the cpu limitation that i've had to put today. 
I didn't thought about forge-server.toml so thanks for the hint
