### ISSUE TITLE
[Bug]: Minecraft start screen font

### ISSUE THREAD

**Issue by CoTheCoder** [AllTheMods/All-the-mods-9-Sky#746]
### Possible Fixes

Yes

### Modpack Version

1.1.2

### What happened?

All the words for the start screen are boxes, i just updated from 1.1.1 which was working just fine and has the normal ATM9 home screen, the new version has the normal Minecraft home screen and all of it is just boxes but isn't the modded layout I'm used to seeing so I'm curious if there is an issue I have with that specific mod, any help would be great thank you!

**Comment by GamerFizi** [comment]
I'm getting this information based on the mods I removed, I installed an old version of these mods and it opened correctly.
Note: I didn't test other significant ways, nor did I try to look deeper, but these mods had some impact on the opening, which I think was probably the mekanism.


[ Mekanism, Mekanism Generator, Tombstone e CC-tweaked.]

**Comment by PawloZiom** [comment]
I think this is low end computer related. My friend has it on his laptop too but i don't have it on my PC.
