### ISSUE TITLE
[Bug]: Item Refill (not 100% sure if this is intended or a bug)

### ISSUE THREAD

**Issue by Bloemenpot** [AllTheMods/All-the-mods-9-Sky#75]
### Modpack Version

Atm 9 Sky 1.0.0

### What happened?

So when building and you run out of a item in your current slot, it refills that item.
However this does not happen when running out of a item when sieving.

Im not sure if this is a intended thing or a bug. But if it is intended, is there a config to change this?

**Comment by oly2o6** [comment]
Not intended, working on fixing these as they show up (1.0.1 did have a few fixes but we are not 100% done with slot refills)
