### ISSUE TITLE
[Bug]: "THE ULTIMATE PHYTO" quest requires missing item

### ISSUE THREAD

**Issue by Leo40Git** [AllTheMods/All-the-mods-9-Sky#756]
### Possible Fixes

Yes

### Modpack Version

1.1.2

### What happened?

This quest in the "Mystical Agriculture" chapter (the ATM9sky one, not the leftover ATM9 one) requires `thermal_extra:machine_speed_augment_4`.

![image](https://github.com/user-attachments/assets/e56ef5b7-193e-4746-9d1d-6a1b0297bbfb)

I'm assuming this should be 3x Abyssal Flux Linkage Amplifier (`thermal_extra:abyssal_machine_speed_augment`)?

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/All-the-mods-9-Sky/issues/720
