### ISSUE TITLE
[Bug]: SoulSand isn't dropping any Prosperity Shards..

### ISSUE THREAD

**Issue by NetherKingHD** [AllTheMods/All-the-mods-9-Sky#759]
### Possible Fixes

Yes

### Modpack Version

1.1.2

### What happened?

Well where do i start..
In SinglePlayer Soulsand drops Prosperity Shards all the time
On our Server SoulSand isn't dropping any Prosperity Shards for all players.. 

can someone help?
Thanks.. <3

**Comment by TheBedrockMaster** [comment]
Make sure everything is working fine on your server. If you need more help ask on the ATM Discord server.
