### ISSUE TITLE
[Bug]:  allthemodium alloys got no Recipes

### ISSUE THREAD

**Issue by A009i8** [AllTheMods/All-the-mods-9-Sky#760]
### Possible Fixes

Yes

### Modpack Version

atm9sky-1.1.2

### What happened?

 allthemodium alloy got no Recipes

**Comment by TheBedrockMaster** [comment]
This is intended.

**Comment by A009i8** [comment]
why is the items thin ingame so useless

**Comment by A009i8** [comment]
> This is intended.

are you joking you have a quest part and its intended xDDD are you joking ????
![image](https://github.com/user-attachments/assets/31a48e16-2179-4dda-a39a-d2991eb81b45)

**Comment by TheBedrockMaster** [comment]
That quest chapter is a broken duplicate ported from ATM9 that needs to be removed. See https://github.com/AllTheMods/All-the-mods-9-Sky/issues/710
