### ISSUE TITLE
[Bug]: Right Clicking Grass Doesn't Work

### ISSUE THREAD

**Issue by tigeresssweetie** [AllTheMods/All-the-mods-9-Sky#77]
### Possible Fixes

Yes

### Modpack Version

Atm9 Sky 1.0.0

### What happened?

Quest says to right click grass for pebbles, but right clicking the grass does not do anything. Closing and reopening the game did not work.

### latest.log

https://gist.github.com/tigeresssweetie/dc79d74aed08e41be47249ca7ac65c65

**Comment by thevortex** [comment]
sneak and right click

**Comment by Daveawb** [comment]
Having this same issue,  sneak right-clicking grass with an empty hand, tool, or item (that doesn't place) does nothing. I'm stuck because of it.
