### ISSUE TITLE
[Bug]: opening the chemlib sucrose recipes and switching to the liquifier tab crashes game

### ISSUE THREAD

**Issue by mer2329** [AllTheMods/All-the-mods-9-Sky#777]
### Possible Fixes

Yes

### Modpack Version

1.1.2

### What happened?

like the title says opening the chemlib sucrose JEI recipes and switching to the liquifier tab crashes game. happens in both single player and server multiplayer.
crash log (uploaded by prism): https://mclo.gs/IYoRAan

### latest.log

https://gist.github.com/mer2329/fe368e6e41816de90170c67a58f9e20a

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/All-the-mods-9-Sky/issues/641
