### ISSUE TITLE
[Bug]:  item id not found (item missing)

### ISSUE THREAD

**Issue by Kwisma** [AllTheMods/All-the-mods-9-Sky#784]
### Possible Fixes

Yes

### Modpack Version

1.1.2

### What happened?

Unable to complete ftb task, item id not found (item missing)

![QQ20241128-154352](https://github.com/user-attachments/assets/10f521d5-57e7-4b38-b631-81c020a13399)

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/All-the-mods-9-Sky/issues/720
