### ISSUE TITLE
[Crash]: alchemistry and JEI can cause a crash

### ISSUE THREAD

**Issue by XinkangShi** [AllTheMods/All-the-mods-9-Sky#787]
### Possible Fixes

No

### Modpack Version

1.1.2

### What happened?

Using jei to check Liquifier usage will cause the game to crash

### Crash Log

https://gist.github.com/evolry/d45455828e00c9935dc1a42e7c26fea3

### Latest.Log

https://gist.github.com/evolry/fb8c4fd6de151ca063d6af36d9cd1e23

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/All-the-mods-9-Sky/issues/641
