### ISSUE TITLE
[Bug]: Igneous extruder not making netherrack

### ISSUE THREAD

**Issue by dYbIRitz** [AllTheMods/All-the-mods-9-Sky#79]
### Possible Fixes

Yes

### Modpack Version

all the mods 9 to the sky

### What happened?

igneous extruder not making netherrack from lava and witchwater, I also have a redstone block under the igneous extruder.  It does not make anything. pleaase help! Thanks!

**Comment by billbertking1** [comment]
It needs to be a netherrack block underneath, not redstone block.
