### ISSUE TITLE
[Bug]: Quantum Computer/Visual

### ISSUE THREAD

**Issue by I-Want-Ninja** [AllTheMods/All-the-mods-9-Sky#792]
### Possible Fixes

Yes

### Modpack Version

1.1.3 Newest

### What happened?

![grafik](https://github.com/user-attachments/assets/d7773286-29ce-420e-ab91-f3cd7f80962b)

dosnt show the active crafting

**Comment by I-Want-Ninja** [comment]
And is The AE Quantum Armor gona be available in the future?

**Comment by pedroksl** [comment]
Hey. All of those issues have been addressed. You can manually update the mod and it will work finally. The quantum armor was also added, with all of its upgrades.
