### ISSUE TITLE
[Crash]: AMD Driver related crash when arriving to main splash screen.

### ISSUE THREAD

**Issue by Wojayyy** [AllTheMods/All-the-mods-9-Sky#81]
### Possible Fixes

Yes

### Modpack Version

1.0

### What happened?

On relaunch of the pack, the forge loader would do its job and right as the loader moved into displaying the main splash screen, the game itself would not crash out, but would stop displaying and just end up as a taskbar icon. Would also get an AMD crash pop up, but it isn't a driver update or something pertaining to my GPU as nothing else shares this problem. This is a new sudden issue, the pack ran flawlessly prior to this.

### Crash Log

https://gist.github.com/Wojayyy/d20086848be34d65f9d8a9f614b869d8

### Latest.Log

https://gist.github.com/Wojayyy/04b90da0536ab82ecf1bdf3985e46612

**Comment by Wojayyy** [comment]
It is now launching normally. I'm unsure if anyone can replicate this or if it is pack related. If not, close this. Until then I'll leave it open for you silly little devs to look at.

**Comment by oly2o6** [comment]
Odd, going to close this as a one off, if you do get it again make sure your drivers are all upto date
