### ISSUE TITLE
[Bug]: Several ATM9TTS problems

### ISSUE THREAD

**Issue by LuciusV** [AllTheMods/All-the-mods-9-Sky#84]
### Possible Fixes

Yes

### Modpack Version

1.0.0

### What happened?

1. Ars Elemental Flashpine and Flashing Archwood Saplings are unbotainable (and cannot craft some glyphs because of this)
2. Botania Green Mystical Flower quest misses +10 xp quest reward
3. No soul lava?
Also some feedback:
4. I crafted Starbunkle charm and... No Ars Creo???
5. Witherproof glass gated too much
6. Crying obsidian gated too much.
7. Basic tier upgrade from sophisticated storage diappears after use (was reusable in ATM9NF)
8. Final (netherite) Mesh gated behind Occultism feels too much
9. Please consider making PneumaticCraft entirely optional and without quests (so 100% completion can be achieved)

**Comment by XaineDev** [comment]
womp womp
