### ISSUE TITLE
[Quests issues]: Flax Quest doesn't accept Thermal Cultivation Flax seeds

### ISSUE THREAD

**Issue by JL2210** [AllTheMods/All-the-mods-9-Sky#85]
### Modpack Version

1.0

### Describe the issue

I have a stack of Thermal Cultivation Flax Seeds and the quest requires specifically Supplementaries flax seeds. Both types of flax give string so I don't see a need to require one
![2024-06-03_03 03 46](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/38843657/bc104de0-11df-4a39-82a8-70ff359926b9)

**Comment by ToshibaEC0Microwave** [comment]
Being switched to any flax seeds
