### ISSUE TITLE
[SUGGESTION/BUG] No Curio slot for Terminals?

### ISSUE THREAD

**Issue by Bodadis** [AllTheMods/All-the-mods-9-Sky#86]
### **Modpack Version**
1.0.0

### **Describe the issue**
There is no Curio slot for AE2/RS terminals. Would be nice if it was added, (and maybe 1 or 2 more Charm slots).

**Comment by Satherov** [comment]
The AE Terminal can go into basically any slot, not sure about RS

**Comment by Bodadis** [comment]
> The AE Terminal can go into basically any slot, not sure about RS

True, but I'd prefer go into a specific Curio-slot. :)

**Comment by TheBedrockMaster** [comment]
Why do grids have their own curios slot in ATM9 but not TTS?
