### ISSUE TITLE
[Bug]: Cannot obtain fluffy puff seeds

### ISSUE THREAD

**Issue by Ozzymud** [AllTheMods/All-the-mods-9-Sky#87]
### Modpack Version

1.0.0

### What happened?

Tried both breaking grass and the market. Don't see any way in jei to obtain them.  

Edit: Was able to obtain them from the bag of seeds from Corail Tombstone. If this is supposed to be the way, kindly close this issue :)

**Comment by TheBedrockMaster** [comment]
Now you can get them from the market, you can close this issue.

**Comment by TheBedrockMaster** [comment]
Obtainable from the market, can be closed.
