### ISSUE TITLE
[ENHANCEMENT] Antiblocks Rechiseled and Simply Lights

### ISSUE THREAD

**Issue by Bodadis** [AllTheMods/All-the-mods-9-Sky#88]
Low priority but give it a thought about adding Antiblocks Rechiseled and Simply Light to the mod.

[Antiblocks Rechiseled](https://www.curseforge.com/minecraft/mc-mods/antiblocksrechiseled): Would be cool to have them EMC (since they serve no purpose except building)

[Simply Light](https://www.curseforge.com/minecraft/mc-mods/simply-light): Modern indoor lightning solution.

Cheers,
Bodadis

**Comment by TheBedrockMaster** [comment]
Adding EMC to all those would take a while unfortunately.
