### ISSUE TITLE
[Quests issues]: 

### ISSUE THREAD

**Issue by McKitten** [AllTheMods/All-the-mods-9-Sky#89]
### Modpack Version

1

### Describe the issue

Food and farming -> sugar sugar
The quest for 16 sugar cane does not mark as (any percentage) completed, possibly because sugar is marked as apotheosis rather than minecraft.

**Comment by TheBedrockMaster** [comment]
Works fine for me

**Comment by ToshibaEC0Microwave** [comment]
You shouldn't be able to obtain Minecraft sugarcane cuz apotheosis replaces it so this one's being closed
