### ISSUE TITLE
[Bug]: thermal series Igneous Extruder has no item slots

### ISSUE THREAD

**Issue by PowerMan2015** [AllTheMods/All-the-mods-9-Sky#90]
### Possible Fixes

Yes

### Modpack Version

1.0.0

### What happened?

thermal series Igneous Extruder has no item slots I can't put any items ine

**Comment by Bodadis** [comment]
Igneous Extruder only output items, the only items that it can take is Augments.

**Comment by billbertking1** [comment]
That's not a bug. That's how it's intended to operate.

**Comment by PowerMan2015** [comment]
> What are you trying to produce?

cobbled deepslate I can't put lava and packed ice in it

**Comment by Bodadis** [comment]
Place them on each side of the Igneous Extruder like this.

![2024-06-03_20 00 53](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/171534737/c2fca191-8f39-48d1-8d94-b4b20a1b4bf8)

**Comment by PowerMan2015** [comment]
> Place them on each side of the Igneous Extruder like this.
> 
> ![2024-06-03_20 00 53](https://private-user-images.githubusercontent.com/171534737/336178373-c2fca191-8f39-48d1-8d94-b4b20a1b4bf8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MzgwMjEsIm5iZiI6MTcxNzQzNzcyMSwicGF0aCI6Ii8xNzE1MzQ3MzcvMzM2MTc4MzczLWMyZmNhMTkxLThmMzktNDhkMS04ZDk0LWI0YjIwYTFiNGJmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QxODAyMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDc0YjRiYjhmYWExNDE5MmE5NzdlYTk5NDZiOTY2ZTc1YWQwZmZjOGNhMjk5YzAwMGE4Mzc1NTZhNDQwNjg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iKSOEUm_JEUbZtxZv1q2JVtKvTpev8zOCJJog6fcYdw)

oh ok thanks
