### ISSUE TITLE
[Bug]: Dupe item Bug

### ISSUE THREAD

**Issue by AArtha55** [AllTheMods/All-the-mods-9-Sky#92]
### Possible Fixes

No

### Modpack Version

1.20.1

### What happened?

in ATM9sky placing Compacting drawer from (mod: Functional Storage) and then Puting in "Max storage Upgrade" and then puting in any item, the item is duped in stack of ~45k in one inventory slot, when i placed "in this case placed block on ground", the stack of ~45k didn't wanish. 
![Screenshot 2024-06-03 215805](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/171614850/d235b60b-e44f-4753-a433-13f5e82708c7)
![Screenshot 2024-06-03 215859](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/171614850/55b8a657-8124-44de-9b0c-3aa90819c52a)
![Screenshot 2024-06-03 215927](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/171614850/c64440c1-2032-40ff-a926-364efeaaa1e2)
![Screenshot 2024-06-03 215956](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/171614850/69c894d8-c998-4203-8cb3-67881dcad745)
![Screenshot 2024-06-03 220002](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/171614850/ee212d1a-9d50-411d-81bb-ca42c0571f1e)

**Comment by 10BamberJ** [comment]
Max storage Upgrade looking like a creative item. + Cannot craft the item.

**Comment by AArtha55** [comment]
> Max storage Upgrade looking like a creative item. + Cannot craft the item.

Then its fair game ;)
