### ISSUE TITLE
[Bug]: Keybinds using [Modifier+Inventory Key] will be triggered when using [Inventory Key] bind without modifier.

### ISSUE THREAD

**Issue by Ianthasys** [AllTheMods/All-the-mods-9-Sky#96]
### Possible Fixes

Maybe?

### Modpack Version

1.0

### What happened?

When binding things like the Crafting Table on a Stick to `Alt+E` (this also works with Ctrl and Shift) when the "open inventory" bind is set to `E`, trying to open the inventory without the modifier key will also execute the keybind with the modifier, even if the modifier isn't pressed. This has been confirmed to also be the case when using similar bindings with the wireless AE2 Terminal by user `bodadis` on the discord.

My assumption is that this is a bug with forge, as if memory serves me correct, this same issue was present in ATM9 when the pack had upgraded forge versions somewhere around update 0.2.35 or so, which had to be upgraded again shortly thereafter when it was fixed in forge. Otherwise, I'm not even sure where to look to try to figure out what's causing the issue, as it spans multiple mods and I'm not familiar with what interfaces with how the controls system works.

### latest.log

N/A

**Comment by Ianthasys** [comment]
Issue seems to have been fixed with the update to Forge 47.2.20

**Comment by Eragonawesome** [comment]
I am still having this issue in the pack version 1.0.6 which is in forge 47.2.20, is there a workaround?
